### PR TITLE
Welcome, camera!

### PR DESCRIPTION
**Pull request by kholk**
UPDATE: Yukon sensors OK // Seagull not working, Rhine/Shinano phones OK

### CODE REVIEW

**Comment by kholk** [comment]
Don't merge until first squashed commit gets fixed. Forcepush on my repo will happen.

**Comment by kholk** [comment]
Merge

**Comment by CoolDevelopment** [comment]
What about other devices?

i. E. amami and togari

**Comment by kholk** [comment]
I don't have amami and/or togari, so I wasn't able to test the changes. 
Those should be fine with a proper DT that I can wrote in less than 5 minutes, but this PR wants to include work that I can prove it's working (sorry about Seagull). 

Others will follow in later commits. 
That's not delaying any plan we have on camera.

**Comment by erikcas** [comment]
amami inits fine last time I checked

**Comment by CoolDevelopment** [comment]
Okay nice

**Pull request merged**
