### PR TITLE
[1.3.3] Upgrade kernel memory management

### PR DESCRIPTION
**Pull request by kholk**
Those upgrades are for not-so-recently discovered problems with memory on Suzuran.
This will improve performance on memory allocation and reclaiming, other than allowing to reclaim more unmovable pages.

### CODE REVIEW

**Comment by kholk** [comment]
Please, test on at least two devices per platform. Specifically:
1. One tablet on ARM
2. One tablet on AArch64
3. One compact and one "regular" (3GB RAM) phone on ARM
4. One compact and one "regular" (3GB RAM) phone on AArch64.

**Comment by humberos** [comment]
Should we do a specific procedure/routine during this test ?
I am going to test it on Karin.

**Comment by kholk** [comment]
Not really. Just use the device, possibly do something heavy on page allocation and reclaiming, like opening a lot of apps and then closing them all together.

**Comment by kholk** [comment]
Tests are done.

PR is not making performance better, but makes mm to reclaim more pages that were unreclaimable without those patches, making slightly more memory to be available at no performance cost.

Merge!

**Pull request merged**
