### PR TITLE
[LA.UM.6.4.r1.] Up to LA.UM.6.4.r1-06100-8x98.0

### PR DESCRIPTION
**Pull request by humberos**
tag: LA.UM.6.4.r1-06100-8x98.0

### CODE REVIEW

**Comment by humberos** [comment]
no regressions on kagura.
ping  @kholk @oshmoun

**Comment by humberos** [comment]
@jerpelea 
please consider this patchset as a draft.
If all platforms are ok then you will be able to merge this tag directly.

**Comment by oshmoun** [comment]
tested on kugo (3dmark, camera, charging)
looks ok upon first glance

**Comment by kholk** [comment]
WARNING! Carefully test deep sleep and WiFi functionality on Loire platform. The mmc PM commit is sorta scary!

**Comment by humberos** [comment]
@kholk
Deep sleep is ok it seems.
Tested on suzu and kagura with WiFi enabled.

**Comment by jerpelea** [comment]
this one needs proper testing

**Comment by artem** [comment]
Are our blobs OK with e9adf0cee8013be2c645b6b49040259f053ec488?

**Comment by jerpelea** [comment]
they should not be affected but proper testing is needed

**Comment by oshmoun** [comment]
been running with this pr for a whole day on kugo, can't notice issues regarding wifi/deepsleep.
functions related to odm also seem to be in working order.

**Comment by kholk** [comment]
Should be ok then!

**Comment by jerpelea** [comment]
tested on DD lilac
looks also Ok

**Pull request merged**
