### PR TITLE
[2.3.2.r1.4] Linux 4.9.177

### PR DESCRIPTION
**Pull request by nathanchance**

### CODE REVIEW

**Comment by nathanchance** [comment]
Do hold off on merging this as there might be a revert coming down the pipeline for one of the commits in 4.9.177.

**Comment by nathanchance** [comment]
Alright, it should be fine now.

**Comment by ix5** [comment]
SoMC kagura seems fine with this.
Boots, RIL, camera ok.

**Comment by MarijnS95** [comment]
No regressions on Akatsuki DSDS, compiled with `clang`.

**Pull request merged**
