### PR TITLE
CAF Aosp/la.bf64.1.2.2 rb4.42

### PR DESCRIPTION
**Pull request by rcstar6696**

### CODE REVIEW

**Comment by rcstar6696** [comment]
@kholk i hope this is okay ?

**Comment by kholk** [comment]
I hope the same! :P needs to be tested on all platforms

**Comment by rcstar6696** [comment]
Sirius and castor_windy are okay

**Comment by humberos** [comment]
No problems here.
Target: Karin

**Comment by rcstar6696** [comment]
@erikcas @alviteri  can anyone of you test it on rhine its the only missing platform

**Comment by deepongi** [comment]
i tested sumire, it was fine also (per ex: same bugs)

**Comment by ergoen** [comment]
Compiled and run om amami and it seems to work as well as before.

**Pull request merged**
