### PR TITLE
[1.3.3] qdsp6v2 optimize size

### PR DESCRIPTION
**Pull request by scafroglia93**
- Reduce kernel size (Z3 with this is 8.6MB)
- Compile arm / arm64 ok 
- Tested on Z3

### CODE REVIEW

**Comment by scafroglia93** [comment]
@rcstar6696 Have you tested this on your device ?

**Comment by rcstar6696** [comment]
Yes i habe but no diffrence im kernel size

**Comment by jerpelea** [comment]
this commit is not having any benefits

**Comment by scafroglia93** [comment]
Just only for info

schermata del 2017-01-15 19-11-39

**Comment by kholk** [comment]
This has no benefits in our specific case.

Moreover, forcing GCC flags in makefiles is the WORST HACK EVER and should be avoided at every cost.

**Pull request closed without merging**
