### PR TITLE
[LA.UM.5.5.r1] defconfig: add kanuti defconfig

### PR DESCRIPTION
**Pull request by pablomh**
Initial defconfig for Xperia M4 Aqua (tulip)

### CODE REVIEW

**Comment by jerpelea** [comment]
there is no suport for this device... yet

**Comment by pablomh** [comment]
I unfortunately know it :(

**Comment by pablomh** [comment]
Is your plan only to add defconfigs for working platforms? I wanted to add it to ease working on it, but I agree with your approach as well and will continue working with forks.

**Comment by erikcas** [comment]
@pablomh the best route imo is to fix tulip in 1.3.3 and with that help @jerpelea and @kholk do the 3.18 magic.

question: do you have recovery fully booting? For example, I have a functining twrp here

**Comment by kholk** [comment]
I have android booting fine and working nice on Tulip 3.18.
I also have the config, so don't care about posting one, I have tested things to push, but that will happen only when ready. 

We are implementing one platform at a time to ensure a hopefully bugless experience as soon as possible. 

Care to fix the remaining bugs on 1.3.3 branch, as this is what I am using to port SoC and Sony boards on the new kernel. If 1.3.3 has a bug on a phone, probably 3.18 will have the same!

**Pull request closed without merging**
