### PR TITLE
misc: Fix Kconfig warnings

### PR DESCRIPTION
**Pull request by scafroglia93**
Fix warning on kitakami compile

### CODE REVIEW

**Comment by scafroglia93** [comment]
@rcstar6696 If you own a arm64 would you be kind to try it. If you have problems you compile the whole thing just to show me which device you own. I only Z3 and to avoid problems with 64bit I need to test on other devices

**Comment by scafroglia93** [comment]
@kholk 
Fix this warn on arm64

schermata del 2017-01-07 15-06-48

**Comment by kholk** [comment]
Why did you remove armbw hwmon?

**Comment by scafroglia93** [comment]
https://github.com/scafroglia93/kernel/commit/34b5c5d136d6d1fa703d4c34f73c3d6e11987e4e

aesthetic commit maded by Kondik

edit: I use this on multiple device for clean this warn

**Comment by alviteri** [comment]
https://github.com/sonyxperiadev/kernel/pull/1180

**Pull request closed without merging**
