### PR TITLE
msm: vidc: Addition of enums for HLG and HDR10

### PR DESCRIPTION
**Pull request by alviteri**
Add HLG and ST2084 Transfer characteristics enum values as
specified in the latest HEVC spec.

CRs-Fixed: 2062828
Bug:76227412
Change-Id: Ife5618da82b9c9ce2c395bf58998847b02522a9c
Signed-off-by: Santhosh Behara <santhoshbehara@codeaurora.org>

### CODE REVIEW

**Comment by alviteri** [comment]
this one is needed by android pie https://android.googlesource.com/platform/hardware/qcom/media/+/a9e43634b124bf8aa45668b537aea2ba1f0392c4%5E%21/#F0

**Comment by kholk** [comment]
Please port it to 2.3.2.r1.4 vidc_3x

**Comment by jerpelea** [comment]
Please port it to 2.3.2.r1.4 vidc_3x

**Comment by alviteri** [comment]
alin it is already in 4.9

**Comment by jerpelea** [comment]
ok

**Pull request merged**
