### PR TITLE
[2.3.2.r1.4] Introduce v4.19 kernel-backports and FMAC BCM43596 implementation

### PR DESCRIPTION
**Pull request by kholk**
This patchset introduces the autogenerated kernel backports from release v4.19-rc4.
The autogen has been cleaned up and sanitized.

Also, this introduces support in the BRCMFMAC driver for the Broadcom BCM4359 Revision 9 and BCM43596, found in SoMC Tone.

This PR does NOT include the Tone platform switch to the FMAC driver.

P.S.: These commits have been tested on a local tree, showing SoMC Tone Keyaki with working wifi on backports+fmac+patches.

### CODE REVIEW

**Comment by kholk** [comment]
NOTE: Don't merge yet. @oshmoun experienced issues building the kernel with the Android build system. We need to make sure that it's not related to this PR.

**Comment by oshmoun** [comment]
no defconfig changes required to trigger the issue

**Comment by kholk** [comment]
The Android build system deadlocks when trying to manage paths like "a/b//c/d".
It just doesn't like "//"... and that was the reason why it didn't work.

Fix pushed and personally verified (Android P build).
Waiting @oshmoun for further confirmation.

**Comment by oshmoun** [comment]
building in an android build environment works now

**Pull request merged**
