### PR TITLE
[7.1.r1] Linux 4.14.197

### PR DESCRIPTION
**Pull request by stefanhh0**
Following files required manual conflict resolutions resp. investigations:
- `drivers/gpu/drm/msm/msm_drv.c`: The commit https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-4.14.y&id=3d516e369e3a563e7da39c72b06d78c7f1b09b1e was not applied since the commit with ID 5d17c1a54fe5e6989015d34ed851d6f4dd02e411 from CAF already provides the function #msm_pdev_shutdown with a different implementation. Switching to the kernel upstream implementation may break things, thus I favoured keeping the CAF implementation as is.

Please review and test.

The kernel already runs fine on Yoshino/Lilac.

### CODE REVIEW

**Comment by stefanhh0** [comment]
I think there is something wrong with 4.14.197 don't merge, needs further investigation.

**Comment by jerpelea** [comment]
@stefanhh0 updates?

**Comment by stefanhh0** [comment]
@jerpelea no updates, since my sony phone is broken, I can't test any more and another one has to take over.

**Comment by jerpelea** [comment]
@stefanhh0  please email me

**Comment by jerpelea** [comment]
@stefanhh0 updates?

**Comment by stefanhh0** [comment]
I have tested it again on lilac, a vanilla build it is now booting fine. Not so sure why I saw the problems, maybe related to: PR #2330, which I haven't included this time or something different that has been merged back meanwhile.

**Comment by stefanhh0** [comment]
Tested successfully on bahamut

**Pull request merged**
