### PR TITLE
[7.1.r1] linux: 4.14.314

### PR DESCRIPTION
**Pull request by voidanix**
Tested on kumano.

### CODE REVIEW

**Comment by roberto-sartori-gl** [comment]
(Working fine on my msm8998 device)

**Comment by rhjdvsgsgks** [comment]
tested on maple. didn't get any issus so far

**Comment by rhjdvsgsgks** [comment]
seems like rndis (usb tethering) is broken on my side in this version. could you please test it?

**Comment by voidanix** [comment]
Can you confirm that RNDIS/USB tethering is not broken on previous versions?

EDIT: will test on 4.14.314 tomorrow, but 4.14.304 seems to work great.

**Comment by roberto-sartori-gl** [comment]
(USB tethering works for me on 4.14.314 but as usual, not maple, not a Sony device)

**Comment by rhjdvsgsgks** [comment]
> Can you confirm that RNDIS/USB tethering is not broken on previous versions?
> 
> EDIT: will test on 4.14.314 tomorrow, but 4.14.304 seems to work great.

4.14.314 only. 304 works fine. the behavior is link (on gadget side) unable to up and cant get ip address on host side

**Comment by voidanix** [comment]
Seems to work fine for me on kumano with 4.14.314... Could you bisect this?

**Comment by rhjdvsgsgks** [comment]
> Seems to work fine for me on kumano with 4.14.314... Could you bisect this?

ofc. but please give me some day. i dont have access to any computer (with usb port) at now

**Comment by rhjdvsgsgks** [comment]
ok. i just found that it caused by 87109978ee5cccfacc2d3ffe84b527959bf7b416 . what is it used for?

**Comment by voidanix** [comment]
lolwut. Are you sure you are looking at the correct commit?

The commit message is fairly clear: coresight will continue to trace once the kernel panics.

FYI, coresight is offered by ARM as an infrastructure for tracing and debugging ARM SoCs, which would make its relation to USB tethering genuinely curious (heck, it wasn't even in our defconfigs).

**Comment by rhjdvsgsgks** [comment]
i tried revert that commit on top of 4.14.314. rndis still not working. so seems like there is something wrong with my biselect. i will clean build and tried it again

**Comment by roberto-sartori-gl** [comment]
@rhjdvsgsgks any news?
I think this is blocking the pull request, and we (me and @voidanix ) cannot replicate the issue at the moment :)

**Comment by roberto-sartori-gl** [comment]
@rhjdvsgsgks any news?

**Comment by roberto-sartori-gl** [comment]
@voidanix We cannot replicate the issue and some months have passed without more feedback, so if this is blocking further pull requests, maybe it makes sense to (ask to) proceed with the merge. What do you think?

**Comment by rhjdvsgsgks** [comment]
sorry guys. during some season i dont have access to my computer and missed some mail. here is what i found:
the working tethering version will have log
```
id0:ipa_usb_notify_cb: Set net_ready_trigger
RNDIS_IPA NetDev was opened
```
and the not working one dont. i also discovered tethering apex will load latter than usual on the version dont have working rndis. not sure is that the reason. maybe it is a userspace issue

**Comment by rhjdvsgsgks** [comment]
i tried revert the commit i pointed, based on version 4.14.314. but it still not working. now im bisecting with the revert patch. hopefully can get some result

**Comment by roberto-sartori-gl** [comment]
@rhjdvsgsgks I just tested that on my device and I have that line:
```
cheeseburger:/ # dmesg -w | grep  ipa_usb_notify_cb
[   32.619251] id0:ipa_usb_notify_cb: Set net_ready_trigger

cheeseburger:/ # uname -r
4.14.314-g1dd4173fa163
```

Not sure where the issue may be in your case, sorry that I can't be more helpful!

**Comment by bartcubbins** [comment]
do we have a ticket on the bug tracker for this? if not, please add it and I'll take a look when I have a chance

**Comment by roberto-sartori-gl** [comment]
@voidanix sorry if I ask you, and I'm not sure if this is the right place, but I'd like to know if you plan to upgrade the kernel again on this repo.
I'd like to follow upstream if possible, otherwise I'll manage it myself.

Thanks!

**Pull request merged**
