### PR TITLE
[1.3.3] prima

### PR DESCRIPTION
**Pull request by bartcubbins**
successfully tested on tulip

### CODE REVIEW

**Comment by jerpelea** [comment]
i would say that this is cleaner ;)
diff --git a/drivers/staging/prima/Kbuild b/drivers/staging/prima/Kbuild
index cebcbea..f3814ea 100644
--- a/drivers/staging/prima/Kbuild
+++ b/drivers/staging/prima/Kbuild
@@ -547,7 +547,6 @@ CDEFINES := -DANI_BUS_TYPE_PLATFORM=1 \
                -DWLAN_FEATURE_GTK_OFFLOAD \
                -DWLAN_WAKEUP_EVENTS \
                -DWLAN_KD_READY_NOTIFIER \
-               -DWLAN_NL80211_TESTMODE \
                -DFEATURE_WLAN_BATCH_SCAN \
                -DFEATURE_WLAN_LPHB \
                 -DFEATURE_WLAN_PAL_TIMER_DISABLE \
diff --git a/drivers/staging/prima/Makefile b/drivers/staging/prima/Makefile
index 68cb92a..6812f59 100644
--- a/drivers/staging/prima/Makefile
+++ b/drivers/staging/prima/Makefile
@@ -502,7 +502,6 @@ CDEFINES := -DANI_BUS_TYPE_PLATFORM=1 \
                -DWLAN_FEATURE_GTK_OFFLOAD \
                -DWLAN_WAKEUP_EVENTS \
                -DWLAN_KD_READY_NOTIFIER \
-               -DWLAN_NL80211_TESTMODE \
                -DFEATURE_WLAN_BATCH_SCAN \
                -DFEATURE_WLAN_LPHB \
                 -DFEATURE_WLAN_PAL_TIMER_DISABLE \

**Comment by jerpelea** [comment]
if you remove WLAN_NL80211_TESTMODE from the Kbuild and Makefile it will be even better :)

**Comment by bartcubbins** [comment]
one min:)

**Comment by jerpelea** [comment]
now replace WLAN_NL80211_TESTMODE everywhere like you did before and your patch is done

**Pull request merged**
