### PR TITLE
[7.1.r1] Fix audio, WLED, Venus, LMH on SoMC Yoshino

### PR DESCRIPTION
**Pull request by kholk**
This patchset fixes audio, wled, venus and limits-lmh on the SoMC MSM89998 Yoshino platform.

Other patches enabling more functionality will come in the next days, as they
require quite a bit of testing and cleanup.
At least this will be welcomed by Yoshino Lilac users right now.

Tested on SoMC MSM8998 Yoshino Maple RoW.

### CODE REVIEW

**Comment by stefanhh0** [comment]
Kernel compilation shows several warnings

[build_log_lilac.log](https://github.com/sonyxperiadev/kernel/files/4584839/build_log_lilac.log)

Specifically for yoshino:
```
  DTC     arch/arm64/boot/dts/qcom/msm8998-v2-yoshino-lilac-sde_generic.dtb
In file included from /home/stefan/android/source/kernel/sony/msm-4.14/kernel/arch/arm64/boot/dts/qcom/msm8998-v2-yoshino-lilac-sde_generic.dts:27:
/home/stefan/android/source/kernel/sony/msm-4.14/kernel/arch/arm64/boot/dts/qcom/msm8998-yoshino-common.dtsi:1242:1: warning: '/*' within block comment [-Wcomment]
/* Follow QTI */
^
1 warning generated.
  CC      net/ipv6/protocol.o
  CC      drivers/gpu/drm/msm/sde/sde_hw_dspp.o
  CC      net/netfilter/nf_log.o
  DTC     arch/arm64/boot/dts/qcom/msm8998-v2.1-yoshino-lilac-sde_generic.dtb
  CC      drivers/gpu/drm/msm/sde/sde_hw_intf.o
In file included from /home/stefan/android/source/kernel/sony/msm-4.14/kernel/arch/arm64/boot/dts/qcom/msm8998-v2.1-yoshino-lilac-sde_generic.dts:27:
/home/stefan/android/source/kernel/sony/msm-4.14/kernel/arch/arm64/boot/dts/qcom/msm8998-yoshino-common.dtsi:1242:1: warning: '/*' within block comment [-Wcomment]
/* Follow QTI */
^
1 warning generated.
```
Don't know if this warning is critical:
```
  LD      vmlinux.o
  MODPOST vmlinux.o
WARNING: EXPORT symbol "gsi_write_channel_scratch" [vmlinux] version generation failed, symbol will not be versioned.
  KSYM    .tmp_kallsyms1.o
  KSYM    .tmp_kallsyms2.o
```

But also other warnings, e.g.:
```
In file included from /home/stefan/android/source/kernel/sony/msm-4.14/kernel/drivers/char/adsprpc.c:48:
/home/stefan/android/source/kernel/sony/msm-4.14/kernel/drivers/char/adsprpc_shared.h:110:9: warning: 'VERIFY_IPRINTF' macro redefined [-Wmacro-redefined]
#define VERIFY_IPRINTF(args) (void)0
        ^
```
introduced by commit https://github.com/sonyxperiadev/kernel/commit/9173291478b4c6f432c36eaa68d5cff4869139a5

And several other warnings of the types:
-Wunused-variable 
-Wunused-function
-Wmacro-redefined


As well an interesting warning, since the kernel build is using clang:
```
Android GCC has been deprecated in favor of Clang, and will be removed from
Android in 2020-01 as per the deprecation plan in:
https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/master/GCC_4_9_DEPRECATION.md
```

Additionally git is called during kernel build, is that expected?
```  
CC      drivers/staging/wlan-qc/qcacld-3.0/core/hdd/src/wlan_hdd_ioctl.o
fatal: Kein Git-Repository (oder irgendein Elternverzeichnis bis zum Einhängepunkt /)
Stoppe bei Dateisystemgrenze (GIT_DISCOVERY_ACROSS_FILESYSTEM nicht gesetzt).
```

**Comment by stefanhh0** [comment]
Ideally, after all warnings have been cleaned it would be good to activate -Werror

**Comment by kholk** [comment]
Noupe, that's nothing critical.. And yes I agree that the kernel would need some cleanup. Had no time to... And I probably won't, as I'm sort of rushing to get things working right now... 

That adsprpc commit, I didn't want it to even exist in the first place but some people insisted to push it temporarily: if you want, make a pr for the revert, it's fine for me!

P.S.: Also, if you want to PR a cleanup, I'd be grateful!

**Comment by MarijnS95** [comment]
That adsprpc commit was insisted on to aid in debugging, and, well, _at least_ see errors. At that point it was unknown that normal, spammy status messages were logged as warn/err, too. A revert would be best as we don't need it anymore.

@stefanhh0 Those errors are a mess in the `Kbuild` that does not foresee the build running with a changed output directory. That's fixed here: https://github.com/MarijnS95/vendor-qcom-opensource-wlan-qcacld-3.0/commits/aosp/LA.UM.7.1.r1 as well as dropping the build timestamp to prevent rebuilding these files when literally nothing has changed.

On that note I have a [similar change](https://github.com/MarijnS95/kernel-techpack-audio/commit/96b5f861dadce5b052c00a588841c7e39e626abc) for `techpack/audio` that gets rid of (this time unreferenced) timestamps preventing recompilation as well.

There don't seem to be too many folders/subsystems rolling `-Werror`, let's not shoot ourselves in the foot too early with all the external sources that have to be pulled in. That's something we can (and should) adhere to on mainline :)

**Comment by stefanhh0** [comment]
Made a PR for reverting the adsprpc change. Regarding the other warnings, I may have a look into them, hope I find the time. I am currently pretty busy with my regular job during the day. Anyway I'd like to help there and love cleaning up things + the task is simple enough for me :-)

Never looked into `kbuild` before, I'll have a look into it as well. Thanks for the info.

**Comment by nathanchance** [comment]
> Kernel compilation shows several warnings
> 
> [build_log_lilac.log](https://github.com/sonyxperiadev/kernel/files/4584839/build_log_lilac.log)
> 
> Specifically for yoshino:
> 
> ```
>   DTC     arch/arm64/boot/dts/qcom/msm8998-v2-yoshino-lilac-sde_generic.dtb
> In file included from /home/stefan/android/source/kernel/sony/msm-4.14/kernel/arch/arm64/boot/dts/qcom/msm8998-v2-yoshino-lilac-sde_generic.dts:27:
> /home/stefan/android/source/kernel/sony/msm-4.14/kernel/arch/arm64/boot/dts/qcom/msm8998-yoshino-common.dtsi:1242:1: warning: '/*' within block comment [-Wcomment]
> /* Follow QTI */
> ^
> 1 warning generated.
>   CC      net/ipv6/protocol.o
>   CC      drivers/gpu/drm/msm/sde/sde_hw_dspp.o
>   CC      net/netfilter/nf_log.o
>   DTC     arch/arm64/boot/dts/qcom/msm8998-v2.1-yoshino-lilac-sde_generic.dtb
>   CC      drivers/gpu/drm/msm/sde/sde_hw_intf.o
> In file included from /home/stefan/android/source/kernel/sony/msm-4.14/kernel/arch/arm64/boot/dts/qcom/msm8998-v2.1-yoshino-lilac-sde_generic.dts:27:
> /home/stefan/android/source/kernel/sony/msm-4.14/kernel/arch/arm64/boot/dts/qcom/msm8998-yoshino-common.dtsi:1242:1: warning: '/*' within block comment [-Wcomment]
> /* Follow QTI */
> ^
> 1 warning generated.
> ```

Looks like this never got merged: https://github.com/nathanchance/kernel/commit/56335e2fbd65b55c43e32f8d82a40495e27d66fa

> Don't know if this warning is critical:
> 
> ```
>   LD      vmlinux.o
>   MODPOST vmlinux.o
> WARNING: EXPORT symbol "gsi_write_channel_scratch" [vmlinux] version generation failed, symbol will not be versioned.
>   KSYM    .tmp_kallsyms1.o
>   KSYM    .tmp_kallsyms2.o
> ```

https://android.googlesource.com/kernel/msm/+/54ace836af62b9fc1edff9c3a436064e177fe2e4

> But also other warnings, e.g.:
> 
> ```
> In file included from /home/stefan/android/source/kernel/sony/msm-4.14/kernel/drivers/char/adsprpc.c:48:
> /home/stefan/android/source/kernel/sony/msm-4.14/kernel/drivers/char/adsprpc_shared.h:110:9: warning: 'VERIFY_IPRINTF' macro redefined [-Wmacro-redefined]
> #define VERIFY_IPRINTF(args) (void)0
>         ^
> ```
> 
> introduced by commit [9173291](https://github.com/sonyxperiadev/kernel/commit/9173291478b4c6f432c36eaa68d5cff4869139a5)
> 
> And several other warnings of the types:
> -Wunused-variable
> -Wunused-function
> -Wmacro-redefined
> 
> As well an interesting warning, since the kernel build is using clang:
> 
> ```
> Android GCC has been deprecated in favor of Clang, and will be removed from
> Android in 2020-01 as per the deprecation plan in:
> https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/master/GCC_4_9_DEPRECATION.md
> ```

Somewhere could be hardcoding a call to `$(CROSS_COMPILE)gcc` instead of `$(CC)`.

> Additionally git is called during kernel build, is that expected?
> 
> ```
> CC      drivers/staging/wlan-qc/qcacld-3.0/core/hdd/src/wlan_hdd_ioctl.o
> fatal: Kein Git-Repository (oder irgendein Elternverzeichnis bis zum Einhängepunkt /)
> Stoppe bei Dateisystemgrenze (GIT_DISCOVERY_ACROSS_FILESYSTEM nicht gesetzt).
> ```

**Comment by stefanhh0** [comment]
> > Don't know if this warning is critical:
> > ```
> >   LD      vmlinux.o
> >   MODPOST vmlinux.o
> > WARNING: EXPORT symbol "gsi_write_channel_scratch" [vmlinux] version generation failed, symbol will not be versioned.
> >   KSYM    .tmp_kallsyms1.o
> >   KSYM    .tmp_kallsyms2.o
> > ```
> 
> https://android.googlesource.com/kernel/msm/+/54ace836af62b9fc1edff9c3a436064e177fe2e4

Thanks for that info, gong to prepare a separate PR for it.

> Somewhere could be hardcoding a call to $(CROSS_COMPILE)gcc instead of $(CC).

Will check that one as well - soon.

**Comment by MarijnS95** [comment]
Gcc is still explicitly used to compile the 32-bit VDSO:
https://github.com/sonyxperiadev/kernel-sony-msm-4.14-common/commit/9fb9489ab281302842bf4c731c318797cfffb049

Also @stefanhh0 no need to dive into Kbuild (for wlan nor techpack audio), the fixes are already there and linked - I just need to create a PR for them.

**Comment by nathanchance** [comment]
> Gcc is still explicitly used to compile the 32-bit VDSO:
> [sonyxperiadev/kernel-sony-msm-4.14-common@9fb9489](https://github.com/sonyxperiadev/kernel-sony-msm-4.14-common/commit/9fb9489ab281302842bf4c731c318797cfffb049)

You should still be using clang for that: https://github.com/sonyxperiadev/kernel/blob/aosp/LA.UM.7.1.r1/arch/arm64/kernel/vdso32/Makefile#L8

That is just to get the right binutils for assembling/linking and target for clang.

**Comment by MarijnS95** [comment]
`s/compile/build`. ~Just pointing out that Stefan _likely_ does not need to go look for `$(CROSS_COMPILE)gcc`.~

~Any recommended toolchain to use that comes with android, provides the right binutils and does not have a deprecation warning?~

~Edit: There's `prebuilts/sdk/tools/linux/bin/{arm-linux-androideabi-,aarch64-linux-android-}` which I _assume_ is what's recommended now (with `prebuilt/gcc` disappearing), but it lacks tools like `nm` [and `elfedit`](https://lkml.org/lkml/2019/2/11/1946), actively used by the build process.~

~Besides, it is not only the vDSO but seemingly the normal build steps too, that use gcc binutils (as exported paths in the build scripts seem to make you believe, eg. `CROSS_COMPILE=aarch64-linux-android-`).~

It looks like you're right. `$(CROSS_COMPILE)gcc` appears in the camera_v2 driver to extract `GCC_VERSION      := $(shell $(CONFIG_SHELL) $(srctree)/scripts/gcc-version.sh $(CROSS_COMPILE)gcc)`, those seem to be the only remaining occurrences. Deleting those results in a clean build with no deprecation warnings anymore.  Which means AOSP is fine using gcc binutils, except gcc itself: I was not aware of that fact (and is obvious from R, where only `gcc` disappeared).

**Pull request merged**
