### PR TITLE
Security and other bug fixes from Google's android-3.10 reference kernel

### PR DESCRIPTION
**Pull request by stellirin**
This brings our kernel up-to-date with all bug and security fixes that Google has pushed to their reference android-3.10 kernel branch.

Tested on:
### loire
- [ ] suzu
### kitakmi
- [ ] satsuki
- [ ] satsuki_dsds
- [ ] sumire
- [ ] sumire_dsds
- [x] suzuran
- [x] ivy
- [ ] ivy_dsds
- [ ] karin
- [x] karin_windy
### kanuti
- [ ] tulip
### shinano
- [ ] leo
- [ ] aries
- [x] sirius
- [x] scorpion
- [ ] scorpion_windy
- [ ] castor
- [x] castor_windy
### rhine
- [x] honami
- [ ] amami
- [ ] togari

### CODE REVIEW

**Comment by oshmoun** [comment]
works on suzuran :+1:

**Comment by alviteri** [comment]
honami ok

**Comment by rcstar6696** [comment]
sirius an castor_windy are okay

**Comment by koron393** [comment]
scorpion works.

**Pull request merged**
