### PR TITLE
[1.3.3] ALSA

### PR DESCRIPTION
**Pull request by scafroglia93**
-No broken compile on arm / arm64
- Tested on Z3 wait for revision on arm64 device

### CODE REVIEW

**Comment by kholk** [comment]
I'm in doubt with that hrtimer commit. The others look like a good opportunity to sanify the API. 

Please remove the hrtimer commit and pr it separately.

**Comment by scafroglia93** [comment]
No push force to remove hrtimer ?

**Comment by kholk** [comment]
Yes, forcepush and send another pr containing only the hrtimer commit. That one needs further investigation (comes from upstream kernel).

**Comment by scafroglia93** [comment]
Done, I'll touch on hangotus for a commit

**Comment by kholk** [comment]
Merge

**Pull request merged**
