### PR TITLE
ARM: dts: msm: Add bus vectors in cpp node

### PR DESCRIPTION
**Pull request by alviteri**
Add bus vector in cpp node for independent
AB/IB voting. Previously this was being done
via isp.

Change-Id: I3804a72d705295645ef5321d995a8dcab6e395a9
Signed-off-by: Krupal Divvela <kdivvela@codeaurora.org>
Signed-off-by: Neelam Abhinav Karthik <aneelam@codeaurora.org>

### CODE REVIEW

**Comment by kholk** [comment]
As much clever as it sounds, the first commit is, in reality, a really stupid idea.
We can get as many bad things as you can imagine, with the most obvious being a clock mess in init path (example: you init CSI0, then init CSI1 while closing CSI0) with not just "possible" but LIKELY race conditions, producing eventually hardware faults or battery WASTE.

The second commit (bus vectors for CPP) will conflict with my other PR, but it's better than my interpretation of it, so.... remove the csiphy clocks commit and let's merge the bus vectors commit ONLY.

**Comment by alviteri** [comment]
I can see csi1phy_clk rate before setting its rate. Set the rate first!

**Comment by kholk** [comment]
Reopen the PR with the other commit only, I need to verify some things in drivers

**Comment by alviteri** [comment]
updated

**Pull request merged**
