### PR TITLE
[2.3.2.r1.4] Backport stability fixes

### PR DESCRIPTION
**Pull request by vknecht**
This is a collection of cherry-picked fixes from k4.14 branch.
Mainly tested on Loire, doesn't seem to introduce unwanted effects and reduce random reboot occurences (see [XDA thread](https://forum.xda-developers.com/xperia-x/development/rom-aosp9-20191117-builds-t4004959)).

### CODE REVIEW

**Comment by kholk** [comment]
I've read something in the thread...
I told to the guys to backport the clk commits that I produced for 4.14, but they eventually forgot to. 

Anyway, the gcc-msm8976 commit and the cpu/hotplug one are the ones that are alleviating and solving some of the issues that your users were experiencing.

The other commits are sort of useless on this kernel, so please create two PRs: one with the clk commits and the hotplug one and another pr with the rest, so that the first one can be timely merged in.

**Comment by vknecht** [comment]
Thank you, second PR will take more time...
Please let me know if any other 4.14 fix is worth considering for backport.
Happy new year :-)

**Comment by stefanhh0** [comment]
@vknecht This PR can be closed then? Got a compile error that has been fixed in #2155.

**Comment by vknecht** [comment]
Le Mercredi 8 janvier 2020, stefanhh0 a écrit :
> @vknecht This PR can be closed then? Got a compile error that has been fixed in #2155.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/sonyxperiadev/kernel/pull/2149#issuecomment-57192380

Indeed it can be closed.
Thanks !

**Comment by jerpelea** [comment]
please test it and report !

**Comment by stefanhh0** [comment]
Just flashed it and testing it on yoshino/lilac. I will report back tomorrow.

**Comment by stefanhh0** [comment]
Test-Result on yoshino/lilac:
So far everything is stable and works nicely I haven't found any new issues that have been introduced by this change. Audio, Taking photos, runtime stability and so on works as before. No crashes and no unexpected reboots occurred.

**Pull request merged**
