### PR TITLE
[LA.UM.5.7.r1] Update tone config

### PR DESCRIPTION
**Pull request by humberos**
ping @oshmoun @alviteri

### CODE REVIEW

**Comment by oshmoun** [comment]
did you notice any differences with ALLOC_BUFFERS_IN_4K_CHUNKS? tested that before but saw no changes.
About USB_DWC3_MSM_ID_POLL and Enable DUAL_ROLE_USB_INTF, would those affect charging?

**Comment by kholk** [comment]
The ID polling should be deprecated.
The PMIC found in msm8996 and the other one in msm8998 supports over current protection (OCP) and short circuit protection (SCP, referenced in code as SC) so, even in the event of water contamination of the usb port while in host mode, the PMIC will be self protected.

About the dual role, that shouldn't be touching any of the code that we are currently executing.

The 4K bugger chunks then is a debugging feature and it's not intended for production use.

**Comment by kholk** [comment]
Whoops.
*buffer

Cannot edit from phone!

**Comment by oshmoun** [comment]
ID polling is enabled for yoshino though
https://github.com/sonyxperiadev/kernel/blob/aosp/LA.UM.5.7.r1/arch/arm64/configs/aosp_yoshino_maple_defconfig#L445

**Comment by kholk** [comment]
Yeah, it's a fancy way to recognize other proprietary (and non-proprietary) accessories, other than a paranoid third protection to avoid to even trigger host mode when not necessary.

**Comment by humberos** [comment]
Thanks for the explanation

**Pull request closed without merging**
