### PR TITLE
[Staging] LA.UM.6.4.r1-06900-8x98.0

### PR DESCRIPTION
**Pull request by humberos**
New CAF's tag

### CODE REVIEW

**Comment by oshmoun** [comment]
boots on both kugo and keyaki
no regressions discovered so far

**Comment by kholk** [comment]
Obi, try to make a phone call. The SSC VMID change looks suspicious.

**Comment by oshmoun** [comment]
good catch, especially for loire!
tested on kugo and keyaki (earpiece, speaker, bt), and all works fine.

**Comment by kholk** [comment]
Then I'm 99% sure that the weektest will succeed :)))

**Comment by humberos** [comment]
No issues here (kagura and suzu).
Not sure about yoshino.
Could someone report it ?

**Pull request merged**
