### PR TITLE
[2.3.2.r1.4] Linux 4.9.221

### PR DESCRIPTION
**Pull request by stefanhh0**
Following files required manual merge conflict resolutions:
- `drivers/usb/gadget/function/f_fs.c` -> Easy: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-4.9.y&id=d51a00dbcf4c0997ee259718d94d887983846a51
- `mm/vmalloc.c` -> Easy to resolve the rejection for the include, see https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-4.9.y&id=f8e84d7a9417e84aad03b98dbbb0ef44f2adcf3b

Please review.

The kernel already runs fine on Yoshino/Lilac.

### CODE REVIEW

**Comment by kholk** [comment]
At least for the vmalloc one, my brain's kernel-explosion detector is not ringing... So this should indeed work fine.

Though, please test this on Loire and Tone before merging!

**Comment by chris42** [comment]
Just tested this on Kugo and seems to work; boots normal, nothing special to see in the logs. Phone, audio, wifi, bluetooth are working.

**Comment by stefanhh0** [comment]
@ix5 If you would find the time to test it on your Tone would be great, not urgent anyway :-)

**Comment by stefanhh0** [comment]
@kholk @jerpelea can this be merged? Tone testing is still missing, however it proved to run stable on Yoshino/Lilac and Loire/Kugo, not sure if someone will have time to test it specifically for tone...

**Comment by ix5** [comment]
Just for posterity, have been running this on kagura for a while now and cursory testing revealed no regressions.

**Pull request merged**
