### PR TITLE
dtsi: leo: fix typos

### PR DESCRIPTION
**Pull request by alviteri**
Signed-off-by: David Viteri davidteri91@gmail.com

### CODE REVIEW

**Comment by alviteri** [comment]
confused ... in stock is change anyway thanks

**Comment by Kali-** [comment]
kholk, sony fixed it in 23.1 
so it's a typo, but need to be fixed in display and on scorpion dtsi too

**Comment by kholk** [comment]
I was meaning that, despite being a typo, it's working as it is global.

**Comment by jerpelea** [comment]
Fix it!

**Pull request closed without merging**
