### PR TITLE
[LA.UM.5.5.r1] loire: welcome pstore

### PR DESCRIPTION
**Pull request by humberos**

### CODE REVIEW

**Comment by AdrianDC** [comment]
If you want to update pstore this way, you might want to revert https://github.com/humberos/kernel/commit/0622bea233d828fd6258c5654ff341a3ff1f53da first to avoid the conflicts of the commit you did override.

Welcome > PSTORE was already working actually.

**Comment by humberos** [comment]
oh! pstore is not working for loire
please, could you test if this way works for tone ?

**Comment by AdrianDC** [comment]
Can't today but will try tomorrow.

Loire has the DT config already I guess.

Try to look at the commit & see if reverting avoids the conflicts resolving on the moto's commit,
I know I was going that way first to restore PSTORE but then came back to Sony's copyleft changes.

**Comment by humberos** [comment]
Oh, I see!
I will upload the revert that you have mentioned. Thank you for point it out.
With those changes we have pstore working back for loire platform.

**Comment by jerpelea** [comment]
working fine on tone

**Pull request merged**
