### PR TITLE
Bluetooth

### PR DESCRIPTION
**Pull request by humberos**

### CODE REVIEW

**Comment by humberos** [comment]
The reasons of those patches are:
1. bluesleep wakelocks (shinano) 
2. bluetooth driver for Kitakami (broken at moment).

@kholk
We need your help here for Kitakami devices.
Even using those changes (including ramdisk one) bluetooth doesn't works.

@alviteri, @Entropy512
Please could you check if it is ok for shinano leo?

Thank you.

**Comment by kholk** [comment]
Sir, yes, sir!
Kitakami BT needs more than what you posted, I know ;)

I'm a bit busy, can't promise you that I will do the magic tomorrow, but I will try to!

**Comment by humberos** [comment]
@kholk 
Thank you!
Sorry for boring you.
I can help here but I'll need some directions from masters.

**Comment by kholk** [comment]
No worries! I'm here to help, as always :)

**Comment by alviteri** [comment]
All seems ok on leo with this

**Comment by kholk** [comment]
for a start, merge this pr.... :)

**Comment by Entropy512** [comment]
Hmm, as far as the bluesleep wakelocks - Humberto, where'd you come up with this approach vs. using the one that the Nexus devices use (PROC_BTWRITE_TIMER_TIMEOUT_MS = 4000) - I could've sworn this was already merged but it turns out it's just sitting locally on my drive even though I know we talked about that patch 2-3 months ago.

Edit:  The CAF patch says it's "temporary" - this worries me

**Comment by humberos** [comment]
Yeah Andrew, I think is time to follow AOSP in this case and leave workarounds. I will upload this change to devices ASAP.
And yes, We talked about it some time ago! :)
Thanks for remind me.

**Comment by mmaret-geny** [comment]
bluetooth for kitakami should be fixed by this PR : https://github.com/sonyxperiadev/device-sony-kitakami/pull/117

**Pull request merged**
