### PR TITLE
[1.3.3] tulip: nfc

### PR DESCRIPTION
**Pull request by bartcubbins**
welcome nfc on tulip

[   24.002959] Loading pn547 driver
[   24.006786] pn547_probe : pinctrl is defined
[   24.010515] pn547_parse_dt: irq : 923, ven : 922, firm : 924, pvdd_en : -2
[   24.017311] pn547_probe : IRQ num 390
[   24.021016] pn547_probe : requesting IRQ 390
[   24.036536] i2c-msm-v2 78ba000.i2c: msm_bus_scale_register_client(mstr-id:86):0x6 (ok)
[   24.043916] pn547_probe : i2c addr=0x28
[   24.047223] pn547_probe : success

### CODE REVIEW

**Comment by pablomh** [comment]
I'm going to test a build with these commits in a moment.

**Comment by bartcubbins** [comment]
@pablomh nfc is not working with libnfc-nxp.conf from sony repo

**Comment by pablomh** [comment]
My test will be with this: https://github.com/pablomh/device_sony_tulip/commits/android-7.0_tulip-nfc

**Comment by bartcubbins** [comment]
@pablomh I used another libnfc

**Comment by jerpelea** [comment]
please updaye the config file

**Comment by bartcubbins** [comment]
@jerpelea ok

**Pull request merged**
