### PR TITLE
LA.UM.6.4.r1: input: ts: synaptics_dsx_td4322: allow downgrading the panel firmware.

### PR DESCRIPTION
**Pull request by krnlyng**

### CODE REVIEW

**Comment by luk1337** [comment]
Wouldn't it be better to just allow downgrading FW @ https://github.com/sonyxperiadev/kernel/blob/6a09aafa51b1910ae2441c44cfde53b1bce83098/drivers/input/touchscreen/synaptics_dsx_td4322/synaptics_dsx_fw_update.c#L2485 and probably https://github.com/sonyxperiadev/kernel/blob/6a09aafa51b1910ae2441c44cfde53b1bce83098/drivers/input/touchscreen/synaptics_dsx_td4322/synaptics_dsx_fw_update.c#L2508 (idk if that part is necessary tho)

**Comment by bartcubbins** [comment]
don't forget, that you need CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_TD_FW_UPDATE=y

**Comment by luk1337** [comment]
it's already enabled.

**Comment by bartcubbins** [comment]
are you sure?

**Comment by luk1337** [comment]
Yes. https://github.com/sonyxperiadev/kernel/blob/04bf6fcb8ad4cec1cab675c5826e8e184e952652/drivers/input/touchscreen/synaptics_dsx_td4322/Kconfig#L51-L60 × https://github.com/sonyxperiadev/kernel/blob/04bf6fcb8ad4cec1cab675c5826e8e184e952652/arch/arm64/configs/aosp_nile_pioneer_defconfig#L365

**Comment by bartcubbins** [comment]
I don't see default y

**Comment by luk1337** [comment]
that's why i also linked defconfig.

**Comment by bartcubbins** [comment]
maybe I'm blind... xD
https://github.com/sonyxperiadev/kernel/blob/aosp/LE.UM.2.3.2.r1.4/arch/arm64/configs/aosp_nile_discovery_defconfig#L368-L370
https://github.com/sonyxperiadev/kernel/blob/aosp/LE.UM.2.3.2.r1.4/arch/arm64/configs/aosp_nile_pioneer_defconfig#L368-L370

**Comment by luk1337** [comment]
image
!=
image

**Comment by bartcubbins** [comment]
I'm definitely blind

**Comment by kholk** [comment]
Please fix your commit title and add a commit description.
The commit title should be in the following format:
`input: ts: synaptics_dsx_td4322: commit message`

Commits without description are bad, as noone knows what are you
trying to do or for which specific reason.

Also, instead of just silently doing the downgrade, please add a print
that makes the user aware of what it's being done; for example:

`Image firmware ID older than device firmware ID. Forcing downgrade.`

`Update reason: configuration ID forced downgrade`

**Comment by pablomh** [comment]
Hi @krnlyng, can you please state in the title the kernel branch? I tried to apply it to 4.9 ([2.3.2.r1.4]) and it failed miserably (expectedly once I saw that it was intended for 4.4).

**Pull request merged**
