### PR TITLE
[2.3.2.r1.4]tone: dts: convert i2c_3 gpios to pinctrl

### PR DESCRIPTION
**Pull request by erikcas**
See:
https://github.com/sonyxperiadev/kernel/pull/1667
and
https://github.com/sonyxperiadev/bug_tracker/issues/137

tested with aosp camera on kagura. Dmesg is clean now

### CODE REVIEW

**Comment by erikcas** [comment]
Earlier had some issues with on build with SnapdragonCamera. Turned out to be an issue with SnapdragonCamera issue (not working properly on suzu either) so the SnapCamera idea is dropped

**Comment by kholk** [comment]
I agree with you about the idea, that's proper configuration. Indeed.

But it wouldn't be the real world if things were THAT SIMPLE. :P
I have to request some changes.

First of all, by doing that you're generating a possible power consumption issue by leaving the not connected pins floating and open for input on Tone Dora: this phone doesn't have any of the two sensors.
Second thing, you've removed them from somc-pinctrl after changing their name/binding/function. That's also very very bad.
Put it like this: something goes bad while using camera, kernel panic happens, the device reboots and you get back into the system with the ToF/RGBC GPIOs in the previous state (HIGH) while they're expected to be LOW.
The best situation at this point would be a camera probe failure requiring a manual system reboot (or shutdown and boot).

So... Override these pins' config in dora-common to be in Hi-Z (or whatever they were, I couldn't read the entire thing since I'm on phone) and DEFINITELY readd them to somc-pinctrl!

Disclaimer: if I've missed anything it's because I'm on phone. In case, I'm preventively sorry.

**Comment by kholk** [comment]
P.S.: I've missed the worst situation. That'd be that you burn the sensors while power supplies are initializing. Cool, eh? :P

**Comment by erikcas** [comment]
oke @kholk understood your point. Should https://github.com/sonyxperiadev/kernel/commit/46688f79ff791adf9921e5c06f829e39ffe10272 be reverted then?

**Comment by erikcas** [comment]
close till properly fixed, prevent leaving a pr open that can damage phones

**Pull request closed without merging**
