### PR TITLE
TCP Improvements

### PR DESCRIPTION
**Pull request by scafroglia93**

### CODE REVIEW

**Comment by scafroglia93** [comment]
@rcstar6696

**Comment by rcstar6696** [comment]
Tested on sirius and castor windy without problems
i merged them in my kernel some time before but forgot to comment

**Comment by scafroglia93** [comment]
@kholk boss ?

**Comment by scafroglia93** [comment]
@rcstar6696 @jerpelea 

So, If all goes well I would say to do the merge

**Comment by kholk** [comment]
I agree with this pr.  Ok to merge.

**Pull request merged**
