### PR TITLE
[1.3.3] BLK Upstream

### PR DESCRIPTION
**Pull request by scafroglia93**
Wait for revision on arm64

Z3 Boot fine

### CODE REVIEW

**Comment by scafroglia93** [comment]
@rcstar6696 Have you tested this commits ? I use this set of commits for my Nexus 6P and 5X stable kernel

**Comment by mcgi5sr2** [comment]
fine on aries

**Comment by scafroglia93** [comment]
wait for revision

**Comment by kholk** [comment]
I said this a billion times now I think. Random commits from other kernel version are likely to invisibly break things (problems will show in some time). In this specific case, what can happen is some code depending on other code introduced by an apparently unrelated commit that, if not applied, can produce race conditions and data loss.

**Pull request closed without merging**
