### PR TITLE
Optimized

### PR DESCRIPTION
**Pull request by scafroglia93**

### CODE REVIEW

**Comment by scafroglia93** [comment]
Tested on Z3
screenshot_20161118-002619

**Comment by scafroglia93** [comment]
@rcstar6696

**Comment by rcstar6696** [comment]
testing now

**Comment by rcstar6696** [comment]
it seems that this  commit makes problems with backlight 
https://github.com/sonyxperiadev/kernel/pull/991/commits/54d1e1c41719ea55c52933815bb6b638397f901d

screen is extremly bright after applying this commit

**Comment by scafroglia93** [comment]
Strange, this commits is used to reduce brightness level. I have fixed with this https://github.com/CasualsKernelProject/leo/commit/715f718de4cb5cf029f064495668dff9be7fad31

**Comment by rcstar6696** [comment]
Your patch is needed on all devices

**Comment by jerpelea** [comment]
please remove https://github.com/scafroglia93/kernel/commit/54d1e1c41719ea55c52933815bb6b638397f901d

**Comment by jerpelea** [comment]
merged

**Comment by scafroglia93** [comment]
I was working...

**Comment by jerpelea** [comment]
i merged your commits and rebuilt blob kernels

**Pull request closed without merging**
