### PR TITLE
Fiops I/O Sched

### PR DESCRIPTION
**Pull request by scafroglia93**
Flash based storage has some different characteristics against rotate disk.
1. no I/O seek.
2. read and write I/O cost usually is much different.
3. Time which a request takes depends on request size.
4. High throughput and IOPS, low latency.

Source:https://lkml.org/lkml/2012/1/4/18

### CODE REVIEW

**Comment by scafroglia93** [comment]
Nexus 6P with latest Android 7.0 + Stock Kernel
img_20160911_162308

Add Random is OFF

**Comment by stellirin** [comment]
The copyright header in your patch does not state that this is compatible with this kernel's GPL licence

**Comment by kholk** [comment]
Disabling add_random cripples FS encryption performance. Moreover there is no proof that this very old io Scheduler makes any improvement.

**Comment by scafroglia93** [comment]
Now on Z3 am using ZEN V2 with no problem

**Pull request closed without merging**
