### PR TITLE
sdcardfs: fix external storage exporting incorrect uid

### PR DESCRIPTION
**Pull request by koron393**
Fix external storage write issue.

### CODE REVIEW

**Comment by alviteri** [comment]
from where did you pick this ?

**Comment by koron393** [comment]
I found it at CM review.
Scorpion is OK.

**Comment by alviteri** [comment]
is not user_id used due to multiuser ID ?

https://github.com/sonyxperiadev/kernel/blob/aosp/LA.BR.1.3.3_rb2.14/fs/sdcardfs/main.c#L270

**Comment by rcstar6696** [comment]
this commit fixes ext sdcard mount on shinano (sirius and castor)

**Pull request merged**
