### PR TITLE
[2.3.2.r1] [SPECTRA-CAM] Bring in line with LA.UM.7.3 05900

### PR DESCRIPTION
**Pull request by kholk**
Update the LE.UM.2.3.2.r1.4 camera to be in line with LA.UM.7.3-05900-sdm845.0.

Tested on SoMC Tama Akatsuki.

### CODE REVIEW

**Comment by kholk** [comment]
P.S.: Even if it is working (for some unknown reason) on my device, and actually even showing better performance, it's not working on @oshmoun 's Tama Apollo.
This probably requires blobs to be recompiled.

**Comment by kholk** [comment]
Offending commit:
6c36a40ed550e7366acfa2cc93a56c3f35eb3ddf
"
    Register Actuator with CRM as real time device.
    Correct request ID for actuator manual lens move command
    for the lens to move in sync with request ID with frame
    delay of 1.
"

Does this need support in userspace?

EDIT:
The commit has been reverted to allow this update to work with the current blobs.

**Comment by kholk** [comment]
@sraase This PR should be totally interesting to you.
Can you please validate?

Thanks!

**Comment by oshmoun** [comment]
the commit can probably be added again, no changes noticed

**Comment by kholk** [comment]
I agree, but that one makes a lot of spam in dmesg and maybe it requires some sort of userspace support.

For now let's keep it reverted, if/until Sebastian says otherwise.

**Comment by sraase** [comment]
Sorry for not replying earlier, but I was on vacation.
I'll try to take a look this week.

**Comment by kholk** [comment]
Sure, no problem :D

**Comment by sraase** [comment]
As far as I can tell, the actuator works in both cases. Keeping it reverted seems the better option for now. Maybe this will be required in the future, but I don't know. Userspace shouldn't matter in this case, since it is mostly descriptive rather than code.

**Comment by kholk** [comment]
Well, from our previous experience, we know that sometimes the smallest change in the camera drivers can break things unexpectedly... And that's why I wanted you to take a look :D

Anyway, if you approve on your side, I think that the pr can be merged at this point.

**Pull request merged**
