### PR TITLE
[6.4.r1] Update to Linux 4.4.222

### PR DESCRIPTION
**Pull request by sjllls**
I met some errors about IPv6 router when upgrade to 4.4.223, so only updated to 4.4.222.
Tested on Kagura, **this PR needs to be verified on other devices**.
Don't give up tone and loire, we are still alive on antique kernel. XD
Screenshot_20200811-141135_Settings

### CODE REVIEW

**Comment by Thaodan** [comment]
Testing that with nile-discovery it looks like everything is fine. Merge?

**Comment by Thaodan** [comment]
Ping @jerpelea

**Comment by jerpelea** [comment]
@Thaodan should be tested on all platforms

**Comment by Thaodan** [comment]
> @Thaodan should be tested on all platforms
Ah sorry that is something I can't do.

**Comment by jerpelea** [comment]
this is a legacy branch and we should not accept patches for it 
Thanks for your understanding

**Pull request closed without merging**
