### PR TITLE
[1.3.3] acdb (In call audio)

### PR DESCRIPTION
**Pull request by mcgi5sr2**
Required commits for acdb tested on Shinano with the corresponding blobs

### CODE REVIEW

**Comment by alviteri** [comment]
these were close before ... see @humberos ' PR

**Comment by alviteri** [comment]
alin want OSS way for this

**Comment by mcgi5sr2** [comment]
Ok i understand OSS may give a better result, as there is still echo on the line using this. However i would live this open until we have a better way. That allows people to have in call volume control on their own current builds.

**Comment by alviteri** [comment]
As I know this doesn't work without acdb blobs

**Comment by mcgi5sr2** [comment]
yes correct without the blobs it doesn't work

**Pull request closed without merging**
