### PR TITLE
[1.3.3][DO NOT MERGE] drivers: clearpad: Workaround for suzu touchscreen

### PR DESCRIPTION
**Pull request by humberos**
This patch forces incell hybrid panels as SP mode
during its initialization.

### CODE REVIEW

**Comment by humberos** [comment]
ping @erikcas @kholk 
I think may should I check the FULL/HYBRID panel first ?
Btw, this patch works really nice on my device (Panel 7).

**Comment by erikcas** [comment]
panel 8. Stuck at bootlogo....
Quite strange we get that different results.

I have no problem at all on the updated driver (which was reverted again)

**Comment by humberos** [comment]
Panel 7 is HYBRID and panel 8 is FULL.

**Comment by erikcas** [comment]
still stuck on bootlogo

**Pull request closed without merging**
