### PR TITLE
Updated Gov Interactive

### PR DESCRIPTION
**Pull request by scafroglia93**
Tested on my Z3 Aosp

### CODE REVIEW

**Comment by rcstar6696** [comment]
Please add the defconfig for all devices not only for one

**Comment by scafroglia93** [comment]
Ooops, can you provide me device list please ? Now i'm at work :(

**Comment by alviteri** [comment]
are you picking this from a CM kernel?

**Comment by scafroglia93** [comment]
This is the only commits cherry-picked from CM Kernel for fix performance issue inside interactive

https://github.com/scafroglia93/kernel/commit/f6efb48ec582b43804c007c69ae11baa351a2e3c

**Comment by scafroglia93** [comment]
Are you still interested ?

**Comment by rcstar6696** [comment]
i tested it on castor_windy and sirius 
it works :)

**Comment by scafroglia93** [comment]
So, it's possibile merge this commits into kernel ?

**Comment by alviteri** [comment]
ping @kholk

**Comment by scafroglia93** [comment]
Ok, wait for response

**Pull request closed without merging**
