### PR TITLE
[1.3.3] mmc: core: Avoid frequent enable/disable of Auto BKOPS

### PR DESCRIPTION
**Pull request by humberos**
Extracted from:
https://github.com/sonyxperiadev/kernel/commit/b42af0ea55492e2be89b5834d266e5fb07c982ed

Signed-off-by: Humberto Borba <humberos@gmail.com>
Change-Id: Ib963c209113b6db959c982ab811763adc0f75b84

### CODE REVIEW

**Comment by humberos** [comment]
ping @kholk

**Comment by oshmoun** [comment]
you seem to have extra commits included ;)

**Comment by humberos** [comment]
Lol
I will rebase it. 
Thanks.

**Comment by jerpelea** [comment]
cherry-picked

**Pull request closed without merging**
