### PR TITLE
Add TTL support

### PR DESCRIPTION
**Pull request by russel5**
Some internet providers check TTL value and if it's change we can't share our unlimited internet via wifi to other devices.
This commit add support to "freeze" TTL value and share internet

### CODE REVIEW

**Comment by jerpelea** [comment]
Please follow the layout!
There must be 1 separate commit for each platform for easy porting and revert

**Comment by russel5** [comment]
Sry but i dont understand what are you want

**Comment by bartcubbins** [comment]
1 commit for all loire devices
1 commit for all yoshino devices
etc

**Comment by bartcubbins** [comment]
also don't forget about commit description

**Comment by jerpelea** [comment]
here is a nice example 
https://github.com/sonyxperiadev/kernel/commits/aosp/LA.UM.6.4.r1/arch/arm64/configs

**Comment by bartcubbins** [comment]
something like this:
arm64: configs: Loire: Enable CONFIG_IP_NF_TARGET_TTL

Some internet providers check TTL value and if it's change we can't share our unlimited internet via wifi to other devices.
This commit add support to "freeze" TTL value and share internet

**Pull request closed without merging**
