### PR TITLE
Drivers

### PR DESCRIPTION
**Pull request by alviteri**
related to usb midi

### CODE REVIEW

**Comment by alviteri** [comment]
wait for this

**Comment by alviteri** [comment]
ok

**Comment by kholk** [comment]
@alviteri is it tested? (I see one more commit, compared to the previous PR)

**Comment by alviteri** [comment]
@kholk yep but need triple check on other targets specially with 64-bit I don't have one of them... also needs a PR on common

**Comment by alviteri** [comment]
@jerpelea I am closing this because midi drivers is correctly indeed on new 1.2.2 kernel now you can merge midi PR on platforms

**Pull request closed without merging**
