### PR TITLE
usb: phy-msm-usb: use internal power supply only

### PR DESCRIPTION
**Pull request by aolexiy**
Remove the global variable and use msm_otg::usb_psy instead. Stop
probe if power supply fails to register (to drop the null pointer
::usb_psy checks) and fix the error code check when registering it.

This fixes USB charging issue on loire devices.

### CODE REVIEW

**Comment by aolexiy** [comment]
@kholk could you, please, have a look at this one?

**Comment by oshmoun** [comment]
Could you please do the following?
1. Enable adb over wifi
2. Charge device with wall charger
3. Adb connect
4. Cat /sys/class/power_supply/usb/uevent

**Comment by oshmoun** [comment]
tested, can confirm that uevent reports input of 1500mAh

**Comment by kholk** [comment]
The commit looks like being correct.

Only one thing concerns me (which is the reason why I chose to write it like that) and that is possibly another driver can use one (or more) of those functions externally for some bad design from QC that hasn't been corrected yet.

Check this driver on Loire, boot with charger, with USB PC and with USB Host: if those tests will not fail, then my congratulations!

**Comment by kholk** [comment]
Verified. MERGEME!

**Comment by oshmoun** [comment]
wut?
was just about to say that I actually don't notice a change in charging current (at least according to values reported by msm_bcl device)
also, a correction to the confirmation above, input_current_max is still 500, similar to tone.
only difference with this pr is that POWER_SUPPLY_CURRENT_MAX reports 150000 on charger. On pc it still remains at 0.
P.S: have to concede though that I don't have the equipment to measure power draw from the outlet. That'd be the best way to confirm/deny an improvement.

**Comment by kholk** [comment]
I have verified that it doesn't cause any stability problem due to the removed checking logic, hence it can be merged safely (and it's a good cleanup).
Whether it solves the low charging amperage or not wasn't actually verified by me.

**Comment by jerpelea** [comment]
lets do more testing

**Comment by jerpelea** [comment]
i agrwe but lets test and merge  after

**Comment by kholk** [comment]
Well, yes, agreed.

**Comment by aolexiy** [comment]
@oshmoun it draws 0.5A max from USB, 1.5A is a limit for the regular charger. do you still need uevents log (sorry, got distracted)?

Here's [1] the some logs when connected to PC USB port (simple "USB Detector" I use shows ~4.7V, 0.48A). There "st=" == state (2 means battery is charging), "l=" == level (it slowly goes from 28% to 30%), "c=" current (negative means battery is charging).

```
[1]
$ adb logcat -b kernel | grep healthd\ :
01-03 19:52:10.211     0     0 I init    : computing context for service 'healthd'
01-03 19:52:10.211     0     0 I init    : starting service 'healthd'...
01-03 19:52:10.508     0     0 W healthd : unable to get HAL interface, using defaults
01-03 19:52:10.772     0     0 W healthd : Unknown power supply type 'BMS'
01-03 19:52:10.784     0     0 W healthd : Unknown power supply type 'BMS'
01-03 19:52:10.790     0     0 W healthd : BatteryFullChargePath not found
01-03 19:52:10.795     0     0 W healthd : BatteryCycleCountPath not found
01-03 19:52:10.800     0     0 W healthd : battery l=28 v=3746 t=26.5 h=2 st=3 c=45 chg=u
01-03 19:52:11.348     0     0 W healthd : battery l=28 v=3746 t=26.5 h=2 st=2 c=45 chg=u
01-03 19:52:11.349     0     0 W healthd : battery l=28 v=3746 t=26.5 h=2 st=2 c=45 chg=u
01-03 19:52:11.418     0     0 W healthd : battery l=28 v=3746 t=26.5 h=2 st=2 c=45 chg=u
01-03 19:52:11.419     0     0 W healthd : battery l=28 v=3746 t=26.5 h=2 st=2 c=45 chg=u
01-03 19:52:11.437     0     0 W healthd : battery l=28 v=3583 t=26.5 h=2 st=2 c=1126 chg=u
01-03 19:52:11.491     0     0 W healthd : battery l=28 v=3583 t=26.5 h=2 st=2 c=1126 chg=u
01-03 19:52:11.524     0     0 W healthd : battery l=28 v=3583 t=26.5 h=2 st=2 c=1126 chg=u
01-03 19:52:12.000     0     0 W healthd : battery l=28 v=3583 t=27.0 h=2 st=2 c=1126 chg=u
01-03 19:52:12.000     0     0 W healthd : battery l=28 v=3583 t=27.0 h=2 st=2 c=1126 chg=u
01-03 19:52:12.071     0     0 W healthd : battery l=28 v=3583 t=27.0 h=2 st=2 c=1126 chg=u
01-03 19:52:12.072     0     0 W healthd : battery l=28 v=3583 t=27.0 h=2 st=2 c=1126 chg=u
01-03 19:52:12.159     0     0 W healthd : battery l=28 v=3583 t=27.0 h=2 st=2 c=1126 chg=u
01-03 19:52:12.160     0     0 W healthd : battery l=28 v=3583 t=27.0 h=2 st=2 c=1126 chg=u
01-03 19:52:15.216     0     0 W healthd : battery l=28 v=3583 t=27.0 h=2 st=2 c=1126 chg=u
01-03 19:53:10.510     0     0 W healthd : battery l=28 v=3812 t=27.2 h=2 st=2 c=-425 chg=u
01-03 19:54:10.511     0     0 W healthd : battery l=28 v=3812 t=27.2 h=2 st=2 c=-309 chg=u
01-03 19:55:10.511     0     0 W healthd : battery l=28 v=3833 t=27.2 h=2 st=2 c=-428 chg=u
01-03 19:55:14.392     0     0 W healthd : battery l=28 v=3835 t=27.2 h=2 st=2 c=-427 chg=u
01-03 19:55:14.403     0     0 W healthd : battery l=28 v=3835 t=27.2 h=2 st=2 c=-427 chg=u
01-03 19:56:10.511     0     0 W healthd : battery l=28 v=3837 t=27.2 h=2 st=2 c=-427 chg=u
01-03 19:57:10.511     0     0 W healthd : battery l=28 v=3839 t=27.2 h=2 st=2 c=-422 chg=u
01-03 19:57:40.721     0     0 W healthd : battery l=28 v=3840 t=27.2 h=2 st=2 c=-425 chg=u
01-03 19:57:40.733     0     0 W healthd : battery l=28 v=3840 t=27.2 h=2 st=2 c=-425 chg=u
01-03 19:58:10.511     0     0 W healthd : battery l=28 v=3841 t=27.2 h=2 st=2 c=-424 chg=u
01-03 19:59:10.511     0     0 W healthd : battery l=28 v=3843 t=27.2 h=2 st=2 c=-427 chg=u
01-03 20:00:02.676     0     0 W healthd : battery l=29 v=3845 t=27.2 h=2 st=2 c=-426 chg=u
01-03 20:00:02.716     0     0 W healthd : battery l=29 v=3845 t=27.2 h=2 st=2 c=-426 chg=u
01-03 20:00:10.511     0     0 W healthd : battery l=29 v=3845 t=27.2 h=2 st=2 c=-424 chg=u
01-03 20:01:10.511     0     0 W healthd : battery l=29 v=3847 t=27.2 h=2 st=2 c=-427 chg=u
01-03 20:02:10.511     0     0 W healthd : battery l=29 v=3848 t=27.2 h=2 st=2 c=-426 chg=u
01-03 20:02:14.274     0     0 W healthd : battery l=29 v=3848 t=27.2 h=2 st=2 c=-426 chg=u
01-03 20:02:14.279     0     0 W healthd : battery l=29 v=3848 t=27.2 h=2 st=2 c=-426 chg=u
01-03 20:03:10.511     0     0 W healthd : battery l=29 v=3849 t=27.5 h=2 st=2 c=-426 chg=u
01-03 20:04:10.511     0     0 W healthd : battery l=29 v=3850 t=27.5 h=2 st=2 c=-426 chg=u
01-03 20:04:22.894     0     0 W healthd : battery l=30 v=3850 t=27.5 h=2 st=2 c=-426 chg=u

```

**Comment by oshmoun** [comment]
thanks for confirming that 0.5A is the current value! logs aren't needed anymore :)
so now the question is why the charging current 0.5A to that and doesn't scale up all the way to 1.5A, right?
Because I get 0.5A on a wall charger, whereas I get 1.5A on 3.10 kernel with the same charger.

**Comment by aolexiy** [comment]
> so now the question is why the charging current 0.5A to that and doesn't scale up all the way to 1.5A, right?

Hmm, quickly tried different chargers, it seems that with old ones it really sticks around ~0.56A / ~4.7V. Used "quick" UCH12 before and with that it charges really fast at ~1.1A / 8.5V. Will try to look a bit more with that. Ugh, at least it charges from USB port now.

**Comment by oshmoun** [comment]
Used the charger that came with the device, would that count as old?
also, a quick charger usually operates at higher current values, 1.7A or even 2A afaik. So wouldn't charging at 1.1A be considered slow as well?

**Comment by kholk** [comment]
@oshmoun  1.1A@8.5V pushes in a higher current (how can I explain the concept without writing a wall of text?) than 5V@1A.
I don't know how many amps should the UCH12 provide at that voltage, but that's already a fast charge, eh!

**Comment by Bitti09** [comment]
Stock charger (Which came with the XZ device) after this PR
```
cat /sys/class/power_supply/usb/uevent
POWER_SUPPLY_NAME=usb
POWER_SUPPLY_PRESENT=1
POWER_SUPPLY_ONLINE=1
POWER_SUPPLY_CURRENT_MAX=2000
POWER_SUPPLY_TYPE=USB
POWER_SUPPLY_HEALTH=Good
```

output of /sys/class/power_supply/battery/uevent

```POWER_SUPPLY_NAME=battery
POWER_SUPPLY_STATUS=Charging
POWER_SUPPLY_PRESENT=1
POWER_SUPPLY_BATTERY_CHARGING_ENABLED=1
POWER_SUPPLY_CHARGING_ENABLED=1
POWER_SUPPLY_CHARGE_TYPE=Fast
POWER_SUPPLY_CAPACITY=82
POWER_SUPPLY_HEALTH=Good
POWER_SUPPLY_TECHNOLOGY=Li-ion
POWER_SUPPLY_SYSTEM_TEMP_LEVEL=0
POWER_SUPPLY_FLASH_CURRENT_MAX=2834569
POWER_SUPPLY_CONSTANT_CHARGE_CURRENT_MAX=2100000
POWER_SUPPLY_VOLTAGE_MAX=4350
POWER_SUPPLY_VOLTAGE_MAX_DESIGN=4350000
POWER_SUPPLY_CURRENT_NOW=-257109
POWER_SUPPLY_TEMP=242
POWER_SUPPLY_VOLTAGE_NOW=4170660
POWER_SUPPLY_SAFETY_TIMER_ENABLED=1
POWER_SUPPLY_INPUT_CURRENT_MAX=400000
POWER_SUPPLY_INPUT_CURRENT_SETTLED=1
POWER_SUPPLY_INPUT_CURRENT_NOW=-22
POWER_SUPPLY_FLASH_ACTIVE=0
POWER_SUPPLY_FLASH_TRIGGER=0
POWER_SUPPLY_DP_DM=0
POWER_SUPPLY_INPUT_CURRENT_LIMITED=1
POWER_SUPPLY_RERUN_AICL=0
POWER_SUPPLY_RESTRICTED_CHARGING=0
POWER_SUPPLY_ENABLE_SHUTDOWN_AT_LOW_BATTERY=0
POWER_SUPPLY_CHARGE_FULL=2855000
POWER_SUPPLY_CHARGE_FULL_DESIGN=2980000
POWER_SUPPLY_CYCLE_COUNT=131
POWER_SUPPLY_FV_CFG=4350
POWER_SUPPLY_FV_CMP_CFG=8
POWER_SUPPLY_LRC_ENABLE=0
POWER_SUPPLY_LRC_SOCMAX=0
POWER_SUPPLY_LRC_SOCMIN=0
POWER_SUPPLY_LRC_NOT_STARTUP=0
POWER_SUPPLY_BATTERY_TYPE=1302-1082
POWER_SUPPLY_INT_CLD=0
POWER_SUPPLY_SMART_CHARGING_ACTIVATION=0
POWER_SUPPLY_SMART_CHARGING_INTERRUPTION=0
POWER_SUPPLY_SMART_CHARGING_STATUS=0
POWER_SUPPLY_INPUT_CURRENT_STATE=400```

Ampere shows it as USB charging instead  of AC charging.

**Comment by oshmoun** [comment]
according to POWER_SUPPLY_CURRENT_NOW, it seems to be charging at 0.5A, which is expected for loire and tone devices (not checked on yoshino)
EDIT: oh just noted POWER_SUPPLY_INPUT_CURRENT_MAX=400000, guess that's a better way to tell the charging rate that approximating using POWER_SUPPLY_CURRENT_NOW

**Comment by kholk** [comment]
The driver involved in this pr is used only on loire and (if it gets merged) kanuti.

**Comment by Bitti09** [comment]
@oshmoun  so that means without the help of  sony providing quickcharge  addon we are stuck to  500mA usb charging ?

**Comment by oshmoun** [comment]
@Bitti09 I was only commenting on your observation, and stating that what you're seeing is a known issue, sorry if there was a misunderstanding.
And this issue is not related to this pr, as kholk said.

**Pull request merged**
