### PR TITLE
[6.4.r1] rqbalance: Fix CPU resources lockdown (and some lagging)

### PR DESCRIPTION
**Pull request by kholk**
This patchset aims to address some lagging issues in some rather rare conditions on some devices, less rare on some others. Also, some cleanup has been done.

When the decider sets the RQBalance state to downcore, we may
still have a very CPU intensive process that is locking CPUFreq
to maximum frequency: this will make our frequency-based
algorithm kickstarter to just do nothing, while the userspace
may be spawning lots of other processes, resulting in a complete
hog of the current CPU available resources without being unable
to unlock more.

Of course, directly running a full evaluation right after that
will just waste CPU cycles and resources, so also introduce a
new worker delay variable "recheck_delay" that wants to be "an
high amount of time", preset to 2*down_delay: this will make us
able to wait enough time so that, if we have a single thread
that is very CPU intensive, we give it time to finish its job
without putting even more load on our system.

So:
If we want to forcefully downcore, and
- We haven't onlined all cores
- Our CPU is intensively used (perhaps by just one thread);
Then, run the worker again after recheck_delay millseconds
and prefer doing an upcore full evaluation to eventually
unlock more resources.

This PR appears to be similar to #1454, but:
1. Fixes the performance regressions introduced by that one
2. Fixes the power regressions
3. Decides based to the real current system load, instead of blindly temporarily disabling the downcore decision

### CODE REVIEW

**Comment by kholk** [comment]
Please test on ESPECIALLY Tone.
I won't cry if anyone tests on Loire, too :)

Tested on Maple.

**Comment by humberos** [comment]
Awesome!
My kagura just got a new life!
Good job!

**Review by humberos — APPROVED** [review]
It is ok on kagura.

**Review by humberos — APPROVED** [review]
Suzu is also ok!

**Comment by jerpelea** [comment]
all 3 platforms are ok

**Comment by kholk** [comment]
Merge!

**Comment by djselbeck** [comment]
After some days of testing I can say, that with this patch applied lacking got back (on kagura). Especially when playing embedded videos in firefox after a while the device locks on one online and three offline CPUs. Like the old behaviour. I think it took longer to happen.

- Kagura
- Running on battery
- Android 8.1

Playing video in firefox:
$ uname -a
Linux localhost 4.4.114-g967945836df8-dirty #1 SMP PREEMPT Sun Feb 18 10:25:43 CET 2018 aarch64
$ cat /sys/devices/system/cpu/offline                                    
1-3

**Pull request merged**
