### PR TITLE
[1.3.3] USB work around

### PR DESCRIPTION
**Pull request by mcgi5sr2**
Works on Aries.

### CODE REVIEW

**Comment by rcstar6696** [comment]
What was the problem?

**Comment by mcgi5sr2** [comment]
Detection of whether it was charging. 

I have created the pull request from a fix offered by the author on xda. Before patching my phone would struggle to decide if it was charging or not when plugged into a pc.

**Comment by jerpelea** [comment]
you are patching more than is needed.please cleanup your patch

**Comment by munjeni** [comment]
Ok

**Comment by jerpelea** [comment]
in this case the patch should be ifdefined for the RHINE platform only

**Pull request closed without merging**
