### PR TITLE
[DONOTMERGE] [2.3.2.r1.4] Support TCM incell touch displays on Apollo and Akari

### PR DESCRIPTION
**Pull request by MarijnS95**
Fixes https://github.com/sonyxperiadev/bug_tracker/issues/351
Fixes https://github.com/sonyxperiadev/bug_tracker/issues/262

Please do not merge this. The text below is merely an overview of what _has been addressed_. The commits might very well do this _the wrong way_. Let's discuss this together.

Unfortunately these devices have a hardware lottery with either Clearpad or TCM hardware.
The panel driver is rather messy and reports a powered panel+touch when it's not fully powered and/or still missing the mandatory reset. Clearpad _**hacks**_ around this by restarting a worker multiple times that probes i2c until it succeeds, which happens finally when the panel prepares.

This patch addresses that issue on Clearpad by forcing the incell touch on and the mandatory reset before probing. The 5-or-so failed attempts including stacktraces are now gone (and hopefully users report less instabilities).
Since TCM doesn't have such a thing, it calls for the incell to power up directly from `probe()`.

Finally, a little mess has been added that allows the TCM and Clearpad drivers to co-exist in the same kernel at runtime. Either one will be switched off when the other touch type is detected.
Stock does it the same way, from a userspace shell-script with kernel modules.

<details>
<summary>I have not included `CONFIG_TOUCHSCREEN_SYNAPTICS_TCM_FWUPG` which enabled firmware upgrading, and it seems to work fine without. But in order to make sure this works on every device, we _should_ add the images listed below to the repositories, and enable `FWUPG` in the defconf.</summary>

```
project device/sony/akari/
diff --git a/device.mk b/device.mk
diff --git a/device.mk b/device.mk
index a99479a..77cdac7 100644
--- a/device.mk
+++ b/device.mk
@@ -82,6 +82,13 @@ PRODUCT_COPY_FILES += \
 # BT/Wifi patch file
 PRODUCT_COPY_FILES += \
     $(DEVICE_PATH)/vendor/firmware/wlan/qca_cld/bdwlan.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/qca_cld/bdwlan.bin

+# Synaptics TCM touch firmware files
+PRODUCT_COPY_FILES += \
+    $(DEVICE_PATH)/vendor/firmware/touch_module_id_0x20.img:$(TARGET_COPY_OUT_VENDOR)/firmware/touch_module_id_0x20.img \
+    $(DEVICE_PATH)/vendor/firmware/touch_module_id_0x20.img:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/touch_module_id_0x20.img \
+    $(DEVICE_PATH)/vendor/firmware/touch_module_id_0x21.img:$(TARGET_COPY_OUT_VENDOR)/firmware/touch_module_id_0x21.img \
+    $(DEVICE_PATH)/vendor/firmware/touch_module_id_0x21.img:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/touch_module_id_0x21.img
+
 # Device Init
 PRODUCT_PACKAGES += \

project device/sony/apollo/
diff --git a/device.mk b/device.mk
index ad5cb4c..49b8c70 100644
--- a/device.mk
+++ b/device.mk
@@ -83,6 +83,13 @@ PRODUCT_COPY_FILES += \
 PRODUCT_COPY_FILES += \
     $(DEVICE_PATH)/vendor/firmware/wlan/qca_cld/bdwlan.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/qca_cld/bdwlan.bin
 
+# Synaptics TCM touch firmware files
+PRODUCT_COPY_FILES += \
+    $(DEVICE_PATH)/vendor/firmware/touch_module_id_0x30.img:$(TARGET_COPY_OUT_VENDOR)/firmware/touch_module_id_0x30.img \
+    $(DEVICE_PATH)/vendor/firmware/touch_module_id_0x30.img:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/touch_module_id_0x30.img \
+    $(DEVICE_PATH)/vendor/firmware/touch_module_id_0x31.img:$(TARGET_COPY_OUT_VENDOR)/firmware/touch_module_id_0x31.img \
+    $(DEVICE_PATH)/vendor/firmware/touch_module_id_0x31.img:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/touch_module_id_0x31.img
+
 # Device Init
 PRODUCT_PACKAGES += \
     fstab.apollo \
```

</summary>

### CODE REVIEW

**Comment by MartinX3** [comment]
Tested on XZ2 and XZ2 Compact.
It doesn't interfere with my clearpad touch and fixed the tcm touch.

Of course it needs the tcm firmware files outside of this PR and the here attached patch, too.

**Comment by MarijnS95** [comment]
The reason this was and _still is_ marked `DONOTMERGE` is because I have not properly tested it. It seems to work, but generates a ton of errors:
```
In file included from /data/aosp-q/kernel/sony/msm-4.9/kernel/include/linux/incell.h:4:
/data/aosp-q/kernel/sony/msm-4.9/kernel/include/uapi/../../drivers/gpu/drm/msm/dsi-staging/somc_panel/incell.h:57:5: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
#if INCELL_TAMA_MULTIPLE_TOUCH_DRIVERS
    ^
/data/aosp-q/kernel/sony/msm-4.9/kernel/include/uapi/../../drivers/gpu/drm/msm/dsi-staging/somc_panel/incell.h:55:3: note: expanded from macro 'INCELL_TAMA_MULTIPLE_TOUCH_DRIVERS'
        (defined(CONFIG_MACH_SONY_AKARI) || defined(CONFIG_MACH_SONY_APOLLO))
         ^
```
I will see about addressing these later.

**Comment by kholk** [comment]
I propose to remove the ifdefs completely and check instead for a substring of the panel name string.

If the panel name contains the "STCM" string, then assign TOUCH_TCM, otherwise, assign TOUCH_GENERIC.

If course you will have to change the panel name in DT... But that'll be way more extendible and way cleaner than what it is right now.

**Comment by MarijnS95** [comment]
@kholk I see what you mean, that would be better instead of basing it on the current panel name which is just a number.

It never came to me that this name is defined in the DT, somehwere in the thought process I figured this was passed in by the BL. But that can't be after seeing the logs, it's using ADC detection.

For that reason - since the type is bound to the panel anyway - I propose a DT property like `somc,mdss-dsi-panel-has-tcm-touch`. Then we can remove all the preprocessor crap and check for just that.

**Pull request merged**
