### PR TITLE
[LA.UM.6.4.r1] Merge tag 'LA.UM.6.4.r1-08000-8x98.0'

### PR DESCRIPTION
**Pull request by tomgus1**
Merged latest CAF tag into SODP kernel

### CODE REVIEW

**Comment by nathanchance** [comment]
* `sound/usb/card.c`: Should be fully discarded because 91d389709dcfca423899dc7bf620414ae93c8676 ("ALSA: usb-audio: Check out-of-bounds access by corrupted buffer descriptor") is already present properly in efbc93bfa41d10524e9419b745e111d8db8d9473 ("treewide: Linux 4.4.92") and the follow up commit ec9cdcc0df6f1ecf4f6180dd8b9980841fbe1d1e ("treewide: Fix merge mistakes").

* `drivers/usb/core/config.c`: Should be fully discarded because 73e6d15b10185d38187d98bf3122b0af672c9c27 ("USB: fix out-of-bounds in usb_set_configuration") and cc125e1f5586c2f078d513b3b26d15f2e861c3a1 ("USB: core: fix out-of-bounds access bug in usb_get_bos_descriptor()") are already present in efbc93bfa41d10524e9419b745e111d8db8d9473 ("treewide: Linux 4.4.92") and f9c05fbc3def3ba0f65837e530a0b2221927ea4f ("treewide: Linux 4.4.95"). There were some follow up fixes/improvements in 350583498835ac062fac13dcdd6a35efe47c5e65 ("treewide: Linux 4.4.105") so git couldn't make a clean resolution.

**Comment by tomgus1** [comment]
Sure, I can revert those two. They were my merge conflicts and wasn't too sure but thanks for the clarification :)

**Comment by nathanchance** [comment]
Always happy to help :)

**Comment by tomgus1** [comment]
Can folks test please, my suzu is away for repair so can't test but built my side.

**Comment by kholk** [comment]
@oshmoun You may be interested in exactly two or three commits in this PR.... :)))

**Comment by oshmoun** [comment]
kugo boots, and the first vulkan benchmark run didn't fail
still has the "checkers effect" though

**Comment by pablomh** [comment]
Hi @tomgus1, would you mind rebasing on top of https://github.com/sonyxperiadev/kernel/pull/1628?

**Comment by oshmoun** [comment]
@pablomh this merges cleanly on top of #1628 here. Do you see conflicts when merging?

**Comment by tomgus1** [comment]
@pablomh @oshmoun Merges cleanly here too on top of #1628

**Comment by pablomh** [comment]
Thanks, and sorry for the question, Just wanted to be sure :)

PS: Merged and running on pioneer (nile platform).

**Comment by oshmoun** [comment]
this may be causing some rare gpu crashes on loire, especially when running chrome.

**Comment by jerpelea** [comment]
9 days passed 
which platforms are tested?

**Comment by pablomh** [comment]
Nile here and no apparent issues.

**Comment by LLJY** [comment]
@jerpelea Kagura, no apparent issues

**Comment by jerpelea** [comment]
loire?

**Comment by oshmoun** [comment]
loire is mentioned above, the comment about some rare crashes.
now running without the pr to see if it's indeed the cause. there are changes here to adreno/kgsl, so it is probable.

**Comment by jerpelea** [comment]
yoshino?

**Pull request merged**
