### PR TITLE
[7.1.r1] Linux 4.14.196

### PR DESCRIPTION
**Pull request by stefanhh0**
The patch command ran without any problems, just a couple of fuzz merges which I have checked and look fine.

Please review and test.

The kernel already runs fine on Yoshino/Lilac.

### CODE REVIEW

**Comment by pablomh** [comment]
Hi @stefanhh0 , can you please rebase after latest changes to the conflicting file?

**Comment by stefanhh0** [comment]
@pablomh Rebased and force pushed.

**Comment by Haxk20** [comment]
Tested on pioneer. Boots up and critical features work. Havent tested further.

**Comment by jerpelea** [comment]
cherry-picked

**Pull request closed without merging**
