### PR TITLE
arm64: crypto: Updates from AOSP

### PR DESCRIPTION
**Pull request by humberos**
These changes was incorporated into AOSP@3.10 tree (from Linaro team).
This patchset enables some optimizations in recent Cortex-A5x cores that improves it performance.

### CODE REVIEW

**Comment by kholk** [comment]
Is this merged on android-3.10 for MSM or generic?
May be breaking hardware crypto... did you check?

**Comment by humberos** [comment]
https://github.com/android/kernel_msm/commits/android-msm-angler-3.10-marshmallow-dr/arch/arm64/crypto

**Comment by humberos** [comment]
BTW, this aosp branch is based on CAF BF64 1.2.1 and up to 1.2.9.   I think 1.2.9 will not be public  released from CAF  is it?

**Comment by Tommy-Geenexus** [comment]
@humberos 

https://github.com/torvalds/linux/commit/08c6781cfaa196d4b257ec043c17e8746d9284e3
This is the correct fix for the priority issue (altough i think its fine as long as beeing under 300).

I tested these patches on Stock (which uses HW-Crypto) and nothing broke, so this should be just fine.

**Pull request merged**
