### PR TITLE
[1.3.3] [MSM8974] kernel compression

### PR DESCRIPTION
**Pull request by alviteri**
use XZ for kernel compression
add BZIP2 and LZMA ramdisk compression

Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by alviteri** [comment]
boot.img and recovery.img have better size 
also fixes big ramdisk on cm/los recovery.img

ping @AdFad666 @adrianDC

**Comment by alviteri** [comment]
ping @kholk

**Comment by scafroglia93** [comment]
@alviteri Great PR, XZ it's my default kernel kernel compression

**Comment by scafroglia93** [comment]
@jerpelea 

This is my old custom kernel for SonyAosp (Z3) XZ was the default kernel compression

https://github.com/CasualsKernelProject/leo/commit/7ca68c9c10c4b1fcbdb065bf0abdcf177198f95a

Save about 4MB

**Comment by kholk** [comment]
Xz compression is cpu intensive. We have lots of space and, at boot, eMMC is initialized in HS by bootloader. Our bottleneck for boot time from bootloader is CPU, so this patch will make it worse.

**Comment by scafroglia93** [comment]
Yep, you're right about cpu stress for XZ

**Comment by alviteri** [comment]
So good bye custom support like cm recovery and rest close

**Comment by alviteri** [comment]
What about LZMA ? @scafroglia93

**Comment by stellirin** [comment]
Recovery lives in its own partition but it is actually the boot kernel that loads the ramdisk from the recovery partition. The recovery kernel does not need to be the full kernel. You could simply build a stripped down kernel with almost no drivers as the kernel in the recovery partition is never used.

**Pull request closed without merging**
