### PR TITLE
Fix for Suzu OTG

### PR DESCRIPTION
**Pull request by tomty89**
NOT TESTED. Please help test it if you can. Refer to #1206 or get in touch with @kholk for more details.

### CODE REVIEW

**Comment by humberos** [comment]
Just wondering if it is not a platform requirement. I mean about kugo,
ping @oshmoun

**Comment by oshmoun** [comment]
sure, could test that
just, what is the targeted difference, i.e what is supposed to change in the behaviour? afaik otg works well 😅

**Comment by tomty89** [comment]
@oshmoun tbh no idea. @kholk briefly explained about it in #1183 and #1206 but i am still not sure what exactly it does. i just create this as a supplement/fix for 867d794, as i've told in the commit message

**Comment by oshmoun** [comment]
sorry for the wait
the function is only defined for suzu
https://github.com/sonyxperiadev/kernel/blob/083cfc020ea502f033cfa3d9819a6efd448d92ec/drivers/usb/phy/phy-msm-usb.c#L209
since that was always the case from before, I'm assuming the fix (whatever it's supposed to do) is only targeting suzu
kugo and suzu do differ a bit on the usb hw side, as kugo has usb type c similar to XZ

**Comment by tomty89** [comment]
Yeah I mentioned in the commit message that "In commit 867d794, msm_otg_select_usb_switch was introduced for Suzu to..."

The problem in the original commit was, that function apparently changes the port selection (whatever it is) according to `id_state` (i.e. OTG state), but was only called at one point where `id_state` can get changed, while that can happen at some other points.

So what I am doing here is merely filling back in what was missed programatically/logically. As for whether the function itself was ever proper, or ever needed for Suzu, I assume @kholk should know best...

**Comment by jerpelea** [comment]
your last patch affects an unused platform !

**Comment by tomty89** [comment]
@jerpelea sorry are you talking to me? what last patch? are you referring to 1d80df9 which got mis-auto-tagged/linked to this pull request?

**Comment by jerpelea** [comment]
1d80df9 is for rockchip devices

**Comment by tomty89** [comment]
@jerpelea the commit was never intended to be relevant, it "referred" to this pull request just because this line in its commit message:

```
[ 7226.716722] CPU: 1 PID: 1708 Comm: bash Not tainted 4.12.0-rc6+ #1213
```

which is a line of log that happens to consists of "#1213"

**Comment by jerpelea** [comment]
ok

**Pull request closed without merging**
