### PR TITLE
msm-audio: dtsi: remove double pcm2: qcom,msm-ultra-low-latency

### PR DESCRIPTION
**Pull request by alviteri**
already defined after

pcm1: qcom,msm-pcm-low-latency

Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by kholk** [comment]
Utterly wrong.
See #1774.

**Comment by jerpelea** [comment]
unfortunately this is wrong because some platforms need pcm2 config

**Comment by alviteri** [comment]
alin your comment seems not ok since it is already defined and defined again ... check the DT ... anyway i still think this is double def

**Comment by jerpelea** [comment]
where is the second definition?

**Comment by alviteri** [comment]
https://github.com/SonyAosp/kernel/blob/aosp/LE.UM.2.3.2.r1.4/arch/arm64/boot/dts/qcom/msm-audio.dtsi#L32
https://github.com/SonyAosp/kernel/blob/aosp/LE.UM.2.3.2.r1.4/arch/arm64/boot/dts/qcom/msm-audio.dtsi#L46

**Comment by jerpelea** [comment]
you are right
please open a PR and add those 2 lines in commit message

**Pull request closed without merging**
