### PR TITLE
[1.2.2] msm8974: Fix torch

### PR DESCRIPTION
**Pull request by humberos**
Fix torch values by using stock configuration.

This patch set fixes : 
- torch duration
- code style

Tested on shinano Leo.

### CODE REVIEW

**Comment by humberos** [comment]
ping @rcstar6696

**Comment by rcstar6696** [comment]
Torch is okay but flashlight while takeing a photo is not okay flashlight turns of to early

**Comment by humberos** [comment]
Yeah, flash requires camerav2 changes. But it brightnnes was increased as I mentioned in PR/commit message. Torch is the main fix here.

**Comment by rcstar6696** [comment]
Okay then we can merge it sirius is okay here castor has no torch :)

**Comment by rcstar6696** [comment]
When i use torch atm it flickers in a high frecuency but it does not turn off like before

**Comment by humberos** [comment]
You are right. It happens due to VFE IRQ problem. Just check logs then you'll see the mess

**Comment by humberos** [comment]
But if you use torch from a fresh reboot it works perfectly.

**Comment by kholk** [comment]
OMG!!!! Are you really sure about those current and max-current value?!??! That looks HUGE!!!
I have written those values based on what Sony's driver for flash was doing.......

About the qpnp-led changes, those look really scary, but well, if they're working... okay.

**Comment by jerpelea** [comment]
this is dangerous and we should avoid burning hw!

**Comment by jerpelea** [comment]
please remove the max-curent changes untill we check the hw

**Comment by humberos** [comment]
ok, working on it.

**Comment by jerpelea** [comment]
The patch has to be tested on all platforms not only shinano
please post the steps to replicate the bug

**Comment by humberos** [comment]
Without this patch, torch (or Android Flashlight option)  works only during 12 seconds and its brightness is not so good when compared with stock version.

Although this patch fixes torch on Shinano devices (at least) but the VFE still have IRQ problems during torch or camera flash enabled (using this patch or not).

VFE logs:
http://paste.omnirom.org/view/34b0b271

**Comment by humberos** [comment]
ping @erikcas
please, could you confirm if this issue is present on rhine nor kitakami ? 
thank you.

**Comment by erikcas** [comment]
@humberos torch off after 12 seconds is confirmed on amami. Brightness however seems fine to me, but I have not seen stock on amami for ages.

Sumire atm on stock, will flash M in half an hour or so and edit here

**Comment by humberos** [comment]
@erikcas 
Thank you!
Great! So, could you apply this patch for rhine too and see if it will get flashlight duration fixed.
If it is ok then I will update this patch by adding rhine.

**Comment by erikcas** [comment]
@Humberos will do. On Sumire NO problems with flashlight duration

**Comment by erikcas** [comment]
@humberos adjusted for rhine and tested on amami: +1

**Comment by alviteri** [comment]
Tested on honami +1

**Pull request merged**
