### PR TITLE
[6.4.r1] Backport clearpad changes from k4.9

### PR DESCRIPTION
**Pull request by artem**

### CODE REVIEW

**Comment by kholk** [comment]
Thanks for cherry-picking.
Can anyone quickly test this before merging, please?

Thanks again!

**Comment by oshmoun** [comment]
lost touch input on kugo after turning screen on! turning screen off and on again fixed it.
https://hastebin.com/amiromulas.sql
~touch completely breaks after a while, with the only way to get it back being a reboot~
it gets much harder to revive touch after a while

**Comment by erikcas** [comment]
Can one of the admins verify this patch?

**Comment by jerpelea** [comment]
I would prefer to freeze the stable kernel and add only kernel security patches

**Pull request closed without merging**
