### PR TITLE
[7.1.r1] arm64: dts: qcom: sm8150: Correct addresses from 55.2.A.xxx

### PR DESCRIPTION
**Pull request by voidanix**
**Actually** fixes https://github.com/sonyxperiadev/bug_tracker/issues/694

### CODE REVIEW

**Comment by voidanix** [comment]
In case you are wondering, running a stock-based kernel with these updated addresses works just fine with both the A10 and A11 modem firmware, so I expect it to "just werk" here as well.

**Review by jerpelea — APPROVED** [review]

**Comment by jerpelea** [comment]
not the best explanation but a valid patch

**Comment by MarijnS95** [comment]
The modem subsystem probably needs a bigger memory region (presumably for firmware, PIL = Peripheral Image Loader) but nothing in this patch explains it.

Besides, I'm certain this is _not_ about the addresses anyway. You're increasing the size of the modem PIL memory area, and for that the rest simply has to move out of the way.

**Comment by jerpelea** [comment]
@MarijnS95 valid explanation  ;)

**Comment by MarijnS95** [comment]
If only it would have made it into the commit message :smirk::wink::smirk::wink:. Who knows, _maaaaaybe_ future contributions.

**Comment by voidanix** [comment]
@MarijnS95 yeah, my bad.

The qcom commits regarding this just go "we got new memory mappings lol" without explaining anything: I just went ahead and explained the consequences of not having the DTS updated.

**Comment by jerpelea** [comment]
@voidanix you will do it in the future ;)

**Comment by Thaodan** [comment]
> The modem subsystem probably needs a bigger memory region (presumably for firmware, PIL = Peripheral Image Loader) but nothing in this patch explains it.
> 
> Besides, I'm certain this is _not_ about the addresses anyway. You're increasing the size of the modem PIL memory area, and for that the rest simply has to move out of the way.

I just catched up with this, yeah very late.

Thanks for explaining the change, it does not make sense outright because the context is missing.
Issues like these also very easily explain bugs that happened when people flashed the "wrong" stock Android.

**Pull request merged**
