### PR TITLE
[LA.UM.7.1.r1] Initial update to the latest 4.14 version

### PR DESCRIPTION
**Pull request by nathanchance**
This updates the Linux version from 4.14.84 to 4.14.164 (latest version at the time of writing this).

I do not see any build regressions with this using `clang-r353983c`. `aosp_loire_blanc_defconfig` and `aosp_yoshino_poplar_defconfig` do not build for me locally, not sure if that is the case for everyone. 

Unfortunately, just because everything builds fine doesn't mean that something won't happen at run time :) If there is some sort of run time issue, please bisect to find which version causes the issue since there are a LOT of changes here.

### CODE REVIEW

**Comment by kholk** [comment]
Thanks a lot man! 

Get the testing started guys!

**Comment by MarijnS95** [comment]
The test results are in!

- **Discovery**:
  Crashes on boot unless https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/drivers/usb/dwc3/gadget.c?h=v4.14.111&id=df4a6a265b2c07d42f4dd0e960d73d40be1ce2f6 is reverted (.111). Looks like the hypervisor doesn't like us reading `dwc3_readl(dwc->regs, DWC3_DCFG);`.
  ```
  [    1.735136] dwc3 a800000.dwc3: changing max_speed on rev 00000000
  [    1.737442] Synchronous External Abort: synchronous external abort (0x96000010) at 0xffffff800bafe700
  [    1.737560] Internal error: : 96000010 [#1] PREEMPT SMP
  [    1.737675] Modules linked in:
  [    1.737740] Process swapper/0 (pid: 1, stack limit = 0xffffffc0f94bc000)
  [    1.737856] CPU: 0 PID: 1 Comm: swapper/0 Not tainted 4.14.164-gd498f399a6e2-dirty #56
  [    1.737918] Hardware name: Qualcomm Technologies, Inc. SDM 630 PM660 + PM660L MTP (DT)
  [    1.738029] task: ffffffc0f94e8000 task.stack: ffffffc0f94bc000
  [    1.738103] pc : dwc3_gadget_init (drivers/usb/dwc3/gadget.c:4074) 
  [    1.738216] lr : dwc3_gadget_init (drivers/usb/dwc3/gadget.c:4100) 
  [..]
  [    1.741367] dwc3_gadget_init (arch/arm64/include/asm/io.h:85 drivers/usb/dwc3/io.h:36 drivers/usb/dwc3/gadget.c:2594 drivers/usb/dwc3/gadget.c:4095) 
  [    1.741429] dwc3_probe (drivers/usb/dwc3/core.c:1344) 
  [    1.741546] platform_drv_probe (drivers/base/platform.c:581) 

  ```
  After that, `tftp_server` goes nuts.
- **Mermaid**:
  Obviously, identical to Nile:
  ```
  [    1.772893] Bad mode in Error handler detected on CPU7, code 0xbf000000 -- SError
  [    1.772979] Kernel panic - not syncing: bad mode
  ```
- **Griffin**:
  Doesn't get past the bootanimation, nothing immediately obvious (inbetween the `pm_qos_add_request() called for already added request` warnings and expected crashing services).
- **Akatsuki**:
  DD, will get tested after I return :wink:

Unfortunately I have to leave right now, more testing and debugging continues in the afternoon.

**Comment by oshmoun** [comment]
a `synchronous external abort` could also be unclocked access afaik

**Comment by nathanchance** [comment]
@MarijnS95 thanks for figuring out the dwc3 commit; looks like Qualcomm also reverted this so I will apply it right after the 4.14.111 merge for documentation: https://source.codeaurora.org/quic/la/kernel/msm-4.14/commit/?id=207d4bf2dfadef2b6765eaee4c22a38de90618b1

**Comment by MarijnS95** [comment]
@nathanchance Neat, I didn't bother to look at CAF just yet. Looks like @oshmoun was right:

> which does not hold true for qcom socs. It leads to
> unclocked register access.

Thanks for PR'ing all these! I'll continue debugging the tftp issue and get the other devices running.

**Comment by jerpelea** [comment]
@nathanchance please add the revert so that I can merge it

**Comment by jerpelea** [comment]
@nathanchance poplar and blanc builds are fixed

**Comment by pablomh** [comment]
My pioneer doesn't boot fully to Android with this patch applied where it did without it (still analyzing).

**Comment by jerpelea** [comment]
@nathanchance  please rebase
This update is huge and I think that is better if i cherry-pick chunks from it 

Thanks

**Comment by MarijnS95** [comment]
@nathanchance [arm64: Ensure VM_WRITE|VM_SHARED ptes are clean by default](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v4.14.152&id=343e5699b74e8b9806b8627d59aa00243f5c96c8) (in .152) prevents Android from booting properly. It is likely that some of our drivers are not setting their memory protection attributes properly, causing the hypervisor to lock things up.
Unfortunately CAF does not have any obvious tag with .152 yet so we can't see if they worked around this issue. Reverting it allows me to boot into .164 :)

**Comment by nathanchance** [comment]
@jerpelea I have rebased it, thanks!

@MarijnS95 That's pretty bad; I could have sworn there was a follow up fix to that commit but I don't remember which it was and it should have happened by 4.14.164. I don't really feel comfortable reverting that, there should be more investigation into what driver is causing the issue and fixing it.

**Comment by MarijnS95** [comment]
I wonder if anyone has the time to actually look into it. It seems to be a silent lockup, no warning signs indicating where this issue happens. Do you have any debugging recommendations to approach this issue?

Besides, I have locally resolved the conflict with `net/wireless/util.c` in .166 by moving our cherry-picked addition `cfg80211_is_gratuitous_arp_unsolicited_na` to the bottom to keep the .166 patch consistent with the stable kernel. Other than that we fixed the other conflicts in the exact same way; I was too late to PR them to you in favor of testing them on a bunch of devices.

**Comment by NukeMania** [comment]
patches doesn't contain this commit [9e8ed26e6062e4f585fe831fba362eb567648881]([https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=9e8ed26e6062e4f585fe831fba362eb567648881)
i think it's follow up fix that mention of it

**Comment by MarijnS95** [comment]
@NukeMania Thanks for mentioning, that indeed fixes the issue the without having to revert the other commit. @nathanchance Can you add 6767df245f4736d0cf0c6fb7cf9cf94b27414245 to the PR before/after .152 (not the merge commit 9e8ed26)?

**Comment by nathanchance** [comment]
I know what happened with that. I picked that commit directly after 4.14.152 in android-linux-stable so it wasn’t in my merge when it actually came through stable. I’ll squash it into the version that it should be in tonight.

**Comment by nathanchance** [comment]
Alright I’ve added it to 4.14.154, which is where it initially came in.

**Comment by jerpelea** [comment]
@MarijnS95 i hope i'll be able to to it today or tomorrow

**Comment by kholk** [comment]
4.14.150 - - Akatsuki's display dies after one suspend cycle.

**Comment by jerpelea** [comment]
please rebase

**Comment by nathanchance** [comment]
Done. I have added 4.14.167 to the mix as well.

**Comment by MarijnS95** [comment]
@nathanchance while at it feel free to add .167. It applies cleanly and no regressions are noticed on:

- Akatsuki DSDS
- Mermaid DSDS
- Discovery ROW
- Griffin DSDS

EDIT: That was a nice simultaneous post :thinking:

**Pull request merged**
