### PR TITLE
[1.2.1] Camera configurations, missed commits from other branch

### PR DESCRIPTION
**Pull request by kholk**

### CODE REVIEW

**Comment by rancidfrog** [comment]
For some reason this commits stops SIM from being detected.
Reverting _shinano: clean camera implementation_ fixes it,

```
git revert 108279fa7ce349563062db411708a398be5844c6
[aosp/AU_LINUX_ANDROID_LA.BF64.1.2.1_RB1.05.00.02.019.067 1403cbd] Revert "shinano: clean camera implementation"
 5 files changed, 1274 insertions(+), 2 deletions(-)
```

After that SIM detection works fine again.

**Comment by jerpelea** [comment]
instead of reverting a merge you can try to revert comits 1 by 1 to search for offending one

**Comment by jerpelea** [comment]
https://github.com/kholk/kernel/commit/108279fa7ce349563062db411708a398be5844c6#diff-3d42a7a07f227d7cd413f4cc363103d4R178 
is our suspect

**Comment by rancidfrog** [comment]
I reverted this commit only and it works after that: https://github.com/kholk/kernel/commit/108279fa7ce349563062db411708a398be5844c6

**Comment by jerpelea** [comment]
fixed and merged 
thanks for reporting

**Pull request merged**
