### PR TITLE
Kgsl updates

### PR DESCRIPTION
**Pull request by alviteri**

### CODE REVIEW

**Comment by kholk** [comment]
The commits logic looks fine.
Needs to be tested on LOIRE, Loire, loire, Tone and Yoshino....
...and on loire. :)

**Comment by alviteri** [comment]
Already up on Loire Loire Loire Loire tone and yoshino AND LOIRE Xd

**Comment by kholk** [comment]
Can we please re-test this on loire with the new iommu driver?
After re testing on loire I think this is safe to merge

**Comment by kholk** [comment]
P.S.: This should address a rare corruption issue I see on maple.

**Pull request merged**
