### PR TITLE
kumano camera

### PR DESCRIPTION
**Pull request by sraase**
Add camera device tree support for kumano.
Remove the unused sony_camera device nodes.

Do not inherit from QCOM MTP, because our hardware
configuration is different anyway. Results in a
cleaner, separate camera dt.

Also updates the CPAS node to match current kernels,
but this is partially guesswork based on the existing devicetree.

Note: Does not work!

### CODE REVIEW

**Comment by sraase** [comment]
The kernel still panics at boot:
> [    8.374854] CAM_DBG: CAM-UTIL: cam_soc_util_get_clk_level_to_apply: 320: Req level 3, Applying 3
> [    8.383888] CAM_DBG: CAM-UTIL: cam_soc_util_set_clk_rate: 391: set gcc_ahb_clk, rate -1
> [    8.392131] CAM_DBG: CAM-UTIL: cam_soc_util_set_clk_rate: 391: set gcc_axi_hf_clk, rate -1
> [    8.400626] CAM_DBG: CAM-UTIL: cam_soc_util_set_clk_rate: 391: set gcc_axi_sf_clk, rate -1
> [    8.409135] CAM_DBG: CAM-UTIL: cam_soc_util_set_clk_rate: 391: set slow_ahb_clk_src, rate 80000000
> [    8.418339] Unable to handle kernel paging request at virtual address fffffffffffffe23

Trying to enable (or even look at) slow_ahb_clk_src triggers the panic.

**Comment by bartcubbins** [comment]
CONFIG_MSM_CAMCC_SM8150 is not enabled. I can't pr it because of war, sorry.

**Comment by Thaodan** [comment]
> CONFIG_MSM_CAMCC_SM8150 is not enabled. I can't pr it because of war, sorry.
> 
Stay safe!

**Comment by MartinX3** [comment]
> CONFIG_MSM_CAMCC_SM8150 is not enabled. I can't pr it because of war, sorry.

Stay safe!

**Comment by sraase** [comment]
> CONFIG_MSM_CAMCC_SM8150 is not enabled.

You are right. I added the change to this PR, and the result boots. Still no camera, but at least it boots now. Stay safe!

**Comment by jerpelea** [comment]
Stay safe!

**Pull request merged**
