### PR TITLE
[LA.UM.6.4.r1] Merge tag 'LA.UM.6.4.r1-05900-8x98.0'

### PR DESCRIPTION
**Pull request by tomgus1**
Merged latest CAF tag into SODP Kernel

### CODE REVIEW

**Comment by danielgusvt** [comment]
Needs testing of course!

**Comment by humberos** [comment]
FPC fixed on kagura (by using this tag) so as I told before the fix is on kernel space.
ping @oshmoun

**Comment by tomgus1** [comment]
This is fixed on Loire (suzu) also.

**Comment by humberos** [comment]
yeah,... I can confirm that!

**Review by humberos — APPROVED** [review]
Although I don't know what's the proper way merging tags but we really need this tag. No regressions for kagura and suzu.

**Comment by humberos** [comment]
~~I did 20 reboots manually (on kagura) without the verity problem. So I think may we have another embedded fix.~~

NVM,... still broken.

**Comment by humberos** [comment]
FPC is working on suzu, but the workaround (mentioned in bugtracker) is not working anymore.
We will lost FPC after reboot cycle or if we use the workaround^.

> 01-22 00:37:28.913  5562  5562 E AOSP FPC HAL: Error loading user database: -6
> 01-22 00:37:28.913  5562  5562 E android.hardware.biometrics.fingerprint@2.1-service: An unknown error returned from fingerprint vendor library: -6
> 
which means that FPC HAL needs some love :(

Btw Kagura is ok by using the workaround.

**Comment by oshmoun** [comment]
Woah nice find! 
This proves me wrong about fpc then 😅
@humberos did you flash O ftf on your kagura? I.e does your kagura have O keymaster firmware?

**Comment by jerpelea** [comment]
camera  ok

**Pull request merged**
