### PR TITLE
[LA.UM.6.4.r1] loire: Configure TLMM register space as strongly ordered

### PR DESCRIPTION
**Pull request by humberos**
The MSM8953 register setting stuff is valid for Loire as well:
use it to solve CPUSS related unstabilities.

### CODE REVIEW

**Comment by humberos** [comment]
ping @kholk

**Comment by kholk** [comment]
Well, in reality I missed that on purpose.
Also, I don't see any CPUSS unstability on 6.4.r1 :D

**Comment by oshmoun** [comment]
the remaining causes of instability, so far observed, are utilization of the vulkan api, and having an sdcard inserted. So, newbie question:
Would this affect either of those?

**Comment by kholk** [comment]
Fairly sure it wouldn't, as this is affecting the CPUSS block (so addresses hotplugging and instabilities related to cpu sleep).
Though, well, trying won't kill you so... Just... Try it and tell me I'm right! :p

**Pull request closed without merging**
