### PR TITLE
adjust regulators and battery values

### PR DESCRIPTION
**Pull request by erikcas**
Regulators 8226_l5 and 8226_l27 differ in Eagle. It causes some drivers to fail to load.
Also took batteryvalues from stock referencekernels

### CODE REVIEW

**Comment by jerpelea** [comment]
instead of copying those files you can overlay needed values

**Comment by erikcas** [comment]
the dtsi thing is quite new to me as a die hard 7x27 and 7x27a user. I get the point, will redo it :-)

**Comment by jerpelea** [comment]
lets talk on xda or gtalk

**Comment by erikcas** [comment]
gtalk = erikcas1972@gmail.com

Redid it, will test in half an hour or so. If tests oke, I will open a new pullrequest

**Pull request closed without merging**
