### PR TITLE
[LA.UM.6.4.r1] Merge tag 'LA.UM.6.4.r1-07600-8x98.0' 

### PR DESCRIPTION
**Pull request by tomgus1**
Merged latest CAF tag into SODP Kernel

### CODE REVIEW

**Comment by kholk** [comment]
Half of the commits in there are REALLY interesting. Let's give this a good test, should bring some good improvements!

**Comment by oshmoun** [comment]
especially those concerning kgsl!

**Comment by kholk** [comment]
Pinched! :p

**Comment by oshmoun** [comment]
https://github.com/sonyxperiadev/kernel/pull/1602/commits/507f372acebdbfa2105b0241dbf939c03f231ec1
this commit conflicts with the linux upstream merges. specifically with https://patchwork.kernel.org/patch/10218657/

Both commits seem to have the same goal, so the question is whether to overwrite the linux upstream update with a caf change, or ignore the caf update. caf over linux or linux over caf?

**Comment by oshmoun** [comment]
so, to get this merge working, the following commits can be reverted:
https://github.com/sonyxperiadev/kernel/commit/507f372acebdbfa2105b0241dbf939c03f231ec1
https://github.com/sonyxperiadev/kernel/pull/1602/commits/97f857f556d5a141ea947326ca9f40f4821533ef
The first one has been explained in the above comment.
The second one breaks boot on loire and tone

**Comment by jerpelea** [comment]
kernel.org has priority

**Comment by tomgus1** [comment]
Reverted both commits

**Comment by kholk** [comment]
No no no no no no no no don't revert the second one. Check if it works on the other platforms and, if it does, then add a build barrier for loire on top.
If that's the case, on the next kernel we will find the same commit and we will apply the same barrier.

**Comment by tomgus1** [comment]
Okay, only first reverted. Can others check the remaining platforms?

**Comment by kholk** [comment]
Thanks!

**Comment by tomgus1** [comment]
Sooo, without the revert for 97f857f as @oshmoun stated, boot on Loire is broken with Magisk installed as the boot fails verity.

**Comment by oshmoun** [comment]
@tomgus1 pretty sure magisk is unrelated. Device will crash due to failing verification either way.

**Comment by tomgus1** [comment]
@oshmoun The device booted okay without the revert but if I was to install magisk the device would fail verification. Applying the revert allows me to pass verification if I installed magisk.

**Comment by tomgus1** [comment]
So, further testing concludes that Reverting 97f857f is required 100% on Loire. Yes it can boot but activating WiFi causes the device to crash and reboot.

**Comment by oshmoun** [comment]
the commit can then probably be ifndeffed with CONFIG_BCMDHD

**Comment by tomgus1** [comment]
Done, builds perfectly now

**Comment by tomgus1** [comment]
Loire and Tone both confirmed to be working no issues. Can someone with Yoshino and Nile test please?

**Pull request merged**
