### PR TITLE
[6.4.r1] somc_panel: Remove legacy panel support

### PR DESCRIPTION
**Pull request by bartcubbins**
There is no more reason to support legacy display panel driver.
Tulip had a chance to get 4.4 kernel, but because a4xx does not have an updated firmware, it's impossible.

### CODE REVIEW

**Comment by bartcubbins** [comment]
ping @kholk

**Comment by bartcubbins** [comment]
ping @kholk

**Comment by kholk** [comment]
I agree, but... let's just wait a little more. Probably the best idea will be to remove that in the next kernel porting.

**Comment by pablomh** [comment]
As sad as I am to accept it, I think it's the way to go :(

**Comment by kholk** [comment]
The legacy panel driver is still needed.
Please, close this PR.

**Pull request closed without merging**
