### PR TITLE
[LA.UM.7.1.r1] staging: android: Put back timed_output back to the dead again

### PR DESCRIPTION
**Pull request by Thaodan**
It is long deprecated and the ldo_vibrator driver doesn't need it
anymore.

Signed-off-by: Björn Bidar <bjorn.bidar@jolla.com>

### CODE REVIEW

**Comment by bartcubbins** [comment]
I wonder why it even came back from the dead on this kernel tag.
If some of the devices still use LDO vibrator driver, then we need this https://github.com/sonyxperiadev/kernel/pull/2058

**Comment by bartcubbins** [comment]
If you rebase and cherry-pick https://github.com/sonyxperiadev/kernel/commit/9a98821ac9ff3df0cc507c473d30723c560dde0e commit this change will become appliable. LDO Vibrator driver is still used by Tama/Apollo device.
Thanks!

**Comment by Thaodan** [comment]
> If you rebase and cherry-pick [9a98821](https://github.com/sonyxperiadev/kernel/commit/9a98821ac9ff3df0cc507c473d30723c560dde0e) commit this change will become appliable. LDO Vibrator driver is still used by Tama/Apollo device. Thanks!

Cherry picked the commit mentioned please test.

**Review by bartcubbins — APPROVED** [review]

**Comment by bartcubbins** [comment]
Thank you!

**Comment by jerpelea** [comment]
@Thaodan please rebase and sumbit the PR to 9.12

**Comment by bartcubbins** [comment]
@jerpelea already in tama pr

**Comment by jerpelea** [comment]
@bartcubbins I saw. Thanks

**Pull request merged**
