### PR TITLE
Enable AIO, as it now required by Android P

### PR DESCRIPTION
**Pull request by a1batross**
See: https://android.googlesource.com/kernel/configs/+/4ed084e489fd1a4b5776715538979d3e921969f0

### CODE REVIEW

**Comment by jerpelea** [comment]
please push the config changes to base_ defconfig using the same layout (1 commit /platform)
Thanks

**Comment by jerpelea** [comment]
it is enabled in the auto generated configs 
https://github.com/sonyxperiadev/kernel-defconfig/blob/aosp/LE.UM.2.3.2.r1.4/android-base.cfg#L10

**Comment by a1batross** [comment]
Autogenerated works for 4.4 now?

**Comment by jerpelea** [comment]
P does not use 4.4 kernel

**Pull request closed without merging**
