### PR TITLE
Pixel2 vidc

### PR DESCRIPTION
**Pull request by alviteri**

### CODE REVIEW

**Comment by alviteri** [comment]
@kholk

**Comment by kholk** [comment]
Remove the addb1da commit and PR it separately. The other ones are safe to merge.

The addb1da commit can be merged only after loire camcorder works.

**Comment by alviteri** [comment]
then we can let this open until to that

**Comment by jerpelea** [comment]
split it !

**Comment by alviteri** [comment]
splited alin the other first 2 were already picked by angelo

**Pull request merged**
