### PR TITLE
[LA.UM.9.12.r1] Linux 4.19.178

### PR DESCRIPTION
**Pull request by Haxk20**
## 4.19.171
Reverting UPSTREAM: kasan: rename source files to reflect the new naming scheme allowed it to apply cleanly.

## 4.19.172
Had to revert that patch as it was previously applied. 172 included the proper fix. (Slightly modified version of downstream patch).

## 4.19.176
Reverting Revert "regulator: Enable supply regulator if child rail is enabled allowed the patch to apply cleanly.

## 4.19.177
Reverting net: qrtr: Only update pkts with broadcast node ID allowed patch to be applied cleanly.

## 4.19.178
Simply just small conflict.

### CODE REVIEW

**Comment by konradybcio** [comment]
171: Instead of skipping, pick missing patches https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/mm/kasan/kasan_init.c?h=1ad3d65c&qt=grep&q=


176: Same, starting from `regulator: resolve supply after creating regulator`: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/drivers/regulator/core.c?h=v4.19.176

177: (Apparently CAF kernel doesn't feature some !!4.18!! changes...

**Comment by Haxk20** [comment]
> 171: Instead of skipping, pick missing patches https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/mm/kasan/kasan_init.c?h=1ad3d65c&qt=grep&q=
> 

Pointless. The changes are there. The file was simply renamed. Reverting that commit allowed the commits to be applied.

> 176: Same, starting from `regulator: resolve supply after creating regulator`: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/drivers/regulator/core.c?h=v4.19.176
> 

Again pointless. The commits are already in the kernel update patches. There was commit removing the needed changes. Reverting this allowed it to apply cleanly.

> 177: (Apparently CAF kernel doesn't feature some !!4.18!! changes...

Absolutely not. Simply reverted the commit causing the changes and applied 177 on top. Applied cleanly.

Will test and push the new update patches

**Comment by Haxk20** [comment]
I forgot.
Tested on Xperia1II. Everything works.

**Comment by MarijnS95** [comment]
> Reverting ... allowed .... to be applied cleanly.

You should mention this in the revert-commits itself **first and foremost**. A small comment along the lines of "Reverting downstream/CAF patch in favour of upstream patch (XXX eventually link to the commit) in linux-stable 4.19.XXX".

### 4.19.172

> Small conflict

Be thorough in your documentation. This isn't something we can review.

### 4.19.176

> Tiny conflict

Same comment here.

### 4.19.178

> 2 single line conflicts.

And here.

Feel free to skip the "Skipped: Nothing." and the like. This is implied when there are no conflicts or issues explicitly documented (and if you didn't document them in the first place, shame on you :grin:). Instead/again, fill your commit with actually useful information like Stefan and Pablo used to do: https://github.com/sonyxperiadev/kernel/pull/2417/commits/4abf996d1125b208015aac86daec641b8b5a3c8d

**Comment by Haxk20** [comment]
> > Reverting ... allowed .... to be applied cleanly.
> 
> You should mention this in the revert-commits itself **first and foremost**. A small comment along the lines of "Reverting downstream/CAF patch in favour of upstream patch (XXX eventually link to the commit) in linux-stable 4.19.XXX".
> ### 4.19.172
> 
> > Small conflict
> 
> Be thorough in your documentation. This isn't something we can review.
> ### 4.19.176
> 
> > Tiny conflict
> 
> Same comment here.
> ### 4.19.178
> 
> > 2 single line conflicts.
> 
> And here.
> 
> Feel free to skip the "Skipped: Nothing." and the like. This is implied when there are no conflicts or issues explicitly documented (and if you didn't document them in the first place, shame on you grin). Instead/again, fill your commit with actually useful information like Stefan and Pablo used to do: [4abf996](https://github.com/sonyxperiadev/kernel/commit/4abf996d1125b208015aac86daec641b8b5a3c8d)

All taken into consideration. Since i would have to rework the patches to explain simply the conflicts i will ignore it in this PR. As for the commit message i will add that in future PRs. As i said the next ones are gonna be well great quality :)

**Comment by jerpelea** [comment]
please rebase

**Comment by Thaodan** [comment]
> I forgot. Tested on Xperia1II. Everything works.

Did you test modem?

**Comment by Haxk20** [comment]
> > I forgot. Tested on Xperia1II. Everything works.
> 
> Did you test modem?
> 

4G breaks some things but this was even before this patch. Use 3G to get sms back

**Pull request merged**
