### PR TITLE
[1.3.3] Restructured SoMC Panel driver + In-Cell support + MMC5.0

### PR DESCRIPTION
**Pull request by kholk**

### CODE REVIEW

**Comment by humberos** [comment]
@kholk 
Seems panel is ok on Karin
https://gist.github.com/humberos/fff266a65dd5aa0cca90cbbb3db6f5f2

**Comment by humberos** [comment]
~~Btw, I am getting this logspam:~~
~~[   85.195848] mdss_fb_do_ioctl: unsupported ioctl (c3086d87)~~
~~[   85.200872] mdss_fb_do_ioctl: unsupported ioctl (c3086d87)~~
~~[   85.533945] mdss_fb_do_ioctl: unsupported ioctl (c3086d87)~~
~~[   85.539037] mdss_fb_do_ioctl: unsupported ioctl (c3086d87)~~
~~...~~

**Comment by kholk** [comment]
Humberto, did you run it on a ROM compiled for 1.3.3 with the right headers?
...otherwise the spam is really normal

**Comment by jerpelea** [comment]
i have tested the patch and it works ok on all devicss except sumire

**Comment by humberos** [comment]
@kholk oh, I am sorry. 
You're right.
Please just ignore that.

**Comment by kholk** [comment]
No problem man, it happens :)

**Pull request merged**
