### PR TITLE
[2.3.2.r1.4] Linux 4.9.150

### PR DESCRIPTION
**Pull request by nathanchance**

### CODE REVIEW

**Comment by pablomh** [comment]
No apparent regressions here (on pioneer / nile).

**Comment by kholk** [comment]
Now there are some interesting changes in here that I definitely like. Though there are changes to the DRM, can anyone please test this on any SDE device before merging? 

Thanks!

**Comment by pablomh** [comment]
My tests on pioneer were with SDE enabled.

**Comment by kholk** [comment]
Then we can safely merge it

**Pull request merged**
