### PR TITLE
Enable AIO, as it now required for Android P(k4.9)

### PR DESCRIPTION
**Pull request by a1batross**
See: https://android.googlesource.com/kernel/configs/+/4ed084e489fd1a4b5776715538979d3e921969f0

### CODE REVIEW

**Comment by jerpelea** [comment]
all configs are autogenerated now
please wait for the final referesh

**Comment by a1batross** [comment]
Autogenerated by build system? Or they will be pushed to repository? 

Okay, thanks anyway. :)

**Comment by jerpelea** [comment]
I am working on the new base configs and the aosp ones will be autogenerated soon

**Comment by a1batross** [comment]
Oh, cool. Is it true for 4.4? My second PR for it, also.

**Comment by jerpelea** [comment]
just 4.9

**Pull request closed without merging**
