### PR TITLE
The Big Display Affair

### PR DESCRIPTION
**Pull request by kholk**
....and some kitakami love :)

### CODE REVIEW

**Comment by galaxyfreak** [comment]
Oops, display broken on eagle.

**Comment by necioerrante** [comment]
Kernel build errors for aries: http://hastebin.com/aculerapev.js

with warnings, too: http://hastebin.com/dunupolosu.js

**Comment by kholk** [comment]
Sorry, yes I admit the previously unknown problems. 
Unfortunately, something got wrong in our testing run and I screwed up something big here. 

I will be able to dev on Monday, so, please wait for the proper fixes on this. 
If you need to compile the kernel right now, please revert the display changes that got merged in this PR until the proper fix comes. 

My apologies. 
Hope you understand!

**Comment by necioerrante** [comment]
No problem.
I was hoping to see if these updates would fix recovery black screen issues on aries.
Will test after the fixes.

**Pull request merged**
