### PR TITLE
[LA.BR.1.3.3_rb2.14] Merge BCMHD fixes from angler 3.10 - nougat-mr2

### PR DESCRIPTION
**Pull request by pablomh**
**Please test as I don't have the hardware to do it.**

### CODE REVIEW

**Comment by rcstar6696** [comment]
Any reason why not enable the config on all devices like msm 8974 ?

**Comment by pablomh** [comment]
Finer grained control.

I'll leave it up to @jerpelea to decide.

**Comment by jerpelea** [comment]
after the patch will be fixed and tested we can enable it on all devices that use BCMDHD

**Comment by pablomh** [comment]
This one builds in kitakami and loire at least.

**Pull request merged**
