### PR TITLE
Misc dev

### PR DESCRIPTION
**Pull request by alviteri**
related to usb midi

### CODE REVIEW

**Comment by alviteri** [comment]
tested on leo and honami

**Comment by kholk** [comment]
Ok! But you pushed to the wrong branch!

**Comment by alviteri** [comment]
@kholk which is the correct....

**Comment by kholk** [comment]
This branch is for commits entirely made by "external" developers, such as you and as well me, mostly modifying QC implementation somehow and for some reason.

Push that change to drivers ;)

**Comment by alviteri** [comment]
thanks @kholk

**Pull request closed without merging**
