### PR TITLE
yukon: set the correct screen dimensions

### PR DESCRIPTION
**Pull request by stellirin**
Not sure how Android uses these, but tianchi has wrong values and flamingo
lacks them completely. Fortunately Android functionality seems unaffected.

However Mozilla's B2G uses these to determine screen density. Incorrect (or
missing) values gives incorrect scaling.

Signed-off-by: Adam Farden adam@farden.cz

### CODE REVIEW

**Comment by jerpelea** [comment]
should be checked on all panels

**Comment by kholk** [comment]
It's just for userspace things. Won't change anything kernel-side, safe to merge

**Comment by stellirin** [comment]
Now all yukon devices have them

**Comment by jerpelea** [comment]
please look into all platforms

**Comment by stellirin** [comment]
All rhine / shinano have `somc,mdss-phy-size-mm` but not the qcom ones. However I don't have any issues on sirius, and the mozilla guys don't have any issues on aries / leo so it looks like the qcom ones are not needed for the other devices and nothing else needs to be done.

**Comment by Kali-** [comment]
not sure if that is related to ZU issue on cm, where the button are huge

**Comment by Kali-** [comment]
nvm
was http://review.cyanogenmod.org/#/c/101228/

**Pull request merged**
