### PR TITLE
[LA.UM.5.7.r1] Add MSM8939 Kanuti platform support

### PR DESCRIPTION
**Pull request by bartcubbins**
Welcome SoMC Kanuti on Kernel 4.4 :)
This is the complete MSM8939/8936 SoC porting patchset, including SoMC Kanuti platform, Tulip board.
Contains ported required drivers and IOMMU and SPMI refactoring.

Note 1: Right now USB and MDSS needs some love.

### CODE REVIEW

**Comment by kholk** [comment]
Someone should test this on Loire platform. This PR is also touching DTs that are in common between all MSM8916-claas SoC, including 8956.

**Comment by erikcas** [comment]
nice work! will test upcoming weekend. Sadly cannot test on suzu, need a reliable dd atm

**Comment by pablomh** [comment]
Is there any way to test this diff? Using 3.10 vendor trees with the rest of code being 4.4 is the only way I could think of, but it obviously fails to boot (it stays at Sony logo and it doesn't even bootloop).

**Comment by bartcubbins** [comment]
@pablomh I think I have one idea. let me check. anyway you can boot recovery:)

**Comment by bartcubbins** [comment]
PR was rebased but some parts need some love

**Review by artem — COMMENTED** [review]
@bartcubbins  https://github.com/sonyxperiadev/kernel/blob/aosp/LA.UM.5.7.r1/drivers/power/reset/msm-poweroff.c#L50

**Comment by bartcubbins** [comment]
@ab123321 what did you mean?

**Comment by artem** [comment]
@bartcubbins Oh, sorry, I misread **!defined** as **defined**

**Comment by jerpelea** [comment]
please rebase and test loire

**Comment by bartcubbins** [comment]
@jerpelea rebased, test is on the way

**Comment by jerpelea** [comment]
tests?

**Comment by bartcubbins** [comment]
During 8 days I had this PR on suzu and any regressions

**Comment by bartcubbins** [comment]
Android 7.1

**Comment by abioteau** [comment]
@jerpelea kernel compile issue on maple since this PR has been merged

```
drivers/built-in.o: In function `lpm_suspend_enter':
cpuquiet-msm.c:(.text+0x574710): undefined reference to `msm_cpu_pm_enter_sleep'
cpuquiet-msm.c:(.text+0x574724): undefined reference to `msm_cpu_pm_enter_sleep'
drivers/built-in.o: In function `lpm_cpuidle_enter':
cpuquiet-msm.c:(.text+0x5749c0): undefined reference to `msm_cpu_pm_enter_sleep'
cpuquiet-msm.c:(.text+0x574ae8): undefined reference to `msm_cpu_pm_enter_sleep'
```

**Comment by bartcubbins** [comment]
@abioteau I will check right now and push the fix

**Comment by bartcubbins** [comment]
there is missing  ifdef for no-PSCI code which used only on msm8916 class SoCs, PR is on the way

**Comment by bartcubbins** [comment]
https://github.com/sonyxperiadev/kernel/pull/1614

**Comment by abioteau** [comment]
@bartcubbins Thanks for the speed to fix it

**Pull request merged**
