### PR TITLE
[1.3.3] rqbalance: ensure two little cores will be fired in hotplug_hmp_final_decision()

### PR DESCRIPTION
**Pull request by RyTekk**
When 4 little cores are online, get_offline_core(CLUSTER_LITTLE) will always return 0, but cpu0 won't be offline and cpu down request just be called one time. Add a function to get online cpu (of course cpu0 will be ignored) and a while loop to ensure that two little cores will be fired.

### CODE REVIEW

**Comment by jerpelea** [comment]
you forgot to add a commit message

**Comment by RyTekk** [comment]
I've just updated the comment, can you add it to the commit? Or I have to create a new one?

**Comment by jerpelea** [comment]
git commit --amend

**Comment by RyTekk** [comment]
Then git push -f and done? Do I need to do something else?

**Comment by jerpelea** [comment]
we will see :)

**Comment by RyTekk** [comment]
Done!

**Comment by kholk** [comment]
Big advice: read your code again :p

**Pull request closed without merging**
