### PR TITLE
[2.3.2.r1.4] Linux 4.9.218

### PR DESCRIPTION
**Pull request by stefanhh0**
One rejections when applying the patch:
- `drivers/scsi/sd.c` -> Manually resolved the merge conflict. In #sd_revalidate_disk initialize q->limits.io_opt with zero within the else branch.

Runs fine on yoshino/lilac.

### CODE REVIEW

**Comment by chris42** [comment]
Runs fine on Kugo/Loire.

**Comment by nathanchance** [comment]
I don't think `arch/arm64/kernel/smp.c` was resolved correctly. You're only taking part of https://git.kernel.org/stable/c/35989bb9eddedf7dda8dbadefc7dc95ccb552f4a.

I would personally revert https://github.com/sonyxperiadev/kernel/commit/30b3a6ef7572db01805b5b06087de96444e43b93 then apply https://git.kernel.org/stable/c/35989bb9eddedf7dda8dbadefc7dc95ccb552f4a fully. I believe they are fixing the same issue and upstream's solution is usually better. That is what I did for android-linux-stable and I have had no reports of issues.

**Comment by stefanhh0** [comment]
@nathanchance Thanks for your feedback and for reviewing it. Indeed I should have realized the difference.

I have fixed it as you proposed.

**Comment by ix5** [comment]
I have testers running 4.9.218 (from before @stefanhh0 force-pushed nathan's suggestion) with the [updated brcmfmac driver](https://github.com/sonyxperiadev/kernel/pull/2188) and [this sched backport](https://github.com/sonyxperiadev/kernel/pull/2224).

So far I have heard no reports of regressions.

**Comment by stefanhh0** [comment]
The latest version of this PR is running fine on yoshino/lilac.

**Comment by stefanhh0** [comment]
@jerpelea I think this this PR is now ready to be merged back. The PRs #2215 and #2221 can then just be closed.

**Pull request merged**
