### PR TITLE
Revert "mm: Increase MIN and MAX default readahead sizes"

### PR DESCRIPTION
**Pull request by Kali-**
imho, this must be set for device in userspace

### CODE REVIEW

**Comment by kholk** [comment]
This is valid for the majority of boards/devices with MSM89226/8974 and higher.
Special exceptions can be made in userspace just normally... devices which MAY need a different value can be the worst 8226 ones with very low RAM, such as Eagle and Seagull.

Also, this commit is effective on "external memory" as well (such as sd cards), which would require other lines to execute in userspace (android-speaking: init.rc), hence raising boot time.

**Comment by humberos** [comment]
So I think we can remove readahead handler from init.[platform].rc

**Comment by humberos** [comment]
I mean,
https://github.com/sonyxperiadev/device-sony-shinano/blob/master/rootdir/init.shinano.rc#L99-L101

**Comment by Tommy-Geenexus** [comment]
@kholk

https://github.com/Tommy-Geenexus/android_kernel_sony_msm8994_suzuran_5.x/commit/15ab1c0a58df12146340493f8153ac672dbfe8a3

The readahead is settled too high. Anything above 128 kbytes causes performance regressions, as described in above commit and confirmed by my testing experience on various devices.

**Pull request merged**
