### PR TITLE
[DONOTMERGE]input: misc: fpc1145: remove all wake logic

### PR DESCRIPTION
**Pull request by oshmoun**
The wakelock is not needed anymore with the new hidl hal implementation.
Tested additionally with fingerprint gestures enabled, which is known to cause device crashes without the wakelock, and there were no crashes observed.

Change-Id: Ibacff4b4afb7d167191da5aef9b0b219d3a87e18

### CODE REVIEW

**Comment by oshmoun** [comment]
testing needed on all platforms for extended periods of time with fingerprint authentication enabled.

**Comment by jerpelea** [comment]
@BuzzBumbleBee @EnJens

**Comment by EnJens** [comment]
@oshmoun the irq wake removal seems a bit too much? Won't that prevent the fpc from waking up the device from sleep?

**Comment by oshmoun** [comment]
according to tests done here on kugo, that irq wake has no effect. device is unable to wake from sleep with and without it.

**Comment by jerpelea** [comment]
irq wake is tested on yoshino and confirmed working

**Pull request closed without merging**
