### PR TITLE
msm-audio: dtsi: remove double pcm2: qcom,msm-ultra-low-latency

### PR DESCRIPTION
**Pull request by alviteri**
already defined after

pcm1: qcom,msm-pcm-low-latency

Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by kholk** [comment]
Utterly wrong.
There are two ULL channels (not in all SoCs) and the device gets used only when assigned to a route.

**Comment by alviteri** [comment]
Should be declared as well https://github.com/sonyxperiadev/kernel/blob/aosp/LE.UM.2.3.2.r1.4/arch/arm64/boot/dts/qcom/msm-audio.dtsi#L649 for me this is double declared only that ... Also not sure but since 670 uses same 660-common audio look ... It's not declared double https://github.com/sonyxperiadev/kernel/blob/aosp/LE.UM.2.3.2.r1.4/arch/arm64/boot/dts/qcom/msm-audio-lpass.dtsi

**Comment by alviteri** [comment]
After this ... In 4.4 where audio works ... I can play mobile legends under ultra low latency as well (it uses noirq as default where supported)

**Comment by jerpelea** [comment]
unfortunately this is wrong because some platforms need pcm2 config
on the affected platforms you can remove the node !

**Pull request closed without merging**
