### PR TITLE
[1.33 branch] [4.11 backport] arm64: fix a migrating irq bug when hotplug cpu

### PR DESCRIPTION
**Pull request by zachariasmaladroit**
Based on the following changes mentioned in https://lkml.org/lkml/2015/9/24/136 [RFC PATCH v6 0/3] arm/arm64: fix a migrating irq bug when hotplug cpu

build-tested on 1.3.3 sonyxperiadev AOSP branch, lightly tested on Sony Stock kernel 32.3.A.2.33 branch based kernel (sumire single-SIM)

It includes one additional change mentioned at the linux-yocto mailing list that is supposed to make shutdown behavior and hotplug more reliable: https://lists.yoctoproject.org/pipermail/linux-yocto/2016-October/005977.html

### CODE REVIEW

**Comment by zachariasmaladroit** [comment]
CC: @kholk , @dani020110 , @rancidfrog

**Comment by kholk** [comment]
This is probably the most dangerous patchset seen in the story of this repository. There are points on which I disagree, but I will not say anything for now to make you think with your minds.

This needs REALLY extensive testing on ALL platforms and ALL DEVICES.

**Comment by danielgusvt** [comment]
@zachariasmaladroit I could test this on tulip
Is there anything I could do to help?

**Comment by kholk** [comment]
Use it. Check hotplugging status, deep sleep status, overall system efficiency... That's what should be tested. 

Of course, the kernel should not panic :p

**Comment by rancidfrog** [comment]
Just flashed new build with this patch and I still get `[  855.889495] IRQ35 no longer affine to CPU2`
No panic yet, but haven't tested wifi yet, which is where I have been getting reboots consistently lately.
Dmesg does not work so rebooted phone and got last_kmsg from bugreport:
- https://paste.ee/r/XMyG0/0

Will test for panics and update.

**Comment by danielgusvt** [comment]
@rancidfrog 
https://github.com/zachariasmaladroit/kernel/blob/a64c4bf27decad12a4211ab7047071ab1efc0124/arch/arm/kernel/irq.c#L186
https://github.com/zachariasmaladroit/kernel/blob/a64c4bf27decad12a4211ab7047071ab1efc0124/kernel/irq/cpuhotplug.c#L77

**Comment by rancidfrog** [comment]
I see.
Will this commit merged, Which is also merged in newer kernels, help stop flooding logs?
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/commit/kernel/irq/cpuhotplug.c?id=58c9c87ca9dca99f269267f5aadcd051fef1637b | https://github.com/torvalds/linux/commit/58c9c87ca9dca99f269267f5aadcd051fef1637b  

If that is the case can we add it to PR, too?
EDIT: After making sure PR works, of course.

**Comment by kholk** [comment]
For this, I first need to check why we don't actually have/need a function to set the affinity in our irqchip driver.

**Comment by zachariasmaladroit** [comment]
@kholk seems like there's quite some recent work getting into those areas & the following is missing from this PR:

https://patchwork.kernel.org/patch/9630325/ Schedule affinity_notify work while migrating IRQs during hot plug

>irq_do_set_affinity() last argument differentiates whether notify work 
need to queued for this irq or not.  So that we can avoid double queuing of notify
in the irq_set_affinity_locked() path.


related irq_do_set_affinity() change from 2012:

https://lists.gt.net/linux/kernel/1541578 [tip:irq/core] genirq: Introduce irq_do_set_affinity() to reduce duplicated code

**Comment by kholk** [comment]
That's even more messy.
If those patches are that much bleeding edge it's not wise to implement.

**Comment by rancidfrog** [comment]
So, does not seem to stop Panics,
With patch I still get reboots while on wifi:
- https://paste.ee/r/ZLNZS/0
- https://paste.ee/r/IUTxH/0

There is also still an issue with `msm-dwc3 msm_dwc3: get_prop_proprietary_charger: read D+ voltage fail`
Deep sleep seems to work though:

**Comment by rancidfrog** [comment]
```
[ 8243.255207] Error: returning -512 value
[ 8243.286910] ------------[ cut here ]------------
[ 8243.286916] WARNING: at ../../../../../../kernel/sony/msm/kernel/irq/manage.c:457 0xc0078328()
[ 8243.286919] Unbalanced enable for IRQ 61
[ 8243.287008] ---[ end trace 1b8cf00ee95e3a51 ]---
[ 8243.388216] mmc1: mmc_set_auto_bkops: error in setting auto bkops to 1 (-74)
[ 8243.388221] mmc1: mmc_init_card: Failed to enable auto-bkops: err: -74
[ 8245.335029] Error: returning -512 value
[ 6251.455324] __qpnpint_handle_irq: 334 triggered [0x0, 0x61,0x1] qpnp_rtc_alarm
[ 6251.536290] mmc1: mmc_set_auto_bkops: error in setting auto bkops to 1 (-74)
[ 6251.536295] mmc1: mmc_init_card: Failed to enable auto-bkops: err: -74
[ 6252.105310] Error: returning -512 value
[ 6252.134679] __qpnpint_handle_irq: 339 triggered [0x0, 0x34,0x4] qpnp_adc_tm_low_interrupt
[ 6252.226369] mmc1: mmc_set_auto_bkops: error in setting auto bkops to 1 (-74)
[ 6252.226379] mmc1: mmc_init_card: Failed to enable auto-bkops: err: -74
[ 6252.375267] Error: returning -512 value
 5984.395184] __qpnpint_handle_irq: 292 triggered [0x0, 0x08,0x0] qpnp_kpdpwr_status
[ 5984.491513] mmc1: mmc_set_auto_bkops: error in setting auto bkops to 1 (-74)
[ 5984.491527] mmc1: mmc_init_card: Failed to enable auto-bkops: err: -74
```
And crash caused by
```
[13697.885458] mdss_mdp_pipe_fetch_halt: 0xc028d3ac: pipe6 is not idle. xin_id=2
[13697.891628] mdss_mdp_pipe_fetch_halt: 0xc028d3ac: pipe7 is not idle. xin_id=10
[13697.915732] mdss_mdp_wait_for_xin_halt: VBIF client 10 not halting. TIMEDOUT.
[13697.921919] mdss_mdp_overlay_cleanup: performing recovery sequence for fb0
[13699.356145] msm_iommu_v1: Timed out waiting for TLB SYNC to complete for mdp_iommu (client: mdp_ns)
[13699.364151] mdss_iommu_tlb_timeout_notify: cb for TLB SYNC timeout. Dumping XLOG's
```

- https://paste.ee/r/YnrJC/0

**Comment by kholk** [comment]
This crash is not relevant to this PR.

**Comment by zachariasmaladroit** [comment]
@kholk I went pretty deep down the rabbit hole and several components would need updating:

hotplug, irqchip, kernel/cpu, rcu, etc.

it seems it's a multi-layered issue and not easily "fixed" (if at all in the short-term)

**Comment by kholk** [comment]
Usually, when someone tries to push a backport of commits from any newer kernel version, I start writing a poem about how much a bad idea it can be and how many "hidden" dependencies (commits) would be necessary to also port. 

This time, I said that I didn't want to say anything to make you think with your mind...... 
.... And I'm glad you continued your research as a good developer would do!

Now, see how many patches would need to get backported and give a conclusion. Would them be just "many" or "too many"? (I don't actually know, on this specific case)

If it's not too many, then maybe it's worth giving it a shot, as soon as those won't break 8994 :D

**Pull request closed without merging**
