### PR TITLE
[TEST][1.3.3] MSM8974: Second qcrypto engine

### PR DESCRIPTION
**Pull request by alviteri**
[    4.387660] qcrypto fd440000.qcom,qcrypto: Qualcomm Crypto 5.1.0 device found @0xfd440000
[    4.395284] qcrypto fd440000.qcom,qcrypto: CE device = 0x0
[    4.428236] qcrypto fd440000.qcom,qcrypto: qcrypto-ecb-aes
[    4.433619] qcrypto fd440000.qcom,qcrypto: qcrypto-cbc-aes
[    4.439035] qcrypto fd440000.qcom,qcrypto: qcrypto-ctr-aes
[    4.444528] qcrypto fd440000.qcom,qcrypto: qcrypto-ecb-des
[    4.449968] qcrypto fd440000.qcom,qcrypto: qcrypto-cbc-des
[    4.455466] qcrypto fd440000.qcom,qcrypto: qcrypto-ecb-3des
[    4.460993] qcrypto fd440000.qcom,qcrypto: qcrypto-cbc-3des
[    4.466594] qcrypto fd440000.qcom,qcrypto: qcrypto-xts-aes
[    4.472042] qcrypto fd440000.qcom,qcrypto: qcrypto-sha1
[    4.477231] qcrypto fd440000.qcom,qcrypto: qcrypto-sha256
[    4.482631] qcrypto fd440000.qcom,qcrypto: qcrypto-aead-hmac-sha1-cbc-aes
[    4.489374] qcrypto fd440000.qcom,qcrypto: qcrypto-aead-hmac-sha1-cbc-des
[    4.496216] qcrypto fd440000.qcom,qcrypto: qcrypto-aead-hmac-sha1-cbc-3des
[    4.503034] qcrypto fd440000.qcom,qcrypto: qcrypto-aead-hmac-sha256-cbc-aes
[    4.509946] qcrypto fd440000.qcom,qcrypto: qcrypto-aead-hmac-sha256-cbc-des
[    4.516917] qcrypto fd440000.qcom,qcrypto: qcrypto-aead-hmac-sha256-cbc-3des
[    4.523937] qcrypto fd440000.qcom,qcrypto: qcrypto-hmac-sha1
[    4.529560] qcrypto fd440000.qcom,qcrypto: qcrypto-hmac-sha256
[    4.535400] qcrypto fd440000.qcom,qcrypto: qcrypto-aes-ccm
[    4.540847] qcrypto fd440000.qcom,qcrypto: qcrypto-rfc4309-aes-ccm
[    4.546927] qcrypto: FIPS140-2 Known Answer Tests: Skipped
[    4.561694] qcrypto fd440000.qcom,qcrypto1: Qualcomm Crypto 5.1.0 device found @0xfd440000
[    4.569303] qcrypto fd440000.qcom,qcrypto1: CE device = 0x1

### CODE REVIEW

**Comment by alviteri** [comment]
ping @humberos @erikcas @rcstar6696

**Comment by rcstar6696** [comment]
Okay i will test it now

**Comment by alviteri** [comment]
see if there are random reboots...... after unplug USB cable

**Comment by rcstar6696** [comment]
All looks okay here on my devices :)  castor_windy and sirius

**Comment by alviteri** [comment]
ok @rcstar6696 test for a while .... and please report if there are reboots after unplug USB cable

**Pull request merged**
