### PR TITLE
[UM.5.5.r1][DO NOT MERGE] drivers: msm: gpu updates

### PR DESCRIPTION
**Pull request by humberos**
Updates for GPU driver

### CODE REVIEW

**Comment by humberos** [comment]
ping @kholk

**Comment by humberos** [comment]
Our kernel:
[    6.090303] QSEECOM: qseecom_load_app: App (keymaste) does'nt exist, loading apps for first time
[    6.165895] scm_call failed: func id 0x72000101, ret: -2, syscall returns: 0xffffffffffffffda, 0x0, 0x0
[    6.165909] QSEECOM: qseecom_load_app: scm_call to load app failed
[    6.165922] QSEECOM: qseecom_ioctl: failed load_app request: -22

[    6.187740] kgsl kgsl-3d0: |_load_regfile| request firmware failed -11, a530v3_seq.fw2

-----------------------------------------------------------------------
Stock kernel:
<4>[    8.182781] QSEECOM: qseecom_load_app: App (keymaste) does'nt exist, loading apps for first time
<3>[    8.237539] scm_call failed: func id 0x72000101, ret: -2, syscall returns: 0xffffffffffffffda, 0x0, 0x0
<3>[    8.237558] QSEECOM: qseecom_load_app: scm_call to load app failed
<3>[    8.237575] QSEECOM: qseecom_ioctl: failed load_app request: -22

<3>[    8.279196] kgsl: _read_fw2_block_header: GPMU unknown header ID 6

**Comment by kholk** [comment]
Well, I actually have the former error on my Dora RoW, not the request firmware failure. Which device is that?

**Comment by humberos** [comment]
my device is kagura!
what error are you getting on dora ?

**Comment by kholk** [comment]
on Dora: kgsl: _read_fw2_block_header: GPMU unknown header ID 6

**Comment by humberos** [comment]
well, so I think it is ok on dora since this missed header error is expected. I mean it is present in stock logs.
I will check dora and kagura dts and try to figure out why kagura doesn't load the FW.

**Comment by kholk** [comment]
Makes sense........... absolutely. But maybe we should try to also update the adreno firmwares.

**Pull request closed without merging**
