### PR TITLE
kitakami: defconfig cleanup

### PR DESCRIPTION
**Pull request by AndroPlus-org**
Clearpad is not needed for karin and karin_windy

### CODE REVIEW

**Comment by jerpelea** [comment]
please remove also other TS drivers and ready my previous comment

**Comment by AndroPlus-org** [comment]
OK, I edited more, but what is "touc screen drivers"?

 CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_RMI_DEV_v21=y
 CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_FW_UPDATE_v21=y
 CONFIG_TOUCHSCREEN_ATMEL_MAXTOUCH_TS=y
 CONFIG_TOUCHSCREEN_GEN_VKEYS=y
 CONFIG_SECURE_TOUCH=y
are in defconfig for stock kernel.

**Comment by jerpelea** [comment]
you can remove those TS drivers since they are not present on device

**Comment by AndroPlus-org** [comment]
I removed them, is it OK now?

**Comment by kholk** [comment]
Looks OK.

**Pull request merged**
