### PR TITLE
ARM64: config: suzuran: Enable Wlan BCM4356

### PR DESCRIPTION
**Pull request by humberos**
This change is based on platform branch.

Signed-off-by: Humberto Borba humberos@gmail.com
Change-Id: Id3eebcc7f054aaa8618f9c402fec8a6aee7767ec

### CODE REVIEW

**Comment by humberos** [comment]
It is not present on copy-left tree. So 1.1 kernel should be updated.

**Comment by humberos** [comment]
I am not sure about this.
@kholk , @jerpelea : Do you know if suzuran uses BCMDHD (interface PCIE) ?

**Comment by kholk** [comment]
Whole Kitakami should have a combo Broadcom chip connected to PCI-E lanes.

**Comment by humberos** [comment]
Ok! Thank you!
Reopened.

**Comment by jerpelea** [comment]
check them all on all branches !

**Comment by humberos** [comment]
did you mean 1.1 and 1.2.2 trees, right.
If yes then it is ok now.

1.2.1 will be abandoned, right?

**Pull request merged**
