### PR TITLE
[6.4.r1] Migrate MSM8956 and Loire to mainline style Common Clock Framework

### PR DESCRIPTION
**Pull request by kholk**
This patchset introduces completely new drivers (and one adapted) for the clock controllers in the MSM8976/8956 SoCs rewritten for the mainline Common Clock Framework.
This also switches the SoC and all the supported devices to the new framework and brings _loads_ of improvements in both device performance and battery life.

The current patchset has been tested on:
SoMC Loire Suzu - @kholk 
SoMC Loire Kugo - @kholk @oshmoun 

Another small step for a driver.... another giant leap for ........ (your_choice_here)
 :)))))))))))

### CODE REVIEW

**Comment by oshmoun** [comment]
smooth sailing so far on kugo, amazing work!
but can we please add a config for enabling corruption? it was a nice feature :D

**Comment by kholk** [comment]
Nah, I don't like the display initial corruption feature anymore... better keep it FIXED :)))))

**Comment by bartcubbins** [comment]
Suzu test is on the way:)

**Comment by kholk** [comment]
The PR has been forcepushed to revert the whole MSM8976 support from downstream and only keep the mainline one.

This will positively affect Tone and Yoshino.
Please, Tone and Yoshino users, test this PR.

**Pull request merged**
