### PR TITLE
prima: update to LA.BR.1.3.3_rb2.28

### PR DESCRIPTION
**Pull request by alviteri**
Signed-off-by: David Viteri <davidteri91@gmail.com>

to test
ping @erikcas @pablomh

### CODE REVIEW

**Comment by erikcas** [comment]
David, currently not able to test on a device with prima

**Comment by bartcubbins** [comment]
wifi works fine on tulip

**Comment by alviteri** [comment]
Have you tried 5Ghz connection ?? I can't test it

**Comment by bartcubbins** [comment]
tomorrow I'm test it. 2.4Ghz works fine.

**Comment by alviteri** [comment]
Contact me on hangouts then we will see what we can do

**Comment by mcgi5sr2** [comment]
doesn't break anything on Aries 2ghz and 5ghz alright

**Comment by alviteri** [comment]
in fact this is needed by qcom wifi chips .... aries is bcm one

**Comment by kholk** [comment]
You should try the latest version for 3.10, branch 1.3.9, instead.
The 1.3.9 branch is for nougat and we are actually running that one. Moreover, we have many updates on our branch that puts it more or less in line with the new one.


Just... Try 1.3.9

**Comment by alviteri** [comment]
I can't see 1.3.9 in CAF ...

**Comment by alviteri** [comment]
Anyway remember this is M kernel

**Comment by erikcas** [comment]
@kholk isn't it 1.3.6?

**Comment by bartcubbins** [comment]
@alviteri 5ghz works only after sim is inserted. tested on tulip

**Comment by alviteri** [comment]
@bartcubbins that's is normal (not normal at all 100% in aosp) bcm and qcom seem have same problem

**Pull request merged**
