### PR TITLE
[7.1.r1] Tama LMh fix

### PR DESCRIPTION
**Pull request by voidanix**
Also resolve some section mismatches that spits warnings.

### CODE REVIEW

**Comment by MarijnS95** [comment]
Addresses don't seem to be adjusted at all, just the node name? The reg addresses are only being lowercased.

**Comment by voidanix** [comment]
> Addresses don't seem to be adjusted at all, just the node name?

Yes, I just wanted a rename in 0b4daf62226abfc0fd5794ce0859f88f101ee604. Totally butchered the terminology to fit into 50 chars. :|

**Comment by MarijnS95** [comment]
Just be careful that trimming the title _does not_ change its meaning, otherwise a self-imposed char limit serves no purpose at all.

**Comment by ShujathMohd** [comment]
I am no expert here, just tested the patch and here are the results 
Antutu results without this patch

without

With the patch 
with

**Comment by ShujathMohd** [comment]
@bartcubbins. can you please review

**Comment by bartcubbins** [comment]
This change corresponds to SDM845 and restores the LMH DCVS behavior in accordance with what is in the original 4.9 kernel

**Pull request merged**
