### PR TITLE
Fix kernel compilation for honami.

### PR DESCRIPTION
**Pull request by Diewi**
Without these changes, there are missing symbols. Thus, the compilation for Z1 fails. This commit fixes these issues.

Thanks for the comment in the previous pull request! The (depends IPV6 || IPV6=no) were really nonsense. I overlooked the obvious...

Nevertheless, there are several occurrences of these lines in the net/*/Kconfig files. Maybe they should be removed as well.

### CODE REVIEW

**Comment by alviteri** [comment]
@Diewi honami kernel fails? because my main device on aosp is honami and n is building without any sort of problems ........

**Comment by Diewi** [comment]
Wait... did I pick the wrong branch?  It fails for me if i try to build for MM. Verfied yesterday evening without this commit.

**Comment by alviteri** [comment]
this branch is for N ..... the M branch is aosp/LA.BF64.1.2.2_rb4.7

**Comment by alviteri** [comment]
http://developer.sonymobile.com/knowledge-base/open-source/open-devices/aosp-build-instructions/

**Comment by Kali-** [comment]
check what u did as IPV6 is already set

**Comment by Diewi** [comment]
Ok, thanks for your comments. This commit is obvious nonsense, downstream issue. Sorry for wasting your time! Closing.

**Pull request closed without merging**
