### PR TITLE
defconfig: nile/yoshino: enable CONFIG_HZ_1000 instead of CONFIG_HZ_100

### PR DESCRIPTION
**Pull request by pablomh**
This way all the supported devices will run with CONFIG_HZ_1000.

### CODE REVIEW

**Comment by pablomh** [comment]
I will be running this diff on pioneer (nile platform) and will report any regression, but some yoshino tests will be needed as well.

**Comment by bartcubbins** [comment]
I think it's better to separate it into two commits, one for Nile and another one for Yoshino

**Comment by oshmoun** [comment]
maybe also completely switch to NO_HZ
seems possible judging by the defconfig of op5(t)
https://github.com/omnirom/android_kernel_oneplus_msm8998/blob/android-8.1/arch/arm64/configs/omni_oneplus5_defconfig#L82

**Review by kholk — APPROVED** [review]

**Comment by kholk** [comment]
I approve, but separate the commits!
Make one for all Yoshino and one for all Nile!

**Comment by nathanchance** [comment]
@oshmoun It's not full NO_HZ though: `# CONFIG_NO_HZ_FULL is not set`

 You still specify a HZ value: https://github.com/omnirom/android_kernel_oneplus_msm8998/blob/android-8.1/arch/arm64/configs/omni_oneplus5_defconfig#L422-L426

`CONFIG_NO_HZ` is already set in these configs.

**Comment by oshmoun** [comment]
ah thanks, missed that.
Then not completely, but still partially might be worth investigating, i.e with CONFIG_NO_HZ_IDLE

**Comment by alviteri** [comment]
https://android.googlesource.com/kernel/msm/+/android-msm-wahoo-4.4-oreo-m4/arch/arm64/configs/wahoo_defconfig#65

Shouldn't be better keep wahoo value ?

**Comment by nathanchance** [comment]
@alviteri I've been using `CONFIG_HZ=1000` for a few months now with no regressions on the Pixel 2 XL. Google stated they have been experimenting with it and found positive results: https://source.android.com/devices/tech/debug/jank_jitter#long_threads

**Comment by pablomh** [comment]
I'll separate them in a following PR.

**Comment by pablomh** [comment]
I've created https://github.com/sonyxperiadev/kernel/pull/1665 and https://github.com/sonyxperiadev/kernel/pull/1666 to that effect.

**Pull request closed without merging**
