### PR TITLE
[2.3.2.r1.4] Linux 4.9.210

### PR DESCRIPTION
**Pull request by nathanchance**

### CODE REVIEW

**Comment by stefanhh0** [comment]
Tried that one today on `yoshino/lilac` and resulted in a boot-loop, system gets not past the sony-logo. When just changing back the bootimage using `4.9.194-g4b7aa31b03b0` instead it then works fine again.  Unfortunately I don't have the time now to `git bisect` now because I've to go to work. Maybe on the weekend.

**Comment by stefanhh0** [comment]
Starting with Linux 4.9.206 the phone is trapped in a boot-loop.
 
<details><summary>git bisect result</summary>
<p>

```
stefan@mars:~/android/source/kernel/sony/msm-4.9/kernel$ git bisect bad 
08ca05f71253b0d29e9bdc121cae8c1192849d97 is the first bad commit
commit 08ca05f71253b0d29e9bdc121cae8c1192849d97
Author: Nathan Chancellor <natechancellor@gmail.com>
Date:   Thu Jan 16 13:08:52 2020 -0700

    treewide: Linux 4.9.206
    
    source kernel.org
    https://cdn.kernel.org/pub/linux/kernel/v4.x/incr/patch-4.9.205-206.xz
    
    Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

 Documentation/hid/uhid.txt                         |  2 +-
 Makefile                                           |  2 +-
 arch/arm/Kconfig.debug                             | 28 ++++++------
 arch/arm/boot/dts/imx53-voipac-dmm-668.dtsi        |  8 +---
 arch/arm/mach-ks8695/board-acs5k.c                 |  2 +-
 arch/arm64/kernel/head.S                           | 26 +++++++++++
 arch/arm64/kernel/smp.c                            |  6 +++
 arch/microblaze/Makefile                           | 12 ++---
 arch/microblaze/boot/Makefile                      |  4 --
 arch/openrisc/kernel/entry.S                       |  2 +-
 arch/openrisc/kernel/head.S                        |  2 +-
 arch/powerpc/boot/dts/bamboo.dts                   |  4 +-
 arch/powerpc/include/asm/cputable.h                |  1 +
 arch/powerpc/include/asm/reg.h                     |  2 +
 arch/powerpc/kernel/cputable.c                     | 10 +++--
 arch/powerpc/kernel/prom.c                         |  6 +--
 arch/powerpc/mm/fault.c                            | 17 +++----
 arch/powerpc/mm/ppc_mmu_32.c                       |  4 +-
 arch/powerpc/platforms/83xx/misc.c                 | 17 +++++++
 arch/powerpc/platforms/powernv/eeh-powernv.c       |  8 ++--
 arch/powerpc/platforms/powernv/pci-ioda.c          |  4 +-
 arch/powerpc/platforms/powernv/pci.c               |  4 +-
 arch/powerpc/platforms/pseries/dlpar.c             |  4 ++
 arch/powerpc/platforms/pseries/hotplug-memory.c    |  1 +
 arch/powerpc/xmon/xmon.c                           |  2 +-
 arch/s390/kvm/kvm-s390.c                           | 17 +++++--
 arch/s390/mm/gup.c                                 |  9 ++--
 arch/um/Kconfig.debug                              |  1 +
 arch/x86/mm/gup.c                                  |  9 +++-
 crypto/crypto_user.c                               | 37 ++++++++-------
 drivers/acpi/acpi_lpss.c                           |  7 +--
 drivers/acpi/apei/ghes.c                           | 30 ++++++-------
 drivers/base/platform.c                            |  3 ++
 drivers/block/drbd/drbd_main.c                     |  1 -
 drivers/block/drbd/drbd_nl.c                       | 43 +++++++++++++-----
 drivers/block/drbd/drbd_receiver.c                 | 52 ++++++++++++++++++++--
 drivers/block/drbd/drbd_state.h                    |  2 +-
 drivers/char/hw_random/stm32-rng.c                 |  8 ++++
 drivers/clk/at91/clk-main.c                        |  7 ++-
 drivers/clk/at91/sckc.c                            | 20 +++++++--
 drivers/clk/samsung/clk-exynos5420.c               |  6 +++
 drivers/crypto/mxc-scc.c                           | 12 ++---
 drivers/hid/hid-core.c                             | 51 ++++++++++++++++++---
 drivers/hid/intel-ish-hid/ishtp-hid.c              |  2 +-
 drivers/infiniband/hw/qib/qib_sdma.c               |  4 +-
 drivers/infiniband/ulp/srp/ib_srp.c                |  1 +
 drivers/input/serio/gscps2.c                       |  4 +-
 drivers/input/serio/hp_sdc.c                       |  4 +-
 drivers/iommu/amd_iommu.c                          |  8 +++-
 drivers/md/dm-flakey.c                             | 33 +++++++++-----
 drivers/media/platform/atmel/atmel-isc.c           |  8 +++-
 drivers/media/v4l2-core/v4l2-ctrls.c               |  1 +
 drivers/misc/mei/bus.c                             |  9 ++--
 drivers/mtd/mtdcore.h                              |  2 +-
 drivers/mtd/mtdpart.c                              | 35 ++++++++++++---
 drivers/mtd/nand/sunxi_nand.c                      |  2 +-
 drivers/mtd/ubi/build.c                            |  2 +-
 drivers/mtd/ubi/kapi.c                             |  2 +-
 drivers/net/can/c_can/c_can.c                      | 26 +++++++++++
 drivers/net/can/usb/peak_usb/pcan_usb.c            | 15 ++++---
 drivers/net/dsa/bcm_sf2.c                          |  7 ++-
 drivers/net/ethernet/atheros/atl1e/atl1e_main.c    |  4 +-
 drivers/net/ethernet/cadence/macb.c                | 14 +++---
 drivers/net/ethernet/freescale/fec_main.c          | 13 +++++-
 drivers/net/ethernet/mellanox/mlx5/core/main.c     |  8 ++--
 drivers/net/ethernet/sfc/ef10.c                    | 29 ++++++++----
 drivers/net/ethernet/stmicro/stmmac/dwmac-sunxi.c  |  4 +-
 drivers/net/macvlan.c                              |  3 +-
 drivers/net/slip/slip.c                            |  1 +
 drivers/net/wan/fsl_ucc_hdlc.c                     |  1 -
 drivers/net/wireless/ath/ath6kl/cfg80211.c         |  4 +-
 drivers/net/wireless/marvell/mwifiex/debugfs.c     | 14 +++---
 drivers/net/wireless/marvell/mwifiex/scan.c        | 18 ++++----
 drivers/net/wireless/realtek/rtl818x/rtl8187/dev.c |  3 +-
 drivers/pinctrl/pinctrl-xway.c                     | 39 +++++++++++-----
 drivers/pinctrl/sh-pfc/pfc-sh7264.c                |  9 +++-
 drivers/pinctrl/sh-pfc/pfc-sh7734.c                | 16 +++----
 drivers/platform/x86/hp-wmi.c                      |  6 +--
 drivers/power/avs/smartreflex.c                    |  3 +-
 drivers/pwm/core.c                                 |  1 +
 drivers/pwm/pwm-bcm-iproc.c                        |  1 +
 drivers/pwm/pwm-berlin.c                           |  1 -
 drivers/pwm/pwm-clps711x.c                         |  4 +-
 drivers/pwm/pwm-samsung.c                          |  1 -
 drivers/regulator/palmas-regulator.c               |  5 ++-
 drivers/regulator/tps65910-regulator.c             |  4 +-
 drivers/scsi/csiostor/csio_init.c                  |  2 +-
 drivers/scsi/libsas/sas_expander.c                 | 29 +++++++++++-
 drivers/scsi/lpfc/lpfc_scsi.c                      | 18 ++++++++
 drivers/scsi/qla2xxx/tcm_qla2xxx.c                 | 48 ++++----------------
 drivers/scsi/qla2xxx/tcm_qla2xxx.h                 |  3 --
 drivers/staging/rtl8192e/rtl8192e/rtl_core.c       |  5 ++-
 drivers/tty/serial/max310x.c                       |  7 +--
 drivers/usb/serial/ftdi_sio.c                      |  3 ++
 drivers/usb/serial/ftdi_sio_ids.h                  |  7 +++
 drivers/vfio/vfio_iommu_spapr_tce.c                | 10 ++---
 drivers/watchdog/meson_gxbb_wdt.c                  |  4 +-
 drivers/xen/xen-pciback/pci_stub.c                 |  3 +-
 fs/btrfs/delayed-ref.c                             |  3 --
 fs/gfs2/bmap.c                                     |  2 +
 fs/ocfs2/journal.c                                 |  6 +--
 fs/xfs/xfs_ioctl32.c                               | 40 +++++++++++++++--
 fs/xfs/xfs_rtalloc.c                               |  4 +-
 include/linux/genalloc.h                           | 13 +++---
 include/linux/gpio/consumer.h                      |  2 +-
 include/linux/netdevice.h                          |  2 +-
 include/linux/reset-controller.h                   |  2 +-
 include/linux/swap.h                               |  6 ---
 include/net/sctp/structs.h                         |  3 ++
 include/net/sock.h                                 |  2 +-
 lib/genalloc.c                                     | 25 ++++++-----
 mm/internal.h                                      | 10 +++++
 net/core/neighbour.c                               | 13 ++++--
 net/core/net_namespace.c                           |  3 +-
 net/core/sock.c                                    |  2 +-
 net/decnet/dn_dev.c                                |  2 +-
 net/ipv4/ip_tunnel.c                               |  8 +++-
 net/mac80211/sta_info.c                            |  3 +-
 net/openvswitch/datapath.c                         | 17 +++++--
 net/sched/sch_mq.c                                 |  3 +-
 net/sched/sch_mqprio.c                             |  4 +-
 net/sched/sch_multiq.c                             |  2 +-
 net/sched/sch_prio.c                               |  2 +-
 net/sctp/associola.c                               |  1 +
 net/sctp/endpointola.c                             |  1 +
 net/sctp/input.c                                   |  4 +-
 net/sctp/transport.c                               |  3 +-
 net/tipc/link.c                                    |  2 +-
 net/tipc/netlink_compat.c                          |  8 +++-
 net/vmw_vsock/af_vsock.c                           |  7 ++-
 scripts/gdb/linux/symbols.py                       |  3 +-
 sound/soc/kirkwood/kirkwood-i2s.c                  |  8 ++--
 132 files changed, 827 insertions(+), 392 deletions(-)
```
```
stefan@mars:~/android/source/kernel/sony/msm-4.9/kernel$ git bisect log
git bisect start
# bad: [a4710cec47b4bcce2663805e9f6e50e9622fce8f] treewide: Linux 4.9.210
git bisect bad a4710cec47b4bcce2663805e9f6e50e9622fce8f
# good: [4b7aa31b03b01f72f2f9d33bf040176f9cc8f6e3] Merge pull request #2149 from vknecht/aosp/LE.UM.2.3.2.r1.4-morefixes-3
git bisect good 4b7aa31b03b01f72f2f9d33bf040176f9cc8f6e3
# good: [3ebfc840f354c73e8254f7e1350665e4c09a61a8] treewide: Linux 4.9.201
git bisect good 3ebfc840f354c73e8254f7e1350665e4c09a61a8
# good: [76782f848b2ad831f7c48674e7794da5e0ca339b] treewide: Linux 4.9.205
git bisect good 76782f848b2ad831f7c48674e7794da5e0ca339b
# bad: [08dc8ed24ff46f2b1e5b816b79a4c6643738aaa1] treewide: Linux 4.9.207
git bisect bad 08dc8ed24ff46f2b1e5b816b79a4c6643738aaa1
# bad: [08ca05f71253b0d29e9bdc121cae8c1192849d97] treewide: Linux 4.9.206
git bisect bad 08ca05f71253b0d29e9bdc121cae8c1192849d97
# first bad commit: [08ca05f71253b0d29e9bdc121cae8c1192849d97] treewide: Linux 4.9.206
```

</p>
</details>

**Files:**
[dmesg-ramoops-0.log](https://github.com/sonyxperiadev/kernel/files/4078309/dmesg-ramoops-0.log)
[dmesg-ramoops-1.log](https://github.com/sonyxperiadev/kernel/files/4078310/dmesg-ramoops-1.log)

**Comment by nathanchance** [comment]
@stefanhh0 thanks for testing! I do not really see anything conclusive in the logs. Here is a branch with 4.9.206 cherry-picked. Make sure that the kernel boots and works at `eef80b2d53781794c98c961fc529bcad7f04281a` and does not at `e587d6171dc6d1af06ede5ed2af7a7c2abe85e4f` then run a `git bisect` on those two commits.

https://github.com/nathanchance/kernel/commits/stable-4.9-investigation

**Comment by stefanhh0** [comment]
Found the commit with that the boot-loop occurs:
nathanchance/kernel@f2e3b9f98a920ef479cc542c2432ea1f5e2d9a98

<details><summary>git bisect result</summary>
<p>

```
stefan@mars:~/android/source/kernel/sony/msm-4.9/kernel$ git bisect good
f2e3b9f98a920ef479cc542c2432ea1f5e2d9a98 is the first bad commit
commit f2e3b9f98a920ef479cc542c2432ea1f5e2d9a98
Author: Huang Shijie <sjhuang@iluvatar.ai>
Date:   Thu Jan 3 15:26:51 2019 -0800

    lib/genalloc.c: use vzalloc_node() to allocate the bitmap
    
    [ Upstream commit 6862d2fc81859f88c1f3f660886427893f2b4f3f ]
    
    Some devices may have big memory on chip, such as over 1G.  In some
    cases, the nbytes maybe bigger then 4M which is the bounday of the
    memory buddy system (4K default).
    
    So use vzalloc_node() to allocate the bitmap.  Also use vfree to free
    it.
    
    Link: http://lkml.kernel.org/r/20181225015701.6289-1-sjhuang@iluvatar.ai
    Signed-off-by: Huang Shijie <sjhuang@iluvatar.ai>
    Reviewed-by: Andrew Morton <akpm@linux-foundation.org>
    Cc: Alexey Skidanov <alexey.skidanov@intel.com>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
    Signed-off-by: Sasha Levin <sashal@kernel.org>
    Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

 lib/genalloc.c | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)
```
```
stefan@mars:~/android/source/kernel/sony/msm-4.9/kernel$ git bisect log 
git bisect start
# good: [eef80b2d53781794c98c961fc529bcad7f04281a] treewide: Linux 4.9.205
git bisect good eef80b2d53781794c98c961fc529bcad7f04281a
# bad: [e587d6171dc6d1af06ede5ed2af7a7c2abe85e4f] Linux 4.9.206
git bisect bad e587d6171dc6d1af06ede5ed2af7a7c2abe85e4f
# good: [2aa2940df744f36caa29e5d74876ebb3333ba66d] vfio/spapr_tce: Get rid of possible infinite loop
git bisect good 2aa2940df744f36caa29e5d74876ebb3333ba66d
# bad: [6d712ddfdc41e82bc6c4aebccc051ade6fb10ad1] tipc: fix skb may be leaky in tipc_link_input
git bisect bad 6d712ddfdc41e82bc6c4aebccc051ade6fb10ad1
# good: [20c75ea1418bd8048e9d6357afb3faa217e794fe] atl1e: checking the status of atl1e_write_phy_reg
git bisect good 20c75ea1418bd8048e9d6357afb3faa217e794fe
# bad: [e02f63a8005feab8bb6b814757cf4b1df9641bc0] lib/genalloc.c: include vmalloc.h
git bisect bad e02f63a8005feab8bb6b814757cf4b1df9641bc0
# good: [8291662a71811d65d3684ea7b8e587736dde4524] vmscan: return NODE_RECLAIM_NOSCAN in node_reclaim() when CONFIG_NUMA is n
git bisect good 8291662a71811d65d3684ea7b8e587736dde4524
# bad: [f2e3b9f98a920ef479cc542c2432ea1f5e2d9a98] lib/genalloc.c: use vzalloc_node() to allocate the bitmap
git bisect bad f2e3b9f98a920ef479cc542c2432ea1f5e2d9a98
# good: [6e1d5fab30f8253a7d9e157e173f57436142329d] lib/genalloc.c: fix allocation of aligned buffer from non-aligned chunk
git bisect good 6e1d5fab30f8253a7d9e157e173f57436142329d
# first bad commit: [f2e3b9f98a920ef479cc542c2432ea1f5e2d9a98] lib/genalloc.c: use vzalloc_node() to allocate the bitmap
```
</p>
</details>

**Comment by stefanhh0** [comment]
With the reverted commit: nathanchance/kernel@f2e3b9f98a920ef479cc542c2432ea1f5e2d9a98
`4.9.210` boots fine, so that would be a simple workaround to get `4.9.210` merged.

**Comment by nathanchance** [comment]
Thank you for testing! I have reverted that commit.

**Pull request merged**
