### PR TITLE
re-enable ARMV8_DEPRECATED and SWP_EMULATION

### PR DESCRIPTION
**Pull request by DevriesL**
Since many applications use boost c++ library such as WeChat, in the boost library, the try_lock() function calls 'swp', if we disable SWP_EMULATION, that will cause application crash, for about boost library in WeChat, please refer to:
https://github.com/Tencent/mars/blob/master/mars/boost/smart_ptr/detail/spinlock_gcc_arm.hpp#L62

BTW: this Tencent's opensource module 'mars' not only used in the WeChat, but also used by many applications in China, so we really need swp. Here is the WeChat crash log:
********** Crash dump: **********
Build fingerprint: Sony/maple/maple:8.0.0/OPR3.170623.013/devrie12222235:userdebug/test-keys
pid: 23687, tid: 23687(main thread)  >>> com.tencent.mm <<<
signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr cf7d5388
???): Routine mars_boost::detail::spinlock::try_lock() at /mars/mars/log/../boost/smart_ptr/detail/spinlock_gcc_arm.hpp:66
(???): Routine mars_boost::shared_ptr<mars_boost::filesystem::detail::dir_itr_imp>::~shared_ptr() at /mars/mars/comm/../boost/smart_ptr/shared_ptr.hpp:336
(???): Routine mars_boost::filesystem::detail::directory_iterator_increment(mars_boost::filesystem::directory_iterator&, mars_boost::system::error_code*) at /mars/mars/comm/jni/../../boost/libs/filesystem/src/operations.cpp:2327
(???): Routine mars_boost::filesystem::directory_iterator::increment(mars_boost::system::error_code&) at /mars/mars/comm/../boost/filesystem/operations.hpp:914
???): Routine mars_boost::filesystem::directory_iterator::directory_iterator(mars_boost::filesystem::path const&) at /mars/mars/log/../boost/filesystem/operations.hpp:904
(appender_open_with_cache(TAppenderMode, std::string const&, std::string const&, char const*, char const*)+216): Routine appender_open_with_cache(TAppenderMode, std::string const&, std::string const&, char const*, char const*) at /mars/mars/log/jni/../src/appender.cc:895
Java_com_tencent_mars_xlog_Xlog_appenderOpen+424): Routine Java_com_tencent_mars_xlog_Xlog_appenderOpen at /mars/mars/log/jni/../jni/Java2C_Xlog.cc:52 (discriminator 7)
c+4293984499)

### CODE REVIEW

**Comment by jerpelea** [comment]
please push reverts to my defconfig commits, with this explanation in the commit message, instead of this change

**Comment by DevriesL** [comment]
Ok, I will start a new pull request latter.

**Comment by bartcubbins** [comment]
You can update current pull request instead of the new one

**Comment by DevriesL** [comment]
Hi @jerpelea updated, please review 😄

**Pull request merged**
