### PR TITLE
[1.2.2] Fix gcc warnings

### PR DESCRIPTION
**Pull request by humberos**
Fix gcc warnings based on Kitakami Karin and Shinano Leo compilation process.

### CODE REVIEW

**Comment by humberos** [comment]
ping @kholk
;)

**Comment by Kali-** [comment]
why still unmerged?

**Comment by jerpelea** [comment]
conflict !

**Comment by humberos** [comment]
will check it today later

**Comment by kholk** [comment]
Please, don't solve warnings on smbcharger

**Comment by humberos** [comment]
ok, just closing this PR.
I will back to work on warnings (if is the case) after big one PR (CAF and Korg).

**Pull request closed without merging**
