### PR TITLE
Add CCI HW ID driver

### PR DESCRIPTION
**Pull request by galaxyfreak**
Needed to Identify model variant. Tested on eagle.

### CODE REVIEW

**Comment by erikcas** [comment]
afaik identification does not work on eagle

**Comment by galaxyfreak** [comment]
root@eagle:/proc # cat cci_hwid_info
cat cci_hwid_info
hwid=5 projectid=1 multisim=0 bandid=0 customer=1

With this commit, it works, now we can use that baseband script again.

**Comment by erikcas** [comment]
I knew that for some time.

**Comment by galaxyfreak** [comment]
Yeah, you actually pointed out cci_hw_id is missing in unified kernel, so I added it back. no problem?

**Comment by jerpelea** [comment]
gsm works nice with aosp ril and there is no need to add this driver

**Comment by galaxyfreak** [comment]
Ehm...Eagle have many variants, how do we set a proper name and LTE/DS props then.

Or we should do another build for each of six variants?

**Comment by jerpelea** [comment]
aosp project suports only LTE devices

**Comment by galaxyfreak** [comment]
Okay then how about D2306, it's also SS LTE, just US version, Or you support International variants only?

**Comment by erikcas** [comment]
@galaxyfreak just clone the repository and add it, if you want to use it.

Personally, I intend not to add it. I opt for SS, DS and LTE versions in separate device subtrees
It is much cleaner

For DS you have to recompile the kernel anyway (offcourse, you can decide to always compile the kernel with DS support, but you always have rubbish in kernels on SS, it might break deepsleep, not tested) so building all in one is not an option anyway

**Comment by galaxyfreak** [comment]
@erikcas, Was that my question? No.
I'm asking about D2306 as thats also LTE.
I was asking jerpelea not you. Am not a fan of butchering everything to "common" repos.

**Pull request closed without merging**
