### PR TITLE
Android.mk: Fix inline kernel build on Nougat due to new build rules

### PR DESCRIPTION
**Pull request by stellirin**
ALL_PREBUILT is now forbidden

Signed-off-by: Adam Farden adam@farden.cz

### CODE REVIEW

**Comment by jerpelea** [comment]
how is this on m?

**Comment by humberos** [comment]
~~seems that it breaks "make bootimage" way~~

**Comment by humberos** [comment]
~~I mean, I can compile kernel but there is something missed in boot.img composition.~~

**Comment by alviteri** [comment]
@humberos did you try making it as ifdef

ifeq (1,$(filter 1,$(shell echo "$$(( $(PLATFORM_SDK_VERSION) >= 24 ))" )))

**Comment by alviteri** [comment]
@humberos are you refering to M or N ..?

**Comment by stellirin** [comment]
I can do `rm -rf out/ && make recoveryimage` with zero issues.

**Comment by humberos** [comment]
nevermind
you're right it is with zero issues
tested on M (Omni) and N (AOSP) and I did not find any issue.
LGTM(+2)

**Pull request merged**
