### PR TITLE
[LA.UM.6.4.r1] Bluesleep backport

### PR DESCRIPTION
**Pull request by yshui**
Backported #1985 

Seems to fix bluetooth connectivity issues for me on kugo+Oreo. Doing more tests currently.

### CODE REVIEW

**Comment by yshui** [comment]
This patch solves my bluetooth dropping issue pretty reliably, so I removed the [WIP] tag.

**Comment by ix5** [comment]
Is this needed for `2.3.2.r1.4` as well?

**Comment by yshui** [comment]
@ix5 This is back ported from `2.3.2.r1.4`.

**Comment by ix5** [comment]
@yshui ok thanks!

**Pull request merged**
