### PR TITLE
arm: DT: MSM8974: add missing clocks for WCNSS node

### PR DESCRIPTION
**Pull request by alviteri**
Signed-off-by: David Viteri davidteri91@gmail.com

### CODE REVIEW

**Comment by alviteri** [comment]
ping @kholk

**Comment by kholk** [comment]
Wrong clocks! Wrong clocks! Wrong clocks!
You've assigned the measure clock to debug and vice-versa! Fix it!

**Comment by alviteri** [comment]
@kholk 

measure-clock: https://github.com/sonyxperiadev/kernel/blob/aosp/LA.BR.1.3.3_rb2.14/arch/arm/mach-msm/clock-gcc-8974.c#L2740
debug-clock: https://github.com/sonyxperiadev/kernel/blob/aosp/LA.BR.1.3.3_rb2.14/arch/arm/mach-msm/clock-gcc-8974.c#L2552

**Comment by kholk** [comment]
Or.. Actually, no. I'm sorry, you're right. There's only naming confusion!
The debug "m" clock is dummy, clock order is OK.

Merge!

**Comment by alviteri** [comment]
:+1:

**Pull request merged**
