### PR TITLE
[UM.5.5.r1] GPU reverts

### PR DESCRIPTION
**Pull request by humberos**
GPU performs better with those reverts although we still can't see its scaling yet.

### CODE REVIEW

**Comment by kholk** [comment]
Hold these for a little....... 

Check the dmesg, I have a message about an unknown header in gpmu firmware, probably that's what produces the issue (will continue researching today).

**Comment by humberos** [comment]
yeah
[    6.651173] kgsl kgsl-3d0: |_load_regfile| request firmware failed -11, a530v3_seq.fw2
This file is present at firmware folder.

apart from this gpu issue I think that we have something broken on filesystem mouting process.

**Comment by humberos** [comment]
or filesystem driver (sdcardfs maybe ?)

**Comment by kholk** [comment]
No, I wasn't referring to this error. But that's pretty much interesting! 

We should try to update adreno firmwares.

**Comment by humberos** [comment]
I did it from latest kagura stock (.442) files....
unfortunately same result :(

**Comment by humberos** [comment]
https://github.com/sonyxperiadev/kernel/pull/1232

**Pull request closed without merging**
