### PR TITLE
[7.1.r1] Welcome, SoMC Seine! Plus, Yoshino/Nile/Ganges fixes

### PR DESCRIPTION
**Pull request by kholk**
This is a pretty big one, so let's be short. Included in this patchset:
- RPM Regulators changes: now we set Low Power mode on regulators
   when the minimum amperage for High Power mode is not reached:
   this allows for good battery savings during deep sleep
- 10nm PLL changes for Tama/Yoshino: now we are caching rates and
   not reading the hardware everytime anymore. This brings performance
   improvements, some little battery efficiency and solves some race
   conditions happening especially on SoMC Yoshino.
- DSI PHY v3.0 additions to kickstart it the right way and to solve issues
   with the PHY ULPS mode on MSM8998 SoC
- MSM8998 changes on the clock tree: MMAXI is now software voted
   in order to stop race conditions with ULPS and DSI idle power collapse
- Dirty fix (but effective) for MSM8998 kernel panic occurring on device
   shutdown and on modem SSR: now it's possible to shut down cleanly
   and won't randomly reboot the device on modem panic (will restart
   the modem, sensors and dsp cleanly, like nothing happened)
- Update BCL for PMIC5 (SoMC Kumano, SoMC Seine) to use mitigation
   level interrupts: this will produce less wakeups during deep sleep,
   while still keeping the device safe like always
- Introduced Qualcomm PM8008 support for SM6125 SoC
- Updated TRINKET (SM6125 SoC) main DTs to the latest tag
- Added SoMC Seine configuration for somc_panel display and other
  early bringup related things.
- Added SoMC Seine camera and charger configuration
- Updated QPNP-QG code, required for SoMC Seine platform
- Updated SoMC charger extensions from latest Kumano and latest
  Seine release, valid for Tama, Nile, Ganges, Kumano, Seine
- Fixed Qualcomm QuickCharge issues on supported configurations
- MSM8998 IPA/CNSS IOMMU (anoc2 crashes) issues fixed
- MSM8998 GSI configuration for DWC3 fixed

### CODE REVIEW

**Comment by stefanhh0** [comment]
Works fine on yoshino/lilac when reverting commit https://github.com/sonyxperiadev/kernel/pull/2268/commits/261c9ab889b08ab25632a07725321d524a8ea85b `arm64: DT: MSM8998: Stop setting s1bypass for ICNSS/IPA IOMMUs`

The commit causes crashes as seen in: https://github.com/sonyxperiadev/bug_tracker/issues/580#issuecomment-633286234
```
<2>[  872.965689] kernel BUG at /home/stefan/android/source/kernel/sony/msm-4.14/kernel/drivers/iommu/arm-smmu.c:1598!
[...]
<6>[  872.968692] Call trace:
<6>[  872.968778]  arm_smmu_context_fault+0x588/0x60c
<6>[  872.968828]  irq_thread_fn+0x2c/0x70
<6>[  872.968875]  irq_thread+0x13c/0x230
<6>[  872.968962]  kthread+0x118/0x128
<6>[  872.969010]  ret_from_fork+0x10/0x18
<0>[  872.969060] Code: f9400320 d000a8c1 911d4021 940640d9 (d4210000) 
```

**Comment by Haxk20** [comment]
Ganges seems to work decently so far. It doesnt burst into flames and i havent noticed anything broken so far.

**Comment by stefanhh0** [comment]
Also tested the full PR, now seeing a crash coming that I haven't seen on my previous test (When writing the comment for https://github.com/sonyxperiadev/kernel/pull/2268#issuecomment-633297811 the kernel based on commit https://github.com/sonyxperiadev/kernel/pull/2268/commits/49320473843a5f9de7bff5344bb8612aef6ff4c2):

```
<2>[  125.184411] kernel BUG at /home/stefan/android/source/kernel/sony/msm-4.14/kernel/lib/genalloc.c:392!
<6>[  125.188111] Call trace:
<6>[  125.188170]  gen_pool_free+0x1d4/0x1dc
<6>[  125.188282]  __dma_free+0x74/0xbc
<6>[  125.188345]  ipa3_teardown_sys_pipe+0x948/0x10f0
<6>[  125.188406]  ipa3_wwan_remove+0x98/0x540
<6>[  125.188517]  platform_drv_remove+0x24/0x4c
<6>[  125.188579]  device_release_driver_internal+0x130/0x1d4
<6>[  125.188689]  driver_detach+0x68/0xa4
<6>[  125.188748]  bus_remove_driver+0x74/0xa4
<6>[  125.188807]  driver_unregister+0x2c/0x4c
<6>[  125.188921]  platform_driver_unregister+0x10/0x18
<6>[  125.188980]  ipa3_ssr_notifier_cb+0x114/0x50c
<6>[  125.189044]  srcu_notifier_call_chain+0x5c/0xa0
<6>[  125.189154]  subsys_notif_queue_notification+0x28/0x30
<6>[  125.189213]  notify_each_subsys_device+0x268/0x3b0
<6>[  125.189326]  subsystem_restart_wq_func+0x214/0x704
<6>[  125.189390]  process_one_work+0x1fc/0x460
<6>[  125.189451]  worker_thread+0x2e8/0x44c
<6>[  125.189560]  kthread+0x118/0x128
<6>[  125.189621]  ret_from_fork+0x10/0x18
<0>[  125.189682] Code: d4210000 14000000 d4210000 14000000 (d4210000)
```

Full logs and files can be found in: https://github.com/sonyxperiadev/bug_tracker/issues/580#issuecomment-633306726

**Comment by stefanhh0** [comment]
Running this PR without sensors and transpower seems to stabilize the phone behavior (see: https://github.com/sonyxperiadev/bug_tracker/issues/583). So, although no yet the final solution from the yoshino/lilac perspective this fixes already some issues.

**Comment by stefanhh0** [comment]
Wakeup from sleep seems to be broken:

Wuff, watchdog barks and bites, then kernel panic because biting fails:
 
```
<3>[  225.133091] dsi-ctrl:[dsi_ctrl_handle_error_status] dsi FIFO UNDERFLOW error: 0xf00000
<4>[  225.133461] dsi-ctrl:[dsi_ctrl_check_for_spurious_error_interrupts] Detected spurious interrupts on dsi ctrl
<6>[  225.133910] msm_watchdog 17817000.qcom,wdt: Watchdog bark! Now = 225.133885
<6>[  225.133931] msm_watchdog 17817000.qcom,wdt: Watchdog last pet at 204.769656
<6>[  225.133952] msm_watchdog 17817000.qcom,wdt: cpu alive mask from last pet ff
<0>[  225.133968] Kernel panic - not syncing: Failed to cause a watchdog bite! - Falling back to kernel panic!
<6>[  225.134351] CPU: 0 PID: 84 Comm: cfinteractive Tainted: G S      W       4.14.176-gef7fd1a4bb9f-dirty #1
<6>[  225.134716] Hardware name: SoMC Lilac-ROW(MSM8998 v2.1) (DT)
<6>[  225.134919] Call trace:
<6>[  225.135140]  dump_backtrace+0x0/0x1b4
<6>[  225.135525]  show_stack+0x14/0x1c
<6>[  225.135734]  dump_stack+0xd4/0x10c
<6>[  225.135949]  panic+0x1d8/0x3dc
<6>[  225.136164]  panic_wdog_handler+0x0/0x74
<6>[  225.136546]  __handle_irq_event_percpu+0x14c/0x2b0
<6>[  225.136766]  handle_irq_event+0x5c/0xd0
<6>[  225.137145]  handle_fasteoi_irq+0xf0/0x1c0
<6>[  225.137358]  __handle_domain_irq+0x7c/0xbc
<6>[  225.137567]  gic_handle_irq+0x168/0x1b8
<6>[  225.137937]  el1_irq+0xf0/0x194
<6>[  225.138150]  rebalance_domains+0xd8/0x388
<6>[  225.138362]  run_rebalance_domains+0x270/0x2c0
<6>[  225.138732]  __do_softirq+0x1ec/0x3a0
<6>[  225.138941]  irq_exit+0xf4/0x100
<6>[  225.139152]  __handle_domain_irq+0x84/0xbc
<6>[  225.139526]  gic_handle_irq+0x168/0x1b8
<6>[  225.139732]  el1_irq+0xf0/0x194
<6>[  225.139934]  0xffffffc0f733ba60
<6>[  225.140146]  cpufreq_interactive_notifier+0x28/0x108
<6>[  225.140526]  srcu_notifier_call_chain+0x5c/0xa0
<6>[  225.140738]  cpufreq_notify_transition+0x1a0/0x21c
<6>[  225.141119]  cpufreq_freq_transition_end+0x30/0x90
<6>[  225.141325]  set_cpu_freq+0x128/0x218
<6>[  225.141537]  msm_cpufreq_target+0x314/0x354
<6>[  225.141910]  __cpufreq_driver_target+0x74/0x550
<6>[  225.142124]  cpufreq_interactive_speedchange_task+0x1a4/0x310
<6>[  225.142494]  kthread+0x118/0x128
<6>[  225.142708]  ret_from_fork+0x10/0x18
<2>[  225.142919] SMP: stopping secondary CPUs
```

[console-ramoops-0.log](https://github.com/sonyxperiadev/kernel/files/4674588/console-ramoops-0.log)
[dmesg-ramoops-0.log](https://github.com/sonyxperiadev/kernel/files/4674589/dmesg-ramoops-0.log)
[pmsg-ramoops-0.log](https://github.com/sonyxperiadev/kernel/files/4674590/pmsg-ramoops-0.log)

Logs from boot:
[dmesg.log](https://github.com/sonyxperiadev/kernel/files/4674607/dmesg.log)
[logcat.1.log](https://github.com/sonyxperiadev/kernel/files/4674608/logcat.1.log)
[logcat.2.log](https://github.com/sonyxperiadev/kernel/files/4674609/logcat.2.log)

Disconnected phone from USB and then tried to reactivate the screen after reconnecting to USB, logcat shows contents until kernel panic after watchdog fails to bite:
[logcat.3.log](https://github.com/sonyxperiadev/kernel/files/4674613/logcat.3.log)
[dmesg.log](https://github.com/sonyxperiadev/kernel/files/4674614/dmesg.log)

**Workaround**
Open e.g. termux, acquire wakelock -> phone never falls asleep. Drawback: high battery drain.

**Comment by kholk** [comment]
PR updated to include the latest bits with Seine camera, charger DT, some
fixes for Yoshino and other fixes for Qualcomm QuickCharge on all platforms.

**Comment by stefanhh0** [comment]
I have retestet it on yoshino lilac. I have done a clean build from scratch this time without deactivating sensors. 

Works okay, still wakeup from sleep is not working, plus starting the phone shows sensors trouble + signal strength symbol is going on and off (shaky), eventually the phone gets online or reboots for another round. Anyway I don't know if the yoshino fixes that you have pushed are expected to fix any of those.

Good things, not spotted any new regressions. Charging works fine. With the workaround never let the phone fall asleep it shows an uptime of currently 12:30!

From personal point of view, biggest pain spot currently is, that the phone is no longer able to wake up from sleep. But I also think it would be okay from yoshino standpoint to merge this PR.

**Comment by kholk** [comment]
The various tests seem to be all passed. 

Please merge this PR.

**Pull request merged**
