### PR TITLE
adjust yukon clocks and dt

### PR DESCRIPTION
**Pull request by erikcas**
needed for camera

### CODE REVIEW

**Comment by kholk** [comment]
FIX IT!!!!! You forgot again the damn clocks!!!

**Comment by erikcas** [comment]
fixed

**Comment by kholk** [comment]
MERGE MERGE MERGE MERGE!!!!!!

Along with https://github.com/sonyxperiadev/kernel/pull/636 and https://github.com/sonyxperiadev/kernel/pull/638 for respectively Eagle and Seagull camera enablement completion

**Comment by jerpelea** [comment]
Please fix whitespaces!

**Pull request merged**
