### PR TITLE
[2.3.2.r1.4] Remove unused cores in 8956 DT

### PR DESCRIPTION
**Pull request by konradybcio**
MSM8956 has 6 cores whereas DT contained 8.

### CODE REVIEW

**Comment by kholk** [comment]
Please do not send PRs without testing before.

Last time we tested this the platform didn't boot.

**Comment by oshmoun** [comment]
Will check soon
Maybe the situation is different on 4.9

**Comment by bartcubbins** [comment]
@oshmoun wait a little, patch is not complete :)
@ewentual please update your PR ;)

**Comment by oshmoun** [comment]
kugo doesn't boot

**Comment by jerpelea** [comment]
suzu does not boot

**Pull request closed without merging**
