### PR TITLE
[1.3.3] qseecom driver updates

### PR DESCRIPTION
**Pull request by humberos**
qseecom driver updates from qcom LA.BR.1.3.3_rb2.29

tested on suzu.

### CODE REVIEW

**Comment by kholk** [comment]
That whitelist commit..... Aaaargh... It was a mess for kitakami and Tulip on kernel 3.18!! Had to hack the world.... 

Please test on kitakami!

**Comment by pablomh** [comment]
Would tulip be required as well?

**Comment by pablomh** [comment]
It didn't blow up my tulip during my short testing.

**Comment by kholk** [comment]
Can anyone test this on Kitakami and Rhine/Shinano platforms, please?

**Pull request closed without merging**
