### PR TITLE
Upgrade EXT4 with cherry-picks from Angler's kernel

### PR DESCRIPTION
**Pull request by stellirin**
### loire
- [ ] suzu
### kitakmi
- [ ] satsuki
- [ ] satsuki_dsds
- [ ] sumire
- [ ] sumire_dsds
- [x] suzuran
- [x] ivy
- [ ] ivy_dsds
- [ ] karin
- [x] karin_windy
### kanuti
- [ ] tulip
### shinano
- [ ] leo
- [ ] aries
- [ ] sirius
- [ ] scorpion
- [ ] scorpion_windy
- [ ] castor
- [ ] castor_windy
### rhine
- [x] honami
- [ ] amami
- [ ] togari

### CODE REVIEW

**Comment by kholk** [comment]
This will bring a good performance improvement but... Wait. 
We actually have some eMMC problems, those have to be solved first, since current ext4 code is known working.

**Comment by rcstar6696** [comment]
can not builded on shinano

**Comment by stellirin** [comment]
Bump, these a mandatory changes for Nougat!

**Comment by kholk** [comment]
How many devices have been tested on this pr?

**Comment by oshmoun** [comment]
tested on suzuran.
device didn't catch fire.
:+1: 
if testing is needed may I suggest the markdown list?

**Comment by stellirin** [comment]
Added the check list, 32bit devices need the defconfig editing, just like the kitakami/loire devices. tulip wasn't tested as last time I tried this device it wouldn't boot. (Actually it's been a while so I'll try it again to see if there's been any change)

```
+CONFIG_EXT4_USE_FOR_EXT23=y
 +# CONFIG_EXT4_FS_POSIX_ACL is not set
 +CONFIG_EXT4_FS_ENCRYPTION=y
 +CONFIG_EXT4_ENCRYPTION=y
```

**Comment by mcgi5sr2** [comment]
`CC      fs/ext4/dir.o
/home/mcgi5sr2/AOSP/android/system/kernel/sony/msm/fs/ext4/dir.c: In function 'ext4_readdir':
/home/mcgi5sr2/AOSP/android/system/kernel/sony/msm/fs/ext4/dir.c:263:3: error: implicit declaration of function 'dir_relax' [-Werror=implicit-function-declaration]
   if ((ctx->pos < inode->i_size) && !dir_relax(inode))
   ^
cc1: some warnings being treated as errors
/home/mcgi5sr2/AOSP/android/system/kernel/sony/msm/scripts/Makefile.build:308: recipe for target 'fs/ext4/dir.o' failed
make[3]: *** [fs/ext4/dir.o] Error 1
/home/mcgi5sr2/AOSP/android/system/kernel/sony/msm/scripts/Makefile.build:455: recipe for target 'fs/ext4' failed
make[2]: *** [fs/ext4] Error 2
/home/mcgi5sr2/AOSP/android/system/kernel/sony/msm/Makefile:821: recipe for target 'fs' failed
make[1]: *** [fs] Error 2
make[1]: *** Waiting for unfinished jobs....
`

Building Aries d5803

**Comment by alviteri** [comment]
@mcgi5sr2 try again there is 32bit support now

**Comment by mcgi5sr2** [comment]
HI David I had already adjusted the defconfig on Aries for encryption as your commit does. I will re-build and test as soon as I return from China (14days)

**Comment by rcstar6696** [comment]
castor_windy and sirius work

**Comment by alviteri** [comment]
@rcstar6696 did you try ... Encrypt the device ? It seems not working here .....

**Comment by rcstar6696** [comment]
No i never encrypt the device :)

**Comment by rancidfrog** [comment]
Tested on aries using
`curl https://patch-diff.githubusercontent.com/raw/sonyxperiadev/kernel/pull/816.patch | git am`
Everything seems to be working,
what exactly should I look|test for?
I am able to browse both internal and extsd

**Comment by alviteri** [comment]
@rancidfrog try to encrypt device

**Comment by rancidfrog** [comment]
@alviteri 
So far when selected phone reboots and loops: LED goes from red to green with vibrate on SONY logo, then bootanimation starts for a second and reboot cycle repeats -> red, to green led vibrate ...

**Comment by alviteri** [comment]
@rancidfrog https://github.com/sonyxperiadev/kernel/pull/906

**Comment by rancidfrog** [comment]
Test again with both #906 and #816 
First attempt failed: Android robot logo appeared then black screen. Forced shut and rebooted Security settings says encrypted and twrp asks for decryption password but nothing was set up.
Needed to reflash.
Second attempt, robot appears for a second and phone reboots and loops

**Comment by alviteri** [comment]
@rancidfrog are you sure ? because here I have encrypted device with this and other commit

honami

@rancidfrog 

https://lh3.googleusercontent.com/-cys3ZrItVk0/V_FMvruzBqI/AAAAAAAAS5U/zH3yiuT7FbkJNCe85xUzSStSm6TFb4l7gCL0B/h1920/5001786882950271292%253Faccount_id%253D1

**Pull request merged**
