### PR TITLE
[K.P.1.0]Kconfig.platforms: Fix nagara platform typo

### PR DESCRIPTION
**Pull request by Haxk20**
This was missed when fixing the other typos

### CODE REVIEW

**Review by MarijnS95 — APPROVED** [review]

**Comment by Haxk20** [comment]
@jerpelea Please click this :)

**Comment by MarijnS95** [comment]
`[K.P.1.0]`?

**Comment by jerpelea** [comment]
@MarijnS95 Kernel.Platform.1.0

**Comment by MarijnS95** [comment]
@jerpelea Martin understood me :smile: - I wanted him to add that tag to the title!

**Pull request merged**
