### PR TITLE
msm: vidc: Allow clients to specify/query the colorspace

### PR DESCRIPTION
**Pull request by alviteri**
When encoder clients specify the color space, the resulting bitstream
will have the color space embedded in it.  This allows for the
decoder to display the picture accurately without the color being
skewed.

Similarly decoder clients can query the color space of the bitstream by
enabling MSM_VIDC_EXTRADATA_VUI_DISPLAY_INFO.  If the bitstream contains
the colorspace hint, the appropriate extradata will be emitted by the
decoder.

Author: Deva Ramasubramanian dramasub@codeaurora.org

Change-Id: I83a3e28b13c3aa306e7cc2d1552a6d39c0d3d49f
Signed-off-by: Deva Ramasubramanian dramasub@codeaurora.org
Signed-off-by: Praveen Chavan pchavan@codeaurora.org

### CODE REVIEW

**Comment by alviteri** [comment]
@jerpelea on 1.1 where I can put this?

**Comment by galaxyfreak** [comment]
Fixes green/pink video overlay?

**Comment by alviteri** [comment]
@galaxyfreak nope this avoid error in build related to mediaHAL

**Comment by jerpelea** [comment]
As usually on misc-qcom if it is coming from qcom

**Pull request closed without merging**
