### PR TITLE
AU_LINUX_ANDROID_LA.BF64.1.2.1

### PR DESCRIPTION
**Pull request by humberos**

### CODE REVIEW

**Comment by kholk** [comment]
.... And this solves... Which problem?

**Comment by humberos** [comment]
Actually these changes made improvements for interactive governor. I have no found issues in current sources even after applying these changes.

**Comment by kholk** [comment]
First rule: don't fix what doesn't need to be fixed!  :)

**Comment by humberos** [comment]
ok :)

**Comment by jerpelea** [comment]
Please dont push patches that are not needed
This makes rebase harder

**Comment by humberos** [comment]
ok I got it. Although these patches are present at CAF

**Comment by jerpelea** [comment]
Not in our branch

**Comment by humberos** [comment]
sorry?
https://www.codeaurora.org/cgit/quic/la/kernel/msm-3.10/log/drivers/cpufreq?h=LA.BF64.1.2.1
isn't this branch?
I am confused!

**Comment by jerpelea** [comment]
We used a specific tag

**Comment by humberos** [comment]
Oh, ok!
but we got mdss updates from pure LA.BF64.1.2.1
I am sorry, I was thinking it was the correct branch to find our possible fixes/improvements.

**Pull request closed without merging**
