### PR TITLE
[7.1.r1] drm/msm/sde: sde_hw_top: Add trinket to legacy platform lookup

### PR DESCRIPTION
**Pull request by krnlyng**
Also remove some unused defines which are confusing.

I asked alin whether this is correct and he said that we should do a PR.
I don't know if it's correct but please let us know. It seems to improve performance slightly on SailfishOS.

### CODE REVIEW

**Comment by MarijnS95** [comment]
Very unlikely to actually make a difference since the WatchDog timers should only be used as fallback when TearCheck interrupts from the panel are not received and cause PingPong timeouts. Have you validated whether that happens?

**Comment by krnlyng** [comment]
@MarijnS95
Hi, thanks for the reply.
I will dig into the driver. As i am not very familiar could you give me some hints where to start looking?
It's curious that we see very large framerate drops on Xperia 10 II (seine/pdx201), but not on Xperia 10 (ganges / kirin, mermaid) and absolutely not on Xperia 10 III (lena/pdx213), but i guess pdx213 has a more powerful gpu. Still it's curious that Xperia 10 II (seine/pdx201) is such an outlier.

**Comment by MarijnS95** [comment]
Seine is indeed extremely sluggish in UI, can you check the interrupts that fire in `/sys/kernel/debug/dri/0/debug/core_irq`?

**Comment by krnlyng** [comment]
@MarijnS95
```
[root@Xperia10II-DualSIM defaultuser]# cat /sys/kernel/debug/dri/0/debug/core_irq
idx:8 irq:2072 enable:0 cb:0
idx:41 irq:2072 enable:0 cb:0
idx:322 irq:29339 enable:0 cb:0
[root@Xperia10II-DualSIM defaultuser]# cat /sys/kernel/debug/dri/0/debug/core_irq
idx:8 irq:2072 enable:0 cb:0
idx:41 irq:2072 enable:0 cb:0
idx:322 irq:29339 enable:0 cb:0
[root@Xperia10II-DualSIM defaultuser]# cat /sys/kernel/debug/dri/0/debug/core_irq
idx:8 irq:2072 enable:0 cb:0
idx:41 irq:2072 enable:0 cb:0
idx:322 irq:29339 enable:0 cb:0
[root@Xperia10II-DualSIM defaultuser]# cat /sys/kernel/debug/dri/0/debug/core_irq
idx:8 irq:2072 enable:0 cb:0
idx:41 irq:2072 enable:0 cb:0
idx:322 irq:29339 enable:0 cb:0
[root@Xperia10II-DualSIM defaultuser]# cat /sys/kernel/debug/dri/0/debug/core_irq
idx:8 irq:2072 enable:0 cb:0
idx:41 irq:2072 enable:0 cb:0
idx:322 irq:29339 enable:0 cb:0
[root@Xperia10II-DualSIM defaultuser]# cat /sys/kernel/debug/dri/0/debug/core_irq
idx:8 irq:2072 enable:0 cb:0
idx:41 irq:2072 enable:0 cb:0
idx:322 irq:29339 enable:0 cb:0
[root@Xperia10II-DualSIM defaultuser]# cat /sys/kernel/debug/dri/0/debug/core_irq
idx:8 irq:2072 enable:0 cb:0
idx:41 irq:2072 enable:0 cb:0
idx:322 irq:29339 enable:0 cb:0
[root@Xperia10II-DualSIM defaultuser]# cat /sys/kernel/debug/dri/0/debug/core_irq
idx:8 irq:2072 enable:0 cb:0
idx:41 irq:2072 enable:0 cb:0
idx:322 irq:29339 enable:0 cb:0
[root@Xperia10II-DualSIM defaultuser]# cat /sys/kernel/debug/dri/0/debug/core_irq
idx:8 irq:2072 enable:0 cb:0
idx:41 irq:2072 enable:0 cb:0
idx:322 irq:29339 enable:0 cb:0
[root@Xperia10II-DualSIM defaultuser]# cat /sys/kernel/debug/dri/0/debug/core_irq
idx:8 irq:2093 enable:0 cb:0
idx:41 irq:2093 enable:0 cb:0
idx:322 irq:29379 enable:1 cb:1
[root@Xperia10II-DualSIM defaultuser]# cat /sys/kernel/debug/dri/0/debug/core_irq
idx:8 irq:2116 enable:0 cb:0
idx:41 irq:2116 enable:0 cb:0
idx:322 irq:29472 enable:1 cb:1
[root@Xperia10II-DualSIM defaultuser]# cat /sys/kernel/debug/dri/0/debug/core_irq
idx:8 irq:2139 enable:0 cb:0
idx:41 irq:2139 enable:0 cb:0
idx:322 irq:29545 enable:1 cb:1
[root@Xperia10II-DualSIM defaultuser]# cat /sys/kernel/debug/dri/0/debug/core_irq
idx:8 irq:2164 enable:0 cb:0
idx:41 irq:2164 enable:0 cb:0
idx:322 irq:29614 enable:1 cb:1

```

In the first few cat's nothing was changing on UI, the last three i swiped back and forth between two views.

**Comment by MarijnS95** [comment]
Thanks, that at least confirms we're not using the WatchDog timer (which are indices 2-3, 5-7).

The IRQs that are used here:

```
8 - SDE_INTR_PING_PONG_0_DONE (vsync)
41 - SDE_INTR_CTL_0_START (starting the controller, every frame, same number of interrupts as vsync)
322 - SDE_INTR_INTF_TEAR_RD_PTR (when to write new data)
```

**Comment by krnlyng** [comment]
Ok so the PR here is probably just placebo.

However it would still be nice to get an improvement somehow.

**Comment by krnlyng** [comment]
```
[root@Xperia10II-DualSIM defaultuser]# cat /sys/kernel/debug/dri/0/debug/core_irq
idx:8 irq:2352 enable:0 cb:0
idx:41 irq:2352 enable:0 cb:0
idx:322 irq:35616 enable:1 cb:1
[root@Xperia10II-DualSIM defaultuser]# cat /sys/kernel/debug/dri/0/debug/core_irq
idx:8 irq:2352 enable:1 cb:1
idx:26 irq:0 enable:1 cb:1
idx:41 irq:2352 enable:1 cb:1
idx:320 irq:0 enable:1 cb:1
idx:322 irq:35658 enable:1 cb:1
[root@Xperia10II-DualSIM defaultuser]# cat /sys/kernel/debug/dri/0/debug/core_irq
idx:8 irq:2356 enable:1 cb:1
idx:26 irq:0 enable:1 cb:1
idx:41 irq:2356 enable:1 cb:1
idx:320 irq:0 enable:1 cb:1
idx:322 irq:35730 enable:1 cb:1
```

This is what happens when i trigger one of our worst case scenarios.
Looks different.

**Comment by MarijnS95** [comment]
> Ok so the PR here is probably just placebo.

Yeah, I think so.

> However it would still be nice to get an improvement somehow.

Definitely, it's horrible to use right now. It's quite coincidental that we're working to bring Seine and friends to the mainlined DPU driver "as we speak", too.

**Comment by MarijnS95** [comment]
@krnlyng It looks like the driver registered a few more IRQs to seek for (that's the `cb:1`, registered callback count), `SDE_INTR_INTF_1_UNDERRUN` (26) and `SDE_INTR_INTF_TEAR_AUTOREFRESH_DONE` (320) but none ever fired (`irq:0`).

**Comment by krnlyng** [comment]
Probably not useful, Still would be nice to get improvements somehow.

**Pull request closed without merging**
