### PR TITLE
[3.10] Solve vmalloc problems, ASoC cleanup, more MDSS calibration

### PR DESCRIPTION
**Pull request by kholk**

### CODE REVIEW

**Comment by kholk** [comment]
Yeah, I absolutely know about that.... and don't worry, I'm 99% sure this is happening only on x86 architecture.
ARM should be totally fine :)

**Comment by jerpelea** [comment]
in case we run into problems we will follow mainline revert 
for now seems ok on ARM

**Comment by Tommy-Geenexus** [comment]
I think it will be fine, the issue could not be 100% related to this commit either way, just wanted to bring this up in case anything bad happens ;)

**Comment by kholk** [comment]
Ah yeah, that's obvious, we appreciate that ;)

**Pull request merged**
