### PR TITLE
[1.2.2] Refactored Sony Unified Display Driver (and other fixes)

### PR DESCRIPTION
**Pull request by kholk**
This is a major refactoring of our unified display driver.

The new driver supports multi-resolution (and multiple timings)
panels, with dynamic resolution switch, which are features
required by SoMC Satsuki's 4K display.

Now we also have a polling mechanism, taken from Sony's copylefts
and modified for our own driver, which will ensure a smooth
transition between continuous splash bootloader logo and OS
framebuffer takeover (usually displaying an OS logo).

Apart new features, now we have nice improvements in code
readability and nice cleanups:
the driver has now been organized in various specialized files,
which are managing only a specific "function". This can be further
improved (TODO in the future) by making the driver modular,
making us able to compile it with the complete omission of some
specific feature that we can find only in a specific platform
and/or a specific device (example: cmd-detect only on Rhine, Yukon).

Nice cleanups come on both code movements and refactoring:
I have been able to remove some hacks from "standard" QC code and
either reimplement them properly in our driver or destroying them
in favor of the resolution of some bugs.

About other cleanups, I've finally got rid of some arrays in our
panel specific struct(s) and simplified the DT parsing / panel
parameters re-set after detection. Moreover, the Sony Unified
Display Driver specific structures, types and definitions have
been removed from common QC headers and moved into our own ones
for enhanced portability across kernel releases.

This whole refactoring will also decrease this driver's footprint
and slightly speed up the boot process.

---

Other fixes include: new Fingerprint Sensor driver (FPC1145), DT updates for MHL and thermal on Kitakami and fixes to HDMI.

### CODE REVIEW

**Comment by olefb** [comment]
Maybe I'm missing something, and I've only tested with OmniROM, but currently, this is breaking display on my togari (a blank light turned on briefly a few seconds after coldboot).

dmesg and logcat here: https://gist.github.com/olefb/1c343c3c6e2d657a27f0

Looks exciting! Thank you :-)

**Comment by kholk** [comment]
Hey! Thanks for the feedback.
I have just updated the PR to include a fix for your issue.

Can you resync and test again? It should work now.
Thanks again!

**Comment by olefb** [comment]
Yep, that sorted it right out! Damn, you're quick. Display on togari now works. Cheers!

**Comment by kholk** [comment]
Thank you! :D

**Comment by rcstar6696** [comment]
After merging your new backlightdriver in my repos the display of my sirius does not turn on everytime 
If it is on charger dock it does not repose when its full charged 
 only reboot helps to get backlight back 
Do you have an  idea?  If you want i can take a log and dmseg

**Comment by kholk** [comment]
21/03: Added Tianchi and FIH boards fix.

**Comment by jerpelea** [comment]
drivers/video/msm/mdss/somc_panel/panel_detect.c: In function 'adc_panel_detect':
drivers/video/msm/mdss/somc_panel/panel_detect.c:336:22: warning: unused variable 'panel_name' [-Wunused-variable]
  static const char \* panel_name;
                      ^

**Comment by kholk** [comment]
22/03: Honami fix, CABC worker workaround feature removal, panel_detect unused variable cleanup

**Pull request merged**
