### PR TITLE
[6.4.r1] [URGENT] rqbalance: Schedule CFL setting on hotplug if cluster unavailable

### PR DESCRIPTION
**Pull request by kholk**
If a cluster is totally down, it is impossible to set a cpufreq
policy on it.

Change the logic so that, if the cluster is currently up we set
the limits right in the sysfs handler but, if the cluster is
unavailable, schedule the setting for the next upcore event and
artificially produce a non-blocking upcore event on the
navailable cluster: this will make us get into the newly
introduced hotplugging notifier that will take care of updating
the policy (thus setting the frequency limits) as soon as the
cluster will come up.

### CODE REVIEW

**Comment by kholk** [comment]
Build errors due to k4.4 having the old hotplug notifiers. Reopening when backported correctly.

**Comment by kholk** [comment]
The PR has been fixed.

MERGEME!

**Comment by alviteri** [comment]
the main problem was fixed but now i can observe 

07-16 00:14:07.953   698   698 E RQBalance-PowerHAL: Error writing to /sys/devices/system/cpu/cpuquiet/nr_min_cpus: Invalid argument

**Comment by kholk** [comment]
This is not an issue and it is absolutely not related to the RQB-CFL patchset.
Whenever this happens, the PowerHAL will retry and succeed. Don't worry.

**Pull request merged**
