### PR TITLE
[2.3.2.r1.4] Encryption upgrades, F2FS hwcrypto support, hardening

### PR DESCRIPTION
**Pull request by kholk**
This PR adds some hardening, F2FS support for ICE and updates hardware
encryption to use the right key size on UFS and eMMC (which is different!).

Also adds some memory management improvement and some fixes for
some race conditions.

Tested on SoMC Discovery DSDS (SDE)

### CODE REVIEW

**Comment by ix5** [comment]
Seems to work fine so far one kagura. Camera is ok.
Not tested: encryption.
[SSR bug](https://github.com/sonyxperiadev/bug_tracker/issues/268) is still present.

**Comment by kholk** [comment]
Waiting for a Tama test before the magic word.

**Comment by oshmoun** [comment]
works fine on tama after including a couple missed commits
breaks boot on tama in the current state, since one of the missed commits is critical to get it to boot

**Comment by kholk** [comment]
Missing commits merged in the PR. Tama working totally fine now.

MERGE!

**Pull request merged**
