### PR TITLE
[LA.UM.5.7.r1] Tone/Yoshino: Remove not needed debug_region memory allocation

### PR DESCRIPTION
**Pull request by bartcubbins**
This will be removed on Loire platform in this commit: https://github.com/sonyxperiadev/kernel/pull/1494/commits/5a18d4485975ab08514e25479ee3430d5bb472be so let's follow it on all our platforms

### CODE REVIEW

**Comment by jerpelea** [comment]
fix the patches.
you add a script then you remove it

**Comment by bartcubbins** [comment]
@jerpelea updated

**Comment by jerpelea** [comment]
this patch has to be carefully tested on the new loaders

**Comment by bartcubbins** [comment]
Was tested on maple device with 47.1.A.8.49 firmware. Pstore is OK. Any regressions.
@kholk your opinion?:)

**Pull request merged**
