### PR TITLE
[7.1.r1] [URGENT] Revert "arch: dtsi: tama-common: panel: set min brightness to 1.2mA"

### PR DESCRIPTION
**Pull request by kholk**
This reverts commit 162f8d73d8cd36fffbc9af9581b538988d355168.

This commit disables continuous splash on SoMC Tama Akatsuki.
Reverting it brings cont splash back!

Tested on SoMC SDM845 Tama Akatsuki RoW.

### CODE REVIEW

**Comment by MartinX3** [comment]
Could it cause hardware damage, @kholk ?

**Comment by kholk** [comment]
No

**Comment by sjllls** [comment]
@kholk  How about overriding it?
:D  #2264

**Comment by kholk** [comment]
Hold this PR, let's test #2264 before

**Comment by sjllls** [comment]
> Hold this PR, let's test #2264 before

No problem, thank you~ :P

**Pull request closed without merging**
