### PR TITLE
[2.3.2.r1.4] Sanitization and small Android Q preparation

### PR DESCRIPTION
**Pull request by kholk**
This (rather huge) patchset introduces some sanitization and improvements
for both qcom drivers and various kernel subsystems.

There are also patches to start supporting basic features of Android Q, which
are left disabled in all devices configurations, so that keeps full compatibility
(like not even having them) with the current releases of Android Pie.

The new (disabled) features for Android Q in this patchset are:
- PSI (Pressure Stall Information Tracking), useful to debug sched pressure statistics
- Android Verity via dm-android-verity (we are currently using dm-verity instead)
- Android AVB Verity
- DM-BOW backport for "Backup On Write" functionality

As already explained, everything else is sanitization and performance improvements.

This patchset shall be _carefully_ tested before merging.
Enjoy!

### CODE REVIEW

**Comment by kholk** [comment]
SoMC Ganges Mermaid DSDS
- Boot test OK
- Basic functionality test OK
------------------------------------------------
SoMC Tama Akatsuki RoW
- Boot test OK
- Basic functionality test OK
- Connectivity test OK
- Camera OK
------------------------------------------------
SoMC Loire Suzu RoW
- Boot test OK
- Basic functionality test OK
- Connectivity test OK
- Camera OK
- NOTE: Noticed faster boot times

**Comment by kholk** [comment]
After one day of testing on my daily driver (Akatsuki), it's still going strong. No issues to report.
Moreover, one more device tested.

**Comment by MarijnS95** [comment]
Same on Akatsuki here, but with the pr for kernel .174 merged, and compiled with clang.

**Comment by kholk** [comment]
No regressions, some improvements seen.

This PR can be merged.

**Pull request merged**
