### PR TITLE
[aosp/LE.UM.2.3.2.r1.4] arm64: configs: somc: update auto-generated defconfig for all platforms 

### PR DESCRIPTION
**Pull request by humberos**
Change-Id: Ic97a4597c74a820b52cf7ad8d4c33c310ae1791c
Signed-off-by: Humberto Borba <humberos@omnirom.org>

### CODE REVIEW

**Comment by kholk** [comment]
Sorry for nitpicking.

arm64: configs: somc: update auto-generated defconfig for all platforms

Link the auto generator GIT in the description, like
Generated using kernel-defconfig repo:
http://github.com/blahblah (link has to contain the current HEAD of the kernel-defconfig repo). 

Moreover, please remove the akatsuki device configuration as we still have no DT for it and the Tama common DT is configured for LCD having different voltages (it'd be dangerous if anyone booted akatsuki with an Akari DT!!)

**Comment by humberos** [comment]
> Sorry for nitpicking.
> 
> arm64: configs: somc: update auto-generated defconfig for all platforms
> 
> Link the auto generator GIT in the description, like
> Generated using kernel-defconfig repo:
> [http://github.com/blahblah](https://github.com/blahblah) (link has to contain the current HEAD of the kernel-defconfig repo).
> 
> Moreover, please remove the akatsuki device configuration as we still have no DT for it and the Tama common DT is configured for LCD having different voltages (it'd be dangerous if anyone booted akatsuki with an Akari DT!!)

Patch updated.
Thank you!

**Comment by kholk** [comment]
Thanks man. 

You only miss one thing, perhaps I've explained in a bad way.
The link would be this one: https://github.com/sonyxperiadev/kernel-defconfig/tree/517688581e102a5dbb0f993f7592a999c900ba43

**Comment by humberos** [comment]
> Thanks man.
> 
> You only miss one thing, perhaps I've explained in a bad way.
> The link would be this one: https://github.com/sonyxperiadev/kernel-defconfig/tree/517688581e102a5dbb0f993f7592a999c900ba43

Updated!

**Comment by kholk** [comment]
Perfect.

Can be merged.

**Pull request merged**
