### PR TITLE
[2.3.2.r1.4] Linux 4.9.137

### PR DESCRIPTION
**Pull request by nathanchance**
A recut of #1683 per @kholk's request

### CODE REVIEW

**Comment by kholk** [comment]
Thanks for reformatting it.

Will test as soon as we get stable enough!
Thanks again!

**Comment by kholk** [comment]
Testing can be started on MSM8956 Loire platform after solving the Google Assistant ADSP issue.
Nile testing after solving current non working audio issues.

Tone, Yoshino, Tama on hold.

Please test on the said platforms after solving these last issues, do not merge until all platforms tested.

**Comment by MartinX3** [comment]
Can I somehow help you testing the tama plattform?

I own a XZ2 (Akari) H8296 Rev 2.
I only need to wait for the bootloader update to a version higher than v59.

I have to unlock the bootloader anyway to develop my twrp build for the drm fix.

**Comment by kholk** [comment]
MSM8956 Loire stability not impacted by the upstream updates. @oshmoun never saw stability issues due to that.

Tone testing can be started since this platform is stable. 

Tama testing will happen soon, after display issues get solved.

Yoshino, Nile on hold due to stability issues to be solved.

**Comment by kholk** [comment]
Tone, Yoshino seem to be stable.

Tama testing is beginning right now.

If nothing bad happens, this PR will be ready to merge this monday.

**Comment by kholk** [comment]
@nathanchance Please resolve the conflicts

**Comment by jerpelea** [comment]
@nathanchance please push the latest patches for 136 and 137

**Comment by nathanchance** [comment]
> @nathanchance Please resolve the conflicts

Done.

> @nathanchance please push the latest patches for 136 and 137

Done.

**Pull request merged**
