### PR TITLE
[LA.UM.5.5.r1] drivers: soc: loire: Fix boot process

### PR DESCRIPTION
**Pull request by humberos**
Add missed DT entry and #ifdef soc driver to match with DT

### CODE REVIEW

**Comment by humberos** [comment]
ping @kholk

**Comment by humberos** [comment]
Not sure if we can still using 15 (for loire) or update it to 17

**Comment by oshmoun** [comment]
same as on 3.10, the documentation doesn't seem to help :(
https://github.com/sonyxperiadev/kernel/blob/aosp/LA.UM.5.5.r1/Documentation/devicetree/bindings/thermal/qpnp-adc-tm.txt#L75

**Comment by humberos** [comment]
Thanks @oshmoun 
I think 17 is ok since tone platform uses the same.
Also it matches with driver header.
Now we need librilqmiservices.so for RIL then I think radio/data will be ok at 7.1.1
WiFi (mmc sdio) is on my way.

**Comment by stellirin** [comment]
~~According to: https://github.com/sonyxperiadev/kernel/blob/aosp/LA.BR.1.3.3_rb2.14/include/linux/qpnp/qpnp-adc.h#L274~~

~~It should now be 18 on all platforms~~

Wrong branch, 17 looks correct.

**Comment by humberos** [comment]
Check it at 3.18

Em sáb, 17 de dez de 2016 21:44, Adam Farden <notifications@github.com>
escreveu:

**Pull request merged**
