### PR TITLE
[DO NOT MERGE]arm: defconfig: MSM8974: Enable CPUSETS

### PR DESCRIPTION
**Pull request by alviteri**
following : 3e2e5848784f94fc7e8efc9f7ddfdfdb5b99c795

Signed-off-by: David Viteri davidteri91@gmail.com

@jerpelea ... in test just sent the PR for more test in shinano by you and others

### CODE REVIEW

**Comment by alviteri** [comment]
ping @rcstar6696 @Myself5 @erikcas @kholk

**Comment by jerpelea** [comment]
8974 has no cpusets

**Comment by kholk** [comment]
IMHO it is a good idea to implement CPUSETS on 8974......

**Comment by jerpelea** [comment]
then lets do some tests
please post bench data

**Comment by alviteri** [comment]
for shinano on N like this is needed

https://github.com/SonyAosp/device_sony_rhine/commits/n-cpa

**Comment by kholk** [comment]
Even if CPUSETS would be an UX improvement more than a general performance thing, it will still give some more performance on apps that are benchmarking UX, like perhaps Vellamo or whatever.

So yes, post benchmark data.

**Comment by alviteri** [comment]
screenshot_20160930-141744
screenshot_20160930-142127

those are my values using CPUSETS in honami with android M ... will test N later

**Comment by kholk** [comment]
How's performance without it?

**Comment by alviteri** [comment]
sorry I didn't do screen capture but the points for SingleCore were 1320 and MultiCore were 1766

without CPUSETS

**Comment by kholk** [comment]
David, PR also the userspace bits!

**Pull request merged**
