### PR TITLE
[LA.UM.7.1.r1] 4.14.214

### PR DESCRIPTION
**Pull request by pablomh**
Everything applied cleanly this time.

### CODE REVIEW

**Comment by Haxk20** [comment]
@pablomh why is this still a draft ?

**Comment by pablomh** [comment]
Because I haven't had time to test it on any device (I'm this week at home taking care of the kids with almost no access to the computer), so if anyone could test it it'd be perfect, and I'd remove the draft tag.

**Comment by pablomh** [comment]
It works without apparent regressions on both `pioneer` (`nile` platform) and `pdx201` (`seine` platform).

**Comment by jerpelea** [comment]
it should be tested on tama & kumano

**Comment by Haxk20** [comment]
Tested on pdx201. Works

**Comment by jerpelea** [comment]
cherry-picked 
thanks!

**Pull request closed without merging**
