### PR TITLE
[LA.UM.6.4.R1] fpc1145: fix build on none-NILE targets

### PR DESCRIPTION
**Pull request by erikcas**
fix unused variable 'hw_type'

### CODE REVIEW

**Comment by erikcas** [comment]
Oh, I see @kholk already did this on the LE.UM.2.3.2.r1.4 branch so that prevents a question if it needs to be done on other branches as well.
Forcepushed corrected author and commit msg

**Comment by MarijnS95** [comment]
This was initially fixed in a different commit together with some other cleanups, but Angelo made this change separately so the cleanup has been rebased. Feel free to pull that one in as well for consistency: d66a700fadd34372a46c794a00f7eadf6aedce99

And the same for the Egistec driver: 6a08052ea80a71fb9908f1cfee3c4c4274e3a07b

**Comment by erikcas** [comment]
@MarijnS95 I will push those on first bad weather occasion during vakantie in eigen land 🤣

**Comment by MarijnS95** [comment]
@erikcas No worries I can push those as well (while checking if there aren't any other forgotten commits in there :see_no_evil:).

Hier schijnt de zon ook weer :sun_with_face:

**Pull request merged**
