### PR TITLE
[9.12.r1] Avoid suspend failures on sm8150

### PR DESCRIPTION
**Pull request by voidanix**
4.19 counterpart of #2516

### CODE REVIEW

**Comment by Thaodan** [comment]
I might also sense to cherry-pick to cherry-pick https://github.com/mer-hybris/android_kernel_sony_msm/commit/9e170078f901a6907db6a1382548b8ca394ada48 at the same time.

**Comment by bartcubbins** [comment]
It seems we have a userspace problem.
Anyway, by "fixing" it like this, this PR is missing this commit https://git.codelinaro.org/clo/la/kernel/msm-4.14/-/commit/8ad13ea554c17395822383405b34b82fe14e034f

**Comment by jerpelea** [comment]
please cherrypick

**Comment by Thaodan** [comment]
> It seems we have a userspace problem.
> Anyway, by "fixing" it like this, this PR is missing this commit
> https://git.codelinaro.org/clo/la/kernel/msm-4.14/-/commit/8ad13ea554c17395
> 822383405b34b82fe14e034f
Is that some kind of hack? Working around PM-runtime suspend sounds wrong.

**Comment by Thaodan** [comment]
> It seems we have a userspace problem.
> Anyway, by "fixing" it like this, this PR is missing this commit
> https://git.codelinaro.org/clo/la/kernel/msm-4.14/-/commit/8ad13ea554c17395
> 822383405b34b82fe14e034f
> 
> --

The commit is already there in msm-4.14 as: 
9a0b2664ae23e6cc54736113789fc82e290fa7f9.

@jerpelea^

**Comment by bartcubbins** [comment]
I just tested AOSP 12 k4.19 on Seine and Tama and have no issue with suspending devices, moreover, when porting the missing commit, the bluetooth stops working. If you are using OS other than Android I would recommend you to check your OS userspace and try to fix this problem or use these changes in your kernel fork.

**Comment by Thaodan** [comment]
> I just tested AOSP 12 k4.19 on Seine and Tama and have no issue with
> suspending devices, moreover, when porting the missing commit, the
> bluetooth stops working. If you are using OS other than Android I would
> recommend you to check your OS userspace and try to fix this problem or use
> these changes in your kernel fork.
> 
So you blame any other OS than Android? If bluetooth breaks because of the 
commit than something else should be wrong since the commit is already present 
in 4.14.

**Pull request merged**
