### PR TITLE
[LA.UM.9.12.r1] More Lena porting

### PR DESCRIPTION
**Pull request by konradybcio**
Please review thoroughly :)

### CODE REVIEW

**Comment by konradybcio** [comment]
> why not just disable the coresight related drivers?

Yeah, might as well do that

**Comment by kholk** [comment]
I reviewed this yesterday; why are you making me come here for a re-review?

**Comment by jerpelea** [comment]
please remove the fp driver and coresight and port the changes to the existing one

**Comment by kholk** [comment]
> please remove the fp driver and port the changes to the existing one

Whoa, I didn't notice that!! -- On a note, isn't this the same ET6xx model series that we have on Edo?
...because that'd literally Just Work (TM) [firmware warning].

**Comment by jerpelea** [comment]
cherrypicked

**Pull request closed without merging**
