### PR TITLE
[2.3.2.r1.4] Update brcmfmac backport up to partial v5.2-rc6

### PR DESCRIPTION
**Pull request by vknecht**
Seems to help with less wifi related crashes, and better suspend time.
These commits only touch drivers/net/wireless/broadcom/ so they were easy to apply using git am,
however I wonder how to handle eg. backported include/
Should [this procedure](https://backports.wiki.kernel.org/index.php/Documentation/integration) be followed ?

### CODE REVIEW

**Comment by stefanhh0** [comment]
Just a question, is this change related to any of those: 
https://github.com/sonyxperiadev/bug_tracker/issues#419 
https://github.com/sonyxperiadev/bug_tracker/issues#433

**Comment by ix5** [comment]
<strike>Tone seems ok, connects to 2.4Ghz network.</strike>
Strike that, must've been the wrong boot image. I cannot turn on wifi on kagura with this.

**Comment by ix5** [comment]
Wi-Fi is fine on kagura, can connect to 2.4Ghz access point.
The breakage was caused by merging https://github.com/sonyxperiadev/kernel/pull/2192 locally.

**Comment by chris42** [comment]
I am running this PR on an android10/kernel 4.9 kugo/loire. The dropouts are less compared to Android Pie, especially in sleep. Thanks a lot @vknecht ! 
I just had a reconnect on Wifi while the device was use, however do not know what happened. Attached find a log of that event, maybe you can understand it?

```
03-04 19:17:28.713  3156  4888 D DhcpClient: doQuit
03-04 19:17:28.715   580   580 E WifiHAL : wifi_get_link_stats: requestResponse Error:-3
03-04 19:17:28.717   945  2890 E WifiVendorHal: getWifiLinkLayerStats_1_3_Internal(l.926) failed {.code = ERROR_NOT_SUPPORTED, .description = }
03-04 19:17:28.728  3156  4888 D DhcpClient: onQuitting
03-04 19:17:28.730   527  5505 W ServiceManager: Permission failure: android.permission.NETWORK_STACK from uid=1073 pid=3156
03-04 19:17:28.730  3156 12203 D DhcpClient: Receive thread stopped
03-04 19:17:28.733  4884  4884 I wpa_supplicant: wlan0: CTRL-EVENT-DISCONNECTED bssid=1a:e8:29:a2:76:5e reason=3 locally_generated=1
03-04 19:17:28.738   527 12219 W DnsTlsSocket: SSL_connect error 5, errno=103
03-04 19:17:28.738   527   793 I Netd    : Destroyed 1 sockets on 192.168.3.13 in 1.5 ms
03-04 19:17:28.739   945  1001 I EthernetTracker: interfaceLinkStateChanged, iface: wlan0, up: true
03-04 19:17:28.753   527  5505 I netd    : interfaceSetCfg() <23.42ms>
03-04 19:17:28.758   527  5505 W ServiceManager: Permission failure: android.permission.NETWORK_STACK from uid=1073 pid=3156
03-04 19:17:28.765   527 12248 W DnsTlsSocket: SSL_connect error 5, errno=103
03-04 19:17:28.767   527   793 I Netd    : Destroyed 1 sockets on <ipv6 removed> in 2.6 ms
03-04 19:17:28.780   527  5505 I netd    : interfaceSetEnableIPv6("wlan0", "false") <24.25ms>
03-04 19:17:28.782   527  5505 W ServiceManager: Permission failure: android.permission.NETWORK_STACK from uid=1073 pid=3156
03-04 19:17:28.784   527  5505 I netd    : interfaceClearAddrs("wlan0") <2.40ms>
03-04 19:17:28.792   580   580 E WifiHAL : Packet monitoring is not yet triggered
03-04 19:17:28.794   945  2890 E WifiVendorHal: getTxPktFates(l.1857) failed {.code = ERROR_NOT_AVAILABLE, .description = }
03-04 19:17:28.795   580   580 E WifiHAL : Packet monitoring is not yet triggered
03-04 19:17:28.806   945  2890 E WifiVendorHal: getRxPktFates(l.1899) failed {.code = ERROR_NOT_AVAILABLE, .description = }
03-04 19:17:28.808   945  2890 D WifiLastResortWatchdog: updateFailureCountForNetwork: No networks for ssid = null
03-04 19:17:28.809   945  2890 D WifiClientModeImpl: ClientModeImpl: Leaving Connected state
03-04 19:17:28.813   945  2890 E WifiVendorHal: stopRssiMonitoring(l.2042) failed {.code = ERROR_NOT_AVAILABLE, .description = }
03-04 19:17:28.815  4884  4884 E wpa_supplicant: wpa_driver_nl80211_driver_cmd: failed to issue private commands
03-04 19:17:28.816   945  2890 E SupplicantStaIfaceHal: ISupplicantStaIface.setBtCoexistenceMode failed: {.code = FAILURE_UNKNOWN, .debugMessage = }
03-04 19:17:28.822   945  2897 D ConnectivityService: NetworkAgentInfo [WIFI () - 144] EVENT_NETWORK_INFO_CHANGED, going from CONNECTED to DISCONNECTED
03-04 19:17:28.823   945  2897 D ConnectivityService: NetworkAgentInfo [WIFI () - 144] got DISCONNECTED, was satisfying 11
03-04 19:17:28.833   527  5505 I netd    : trafficSwapActiveStatsMap() <2.36ms>
03-04 19:17:28.843   527  5505 I netd    : tetherGetStats() <7.27ms>
03-04 19:17:28.900   945  1001 I GnssNetworkConnectivityHandler: Network connection lost. Available networks count: 0
03-04 19:17:28.901   945  1001 I GnssNetworkConnectivityHandler: updateNetworkState, state=CLOSED, connected=false, network=144, capabilities=[ Transports: WIFI Capabilities: NOT_METERED&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&VALIDATED&NOT_ROAMING&FOREGROUND&NOT_CONGESTED&NOT_SUSPENDED LinkUpBandwidth>=1048576Kbps LinkDnBandwidth>=1048576Kbps SignalStrength: -55 SSID: "Guest LAN"], apn: null, availableNetworkCount: 0
03-04 19:17:28.904   568   568 E DataItemsFactoryProxy: createNewDataItem:63]: failed to load library libdataitems.so; error=dlopen failed: library "libloc_stub.so" not found
03-04 19:17:28.906   527  5505 I netd    : idletimerRemoveInterface("wlan0", 15, "1") <3.64ms>
03-04 19:17:28.912   945  2897 D ConnectivityService: Sending DISCONNECTED broadcast for type 1 NetworkAgentInfo [WIFI () - 144] isDefaultNetwork=true
03-04 19:17:28.913   500   500 W /vendor/bin/hw/android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
03-04 19:17:28.914   500   500 W /vendor/bin/hw/android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
03-04 19:17:28.916   466   470 D DrmLibTime: got the req here! ret=0
03-04 19:17:28.916   466   470 D DrmLibTime: command id, time_cmd_id = 770
03-04 19:17:28.917   466   470 D DrmLibTime: time_getutcsec starts!
03-04 19:17:28.917   466   470 D DrmLibTime: QSEE Time Listener: time_getutcsec
03-04 19:17:28.917   466   470 D DrmLibTime: QSEE Time Listener: get_utc_seconds
03-04 19:17:28.918   466   470 D DrmLibTime: QSEE Time Listener: time_get_modem_time
03-04 19:17:28.918   466   470 D DrmLibTime: QSEE Time Listener: Checking if ATS_MODEM is set or not.
03-04 19:17:28.918   466   470 D QC-time-services: Lib:time_genoff_operation: pargs->base = 13
03-04 19:17:28.919   466   470 D QC-time-services: Lib:time_genoff_operation: pargs->operation = 2
03-04 19:17:28.919   466   470 D QC-time-services: Lib:time_genoff_operation: pargs->ts_val = 0
03-04 19:17:28.920   466   470 E QC-time-services: Lib:time_genoff_operation: Connection failed !!
03-04 19:17:28.920   466   470 D DrmLibTime: QSEE Time Listener: ATS_MODEM is not set. Fallback to Android system time.
03-04 19:17:28.920   466   470 D DrmLibTime: QSEE Time Listener: Retrieved Android system time: 1583345848
03-04 19:17:28.921   466   470 D DrmLibTime: time_getutcsec returns 0, sec = 1583345848; nsec = 0
03-04 19:17:28.922   527  5505 I netd    : bandwidthSetGlobalAlert(2097152) <0.50ms>
03-04 19:17:28.929   527   803 D TcpSocketMonitor: suspending tcpinfo polling
03-04 19:17:28.930   527   803 I netd    : networkDestroy(144) <6.20ms>
03-04 19:17:28.932   527   803 I netd    : destroyNetworkCache(144) <0.06ms>
03-04 19:17:28.933   466   470 D DrmLibTime: time_getutcsec finished! 
03-04 19:17:28.944   466   470 D DrmLibTime: iotcl_continue_command finished! and return 0 
03-04 19:17:28.944   466   470 D DrmLibTime: before calling ioctl to read the next time_cmd
03-04 19:17:28.979   500   500 W /vendor/bin/hw/android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
03-04 19:17:28.980   500   500 W /vendor/bin/hw/android.hardware.keymaster@3.0-service: Not performing software digesting for symmetric cipher keys
03-04 19:17:28.981   466   470 D DrmLibTime: got the req here! ret=0
03-04 19:17:28.982   466   470 D DrmLibTime: command id, time_cmd_id = 770
03-04 19:17:28.982   466   470 D DrmLibTime: time_getutcsec starts!
03-04 19:17:28.982   466   470 D DrmLibTime: QSEE Time Listener: time_getutcsec
03-04 19:17:28.983   466   470 D DrmLibTime: QSEE Time Listener: get_utc_seconds
03-04 19:17:28.983   466   470 D DrmLibTime: QSEE Time Listener: time_get_modem_time
03-04 19:17:28.983   466   470 D DrmLibTime: QSEE Time Listener: Checking if ATS_MODEM is set or not.
03-04 19:17:28.984   466   470 D QC-time-services: Lib:time_genoff_operation: pargs->base = 13
03-04 19:17:28.984   466   470 D QC-time-services: Lib:time_genoff_operation: pargs->operation = 2
03-04 19:17:28.984   466   470 D QC-time-services: Lib:time_genoff_operation: pargs->ts_val = 0
03-04 19:17:28.985   466   470 E QC-time-services: Lib:time_genoff_operation: Connection failed !!
03-04 19:17:28.985   466   470 D DrmLibTime: QSEE Time Listener: ATS_MODEM is not set. Fallback to Android system time.
03-04 19:17:28.985   466   470 D DrmLibTime: QSEE Time Listener: Retrieved Android system time: 1583345848
03-04 19:17:28.987   466   470 D DrmLibTime: time_getutcsec returns 0, sec = 1583345848; nsec = 0
03-04 19:17:28.987   466   470 D DrmLibTime: time_getutcsec finished! 
03-04 19:17:28.987   466   470 D DrmLibTime: iotcl_continue_command finished! and return 0 
03-04 19:17:28.988   466   470 D DrmLibTime: before calling ioctl to read the next time_cmd
03-04 19:17:28.994   945  2890 D WifiCountryCode: updateCountryCode to DE
03-04 19:17:28.994  4884  4884 E wpa_supplicant: wpa_driver_nl80211_driver_cmd: failed to issue private commands
03-04 19:17:28.995   945  2890 E SupplicantStaIfaceHal: ISupplicantStaIface.setCountryCode failed: {.code = FAILURE_UNKNOWN, .debugMessage = }
03-04 19:17:28.996   945  2890 D WifiCountryCode: Failed to set country code to: DE
03-04 19:17:28.996   945  2890 D WifiClientModeImpl: Start Disconnecting Watchdog 45
03-04 19:17:28.997   527   803 I netd    : interfaceGetCfg("wlan0") <0.35ms>
03-04 19:17:28.998   945  2890 E WifiVendorHal: stopRssiMonitoring(l.2042) failed {.code = ERROR_NOT_AVAILABLE, .description = }
03-04 19:17:29.000  4884  4884 E wpa_supplicant: wpa_driver_nl80211_driver_cmd: failed to issue private commands
03-04 19:17:29.004   945  2890 E SupplicantStaIfaceHal: ISupplicantStaIface.setBtCoexistenceMode failed: {.code = FAILURE_UNKNOWN, .debugMessage = }
03-04 19:17:29.005   945  2890 I WifiClientModeImpl: disconnectedstate enter
03-04 19:17:29.024   945  2890 D WifiNetworkAgent: NetworkAgent: NetworkAgent channel lost
03-04 19:17:32.308   945 10652 D WificondControl: Scan result ready event
03-04 19:17:32.328   945  2890 D WifiClientModeImpl: CMD_START_CONNECT sup state DisconnectedState my state DisconnectedState nid=0 roam=false
03-04 19:17:32.334   945  2890 I WifiClientModeImpl: Connecting with dc:ef:ca:99:e8:60 as the mac address
03-04 19:17:32.335   692   692 W wificond: Scan is not started. Ignore abort request
03-04 19:17:32.336   945  2890 D SupplicantStaIfaceHal: connectToNetwork "Guest LAN"WPA_PSK
03-04 19:17:32.337   945  2890 D SupplicantStaIfaceHal: Network is already saved, will not trigger remove and add operation.
03-04 19:17:32.352  4884  4884 I wpa_supplicant: wlan0: Trying to associate with SSID 'Guest LAN'
```

**Comment by vknecht** [comment]
@chris42 : thanks for the feedback !
Setting this PR out of draft-status for closer review, especially if you tested it since last force-push ~15 days ago when I tried rebasing it on latest 4.9 but think I messed it, tho there should be no impact since all changes are limited to backports/drivers/net/wireless/broadcom/brcm80211/ subdir and there were no other changes in there.
Don't know about the specific drop-out you encountered... Maybe 632a398 and 
b448453  from recent #2212 may help, also there were quite a few mainline improvements to brcmfmac which are not included in this present PR since they rely on changes outside [backports]/drivers/net/wireless/broadcom/brcm80211/brcmfmac/

**Comment by chris42** [comment]
@vknecht Not sure about the two commits. They seem to be specific for a certain chip version? Hence not sure in which devices they are used. Do you know a way to find out?

**Comment by vknecht** [comment]
@chris42 According to boot logs, Loire devices uses the 4345[5] chip:
_brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6_
so these two commits look relevant to me.

**Comment by chris42** [comment]
@vknecht So I checked the commits. As much as I can see they are both already part of current 2.3.2.r1.4.

**Comment by vknecht** [comment]
@chris42 Sorry, I should have checked before mentioning them...

It could be that [more recent upstream commits](https://github.com/torvalds/linux/commits/master/drivers/net/wireless/broadcom/brcm80211/brcmfmac) help with the remaining bugs/problems but some require changes outside brcmfmac directory (eg. the other ones from 2019-06-18 about not trying to re-tune the card on wake<->sleep transition)...

**Comment by chris42** [comment]
So, I am new to this, but always curious. Basically I take all the commits and would test them, if they A. break something B. Improve something?
What is the issue with the changes outside of the brcmfmac directory? The next ones you mentioned would change something around in some atheros config. As long as they work it should not be a problem?

**Comment by vknecht** [comment]
See for example torvalds/linux@2de0b42: it only adds calls to `sdio_retune_crc_disable()` and `sdio_retune_crc_enable()`, however those functions don't exist in our 4.9 tree, so we'd have to also integrate torvalds/linux@0a55f4ab which changes files in `drivers/mmc/core/` and `include/linux/mmc/`
From what I understood about backported drivers, those changes would have to be done (meaning, adding files) in `backports/drivers/mmc/core/` and `backports/include/linux/mmc/`
That's where the method using only `git am` has its limits (ie. okay-ish when only existing `backports/drivers/net/wireless/broadcom/` files are touched), and why I asked about running the backport procedure again in the first post...

**Comment by chris42** [comment]
As I understood that procedure, it is basically automating the task of checking and gathering the commits? Sounds interesting, but again seems to be way above my level of skill and knowledge.

**Comment by chris42** [comment]
I played around with the backports project. The patches seem to apply to a 4.9.214 Sony tree without issues, however I get a patch failure on the makefile. I tested this against the regular linux-stable and get the same errors there.
Will see if I can figure out what is wrong there.

If I actually get an integrated tree on the Sony tree, is there any reason not to try it on a device? Could any damage happen?

**Comment by chris42** [comment]
So after banging my head on the backports project for a while, I am not sure, if it will help us. I can't find a way to isolate the source changes only for a brcmfmac backport. All the stuff I found basically take all driver backports and then only build the requested modules. However on a source level I would need to configure the copy-list for which I would need an understanding which files are affected. This brings us full circle to the beginning. :-D

The alternative would be to use the backport driver modules in the kernel build?!

**Comment by chris42** [comment]
Would it make sense to merge this? I have it now running for the last few builds and wifi stability has improved.

**Comment by stefanhh0** [comment]
Afaik this PR is not relevant for Yohino/Lilac nevertheless I just picked it and found as expected nothing unusual.

It has been tested successfully on Loire/Kugo by @chris42 and on Tone/Kagura by @ix5.

@jerpelea Should there be done more testing on other devices or are there any other reasons currently to not merge it back as is?

**Pull request merged**
