### PR TITLE
drivers: video: backlight: sort the config option by name

### PR DESCRIPTION
**Pull request by humberos**
the LM3630 should be previous, then LM3639

Signed-off-by: Humberto Borba humberos@gmail.com
Change-Id: Iec65b742730dcd65bcfe4612d52f3e4060f3960a

### CODE REVIEW

**Comment by jerpelea** [comment]
There is no benefit added by this change

**Comment by humberos** [comment]
Yeah! No functional benefit.
It just reduces diffs between CAF.

**Comment by kholk** [comment]
Please don't touch Kconfig files.
I wanted things like that for easy porting between CAF branches.

**Comment by jerpelea** [comment]
This one reduces diff.is ok

**Pull request merged**
