### PR TITLE
missing files for build

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
ubports attempt

**Comment by ghost** [comment]
sorry for being a noob

**Comment by Thaodan** [comment]
You have to either add those modules as submodule or use them as they are in the manifest:
https://github.com/sonyxperiadev/local_manifests/blob/master/LA.UM.9.12.r1.xml#L12

Submodules:
https://github.com/mer-hybris/android_kernel_sony_msm/blob/hybris-sony-aosp/LA.UM.9.12.r1/.gitmodules

**Comment by MartinX3** [comment]
Please take a look how the title and description and commit metadata looks like in the other PR's

**Comment by jerpelea** [comment]
please re-base and clean the commits.

**Pull request closed without merging**
