### PR TITLE
[64r1] [LOIRE] Fix MSM8956 battery drainage issue

### PR DESCRIPTION
**Pull request by kholk**
The GFX3D clock's power supply was getting stuck because of invalid refcounts: this was producing an anomalous battery consumption issue that was draining it fast.

Fix the issue by giving it the proper supplies and refactor the clock declarations to remove uselessly DT-declared clock tables and make them static.

Also, cleanup the DTs from missed leftovers.

### CODE REVIEW

**Comment by alviteri** [comment]
testing kugo

**Comment by kholk** [comment]
@alviteri Recompile with the newly pushed commit, it's a really important one.

**Comment by kholk** [comment]
@oshmoun go for it! :)))

**Comment by oshmoun** [comment]
kgsl doesn't seem to like the new freqs :sweat_smile:

**Comment by oshmoun** [comment]
The affected gpu frequency has been updated, and kgsl-3d reports the correct rate
https://github.com/sonyxperiadev/kernel/pull/1618

**Pull request merged**
