### PR TITLE
[57r1] Loire updates + driver upgrades

### PR DESCRIPTION
**Pull request by kholk**
Tested on Kugo, Suzu, Poplar

### CODE REVIEW

**Comment by oshmoun** [comment]
causes build errors on keyaki in the current state
```
../../../../../../kernel/sony/msm/drivers/media/platform/msm/sde/rotator/sde_rotator_dev.c:469:20: warning: passing argument 1 of 'cancel_work_sync' from incompatible pointer type 
error, forbidden warning: sde_rotator_dev.c:469
```

**Comment by alviteri** [comment]
last commit needs an update in cameraHAL too

**Comment by kholk** [comment]
the warning has to be fixed.
the commit that should need an update to camera hal is refactored and marked as PORT, so that it does NOT require any hal upgrade.

**Comment by alviteri** [comment]
https://github.com/SonyAosp/platform_hardware_qcom_camera/commits/clock

**Comment by kholk** [comment]
Don't commit this on hal. I want to stay compatible with our caf tag and that's why I modified the commit.

**Comment by kholk** [comment]
Alternatively, I will just remove the modified commit and we will evaluate the benefits. After that we'll see.

**Pull request merged**
