### PR TITLE
[6.4.r1] arm: defconfig: kugo: Change CONFIG_HZ value

### PR DESCRIPTION
**Pull request by tomgus1**
This is to be the same as for bullhead

Discussed with @kholk 
This won't have as big an effect on kugo as it is 720p this will mean that 120Hz functionality cannot be used but due to 720p this isn't supported anyway.

### CODE REVIEW

**Comment by danielgusvt** [comment]
This is not a dt change but a defconfig change!

**Comment by tomgus1** [comment]
Sorry, my bad. Didn't sleep much last night.

**Comment by jerpelea** [comment]
changes are applied / platform

**Comment by jerpelea** [comment]
in sync for all platforms

**Comment by kholk** [comment]
This makes sense only on Kugo, since HZ=1000 is useful only for 1080p and platforms that can achieve 120Hz refresh rate.
Kugo's panel does NOT support 120Hz.

**Comment by jerpelea** [comment]
then all platforms should stay on ths same config since there is a small benefit

**Comment by kholk** [comment]
Oki, then close it

**Pull request closed without merging**
