### PR TITLE
[LA.BR.1.3.3_rb2.14] Kanuti fixes

### PR DESCRIPTION
**Pull request by bartcubbins**
1. Included fix for Tulip versions with CYTTSP5 touchscreen. Now it works and happy.
2. Update Capella CM36686 sensor driver permissions.
3. Fix Bosch sensors VDD and VIO regulators.
4. Disabled unused TPS65132 and FAN53555 regulators.
5. CYTTSP4/5 pins and regulators were updated.
6. ADSP loader commit was ported from k4.4, without this change on the Tulip devices, the initialization from the successful kernel probe to the appearance of the bootanimation has decreased from 70+ seconds to 6-8 seconds.

All changes were successfully tested on different revisions of Tulip device.

### CODE REVIEW

**Comment by jerpelea** [comment]
please test the changes on all platforms

**Comment by jerpelea** [comment]
@kholk

**Comment by bartcubbins** [comment]
suzu looks ok. no regressions
tested with security bulletin pr https://github.com/sonyxperiadev/kernel/pull/1568

**Comment by kholk** [comment]
Nothing can really go wrong with that one. Safe to merge!

**Pull request merged**
