### PR TITLE
lena camera dts changes

### PR DESCRIPTION
**Pull request by sraase**

### CODE REVIEW

**Comment by Thaodan** [comment]
Why is wl2864c there then if it servers no purpose?

**Comment by jerpelea** [comment]
there is usually a difference between a QCOM reference board and a final product

**Comment by sraase** [comment]
> Why is wl2864c there then if it servers no purpose?

There is no regulator driver for it. But we can use its default configuration and save a lot of headache.

**Comment by MarijnS95** [comment]
In other words, in the current tree there's no driver that handles `qualcomm,gpio_wl2864c` nor `qualcomm,i2c_wl2864c`. @sraase what default are you referring to, the default this regulator provides when it is being turned on through `gpios = <&tlmm 58 GPIO_ACTIVE_HIGH>;` without being - supposedly - configured over i2c?

**Comment by sraase** [comment]
Correct. The wl2864c datasheet is publicly available from OmniVision.

**Pull request merged**
