### PR TITLE
[1.2.2] drivers: misc: nfc: Add pn547 pinctrl support (IOCTL)

### PR DESCRIPTION
**Pull request by humberos**
NFC driver adaptation for pinctrl (kitakami devices).

### CODE REVIEW

**Comment by humberos** [comment]
this is another way to get pinctrl for nfc.
but i2c is broken.

http://paste.omnirom.org/view/0727f038

**Comment by Kali-** [comment]
instead of rename to 89X4 is not better to remove completly?

**Comment by jerpelea** [comment]
We dont need it on 8226

**Comment by Kali-** [comment]
ofc, but it name look wrong, i guess it should be related to PM and not to SoC

**Comment by humberos** [comment]
Ok. 
I am sorry but IMHO I think that we should expend our time by trying to getting Nfc pinctrl fixed then after that work we'll can discuss more about config naming.

**Comment by humberos** [comment]
More details about driver: http://paste.omnirom.org/view/c707c839

Seems the i2c is crashing when:
pn547_dev_write : writing 246 bytes.

Buffer size?

**Comment by humberos** [comment]
we need the @kholk 's ninja sword here once again!

**Comment by kholk** [comment]
Ninja sword in 24h. Testing a big kernel update first, then taking this.

"Problem solved" :P

**Comment by humberos** [comment]
NFC works!
Tested on karin.

**Comment by kholk** [comment]
Wonderful Humberto!
Don't modify msm8994.dtsi, put the changes into kitakami common dtsi!

**Comment by humberos** [comment]
Done.
Ready to push!

**Comment by humberos** [comment]
@kholk the i2c transfer mode must be the MHL issue on Z5 devices!

**Pull request merged**
