### PR TITLE
[2.3.2.r1.4] Linux 4.9.230

### PR DESCRIPTION
**Pull request by chris42**
Due to popular request, all in one PR.
source kernel.org

Please see each commit for merge conflict details.
Builds and device boots, audio, bluetooth/nfc, wifi, phone working

Tested on Kugo further test on other legacy devices would be appreciated.

### CODE REVIEW

**Comment by chris42** [comment]
@nathanchance @stefanhh0  Guess it then makes sense to continue here

**Comment by chris42** [comment]
@kholk would be nice if you check the crypto stuff

**Comment by chris42** [comment]
So anyone wants to test this as well? It is now working on my Kugo for 2 Weeks...

**Comment by chris42** [comment]
@jerpelea I think this can be merged. It is running on my phone now for 3 weeks, without issues. As no one else takes a look this has to be enough.

**Comment by jerpelea** [comment]
please rebase before I can merged it

**Comment by chris42** [comment]
Huh, I do not see changes in 2.3.2.r1.4?

**Pull request merged**
