### PR TITLE
[2.3.2.r1.4] Linux 4.9.216

### PR DESCRIPTION
**Pull request by stefanhh0**
For following files merge conflicts had to be resolved manually:
- `drivers/usb/gadget/composite.c` -> Manually resolved the merge conflicts and aligned the code to comply with kernel.org
- `drivers/gpu/drm/msm/msm_drv.c` -> Manually resolved the merge conflict. Found that shrinker support is not available, is that a problem? Should we add it? Could give it a try to add it in a separate PR if it makes sense:
  ```
  Autor: Rob Clark <robdclark@gmail.com>  2016-05-17 21:44:49
  Eintragender: Rob Clark <robdclark@gmail.com>  2016-07-16 16:09:05
  Eltern: 96a611b54f7f0564886d64c43485402fa2530bf4 (drm/msm/mdp5: Update compatible strings for MDSS/MDP5)
  Kind:  68209390f116034449fa6a3ae03f7b100b3d894a (drm/msm: shrinker support)
  Zweig: 4.9.215, 4.9.216, remotes/origin/4.9.215 und weitere (36)
  Folgt auf: v4.7-rc5
  Vorgänger von: v4.8-rc1

      drm/msm: add madvise ioctl

      Doesn't do anything too interesting until we wire up shrinker.  Pretty
      much lifted from i915.

      Signed-off-by: Rob Clark <robdclark@gmail.com>
  ```
- `drivers/usb/gadget/function/f_fs.c` -> Manually resolved the merge conflict, kept logging and changed to spin_lock_irq... function with flags parameter
- `fs/ext4/super.c` -> Manually resolved merge conflicts, in the end easy to resolve. Patch tool couldn't match because of limited context

### CODE REVIEW

**Comment by stefanhh0** [comment]
This builds fine and already runs on my phone (yoshino/lilac) for more than half an hour stable :-) Please feel free to test it and it would be great if someone could also have a look at the manually resolved merge-conflicts if those are resolved okayish.

**Comment by jerpelea** [comment]
which devices were tested?

**Comment by stefanhh0** [comment]
From my side only Yoshino/Lilac, it ran stable for several days I am now on 4.9.217.

**Comment by chris42** [comment]
Just tested this on Kugo with a build from yesterday, could not spot anything unusual. Tested Wifi, Bluetooth, NFC, Phone - all working. Logs seem to be ok.

**Pull request merged**
