### PR TITLE
[7.1.r1] Various updates, IPAv2 big sanitization, IPAv3 mobile data throughput solutions

### PR DESCRIPTION
**Pull request by kholk**
This patchset contains various updates for all devices, from Yoshino to Kumano, in various fields.
It also contains a big sanitization in the IPAv2 driver and a feature enhancement, as now we can finally use the IOMMU to get more performance during the IPAv2<->ICNSS-WLAN communication.

Tested on SDM630 Ganges Kirin DSDS -- Much lower CPU usage during WiFi data exchange
Tested on MSM8998 Yoshino Maple RoW -- Platform seems to be less prone to random subsystems crashes
Tested on SM8150 Kumano Griffin DSDS -- Bluetooth communication is way stabler now

### CODE REVIEW

**Comment by Haxk20** [comment]
Tested on Nile Pioneer.

**Comment by stefanhh0** [comment]
The commit: 
sched: features: Disable EAS_PREFER_IDLE: https://github.com/sonyxperiadev/kernel/pull/2321/commits/b8856fb6d0ffe221af83df1bf16b0a25071b477c
should be dropped from the changeset. It is already merged back.

**Comment by stefanhh0** [comment]
Tested on yoshino/lilac, the phone is no longer booting into a stable state but crashes and reboots very quickly after entering sim and device pin.

```
[   42.949285] ------------[ cut here ]------------
[   42.949402] WARNING: CPU: 0 PID: 58 at /home/stefan/android/source/kernel/sony/msm-4.14/kernel/kernel/softirq.c:173 __local_bh_enable_ip+0x98/0x108
[   42.949784] ---[ end trace 8a1b6006f51078f4 ]---
[   43.074870] arm-smmu 16c0000.arm,smmu-anoc2: FAR    = 0x00000000146bd080
[   43.074983] arm-smmu 16c0000.arm,smmu-anoc2: PAR    = 0x0000000000000000
[   43.075109] arm-smmu 16c0000.arm,smmu-anoc2: FSR    = 0x40000402 [TF R SS ]
[   43.075166] arm-smmu 16c0000.arm,smmu-anoc2: TTBR0  = 0x0000000000000000
[   43.075267] arm-smmu 16c0000.arm,smmu-anoc2: TTBR1  = 0x0000000000000000
[   43.075323] arm-smmu 16c0000.arm,smmu-anoc2: SCTLR  = 0x00c010e7 ACTLR  = 0x70000000
[   43.075454] arm-smmu 16c0000.arm,smmu-anoc2: CBAR  = 0x0001f300
[   43.075552] arm-smmu 16c0000.arm,smmu-anoc2: MAIR0   = 0xf404ff44 MAIR1   = 0x000000e4
[   43.075651] arm-smmu 16c0000.arm,smmu-anoc2: translation fault!
[   43.075795] arm-smmu 16c0000.arm,smmu-anoc2: PAR = 0x100000203
[   43.075943] arm-smmu 16c0000.arm,smmu-anoc2: translation fault!
[   43.076038] arm-smmu 16c0000.arm,smmu-anoc2: PAR = 0x100000203
[   43.076157] arm-smmu 16c0000.arm,smmu-anoc2: Unhandled context fault: iova=0x146bd080, cb=1, fsr=0x40000402, fsynr0=0x1, fsynr1=0x1030023
[   43.076256] arm-smmu 16c0000.arm,smmu-anoc2: soft iova-to-phys=0x0000000000000000
[   43.076356] arm-smmu 16c0000.arm,smmu-anoc2: SOFTWARE TABLE WALK FAILED! Looks like 16c0000.arm,smmu-anoc2 accessed an unmapped address!
[   43.076452] arm-smmu 16c0000.arm,smmu-anoc2: hard iova-to-phys (ATOS) failed
[   43.076550] arm-smmu 16c0000.arm,smmu-anoc2: SID=0x18e0
[   43.076601] arm-smmu 16c0000.arm,smmu-anoc2: Unhandled arm-smmu context fault!
[   43.076744] kernel BUG at /home/stefan/android/source/kernel/sony/msm-4.14/kernel/drivers/iommu/arm-smmu.c:1600!
[   43.076842] Internal error: Oops - BUG: 0 [#1] PREEMPT SMP
[   43.076898] Modules linked in:
[   43.076997] Process irq/169-arm-smm (pid: 725, stack limit = 0xffffffc0e2b20000)
[   43.077053] CPU: 1 PID: 725 Comm: irq/169-arm-smm Tainted: G S      W       4.14.188-24356-gd02f3f6a11cc-dirty #1
[   43.077148] Hardware name: SoMC Lilac-ROW(MSM8998 v2.1) (DT)
[...]
[   43.080038] Call trace:
[   43.080094]  arm_smmu_context_fault+0x584/0x5f0
[   43.080149]  irq_thread_fn+0x2c/0x70
[   43.080243]  irq_thread+0x130/0x20c
[   43.080295]  kthread+0x118/0x128
[   43.080348]  ret_from_fork+0x10/0x18
[   43.080402] Code: f9400320 f00099c1 912b4021 94061e17 (d4210000) 
[   43.080497] ---[ end trace 8a1b6006f51078f5 ]---
```

`/sys/fs/pstore`
[console-ramoops-0.log](https://github.com/sonyxperiadev/kernel/files/4944049/console-ramoops-0.log)
[dmesg-ramoops-0.log](https://github.com/sonyxperiadev/kernel/files/4944050/dmesg-ramoops-0.log)
[dmesg-ramoops-1.log](https://github.com/sonyxperiadev/kernel/files/4944051/dmesg-ramoops-1.log)
[pmsg-ramoops-0.log](https://github.com/sonyxperiadev/kernel/files/4944052/pmsg-ramoops-0.log)

**Comment by stefanhh0** [comment]
Without inserted SIM the phone seems to be more stable.

**Comment by kholk** [comment]
Mobile data is producing this issue on Nile and Ganges as well, thanks for the test.

Added DNM status until the issue is solved.

**Comment by kholk** [comment]
Pushed a commit that fixes the mobile data crash issues on SDM630/660 SoC.

**Comment by kholk** [comment]
Pushed commits to fix issues with MSM8998 Yoshino mobile data crashes.

DNM status removed: ready to merge.

**Comment by kholk** [comment]
Added commits to optimize IPA performance on MSM8998, SDM630,660,845.
Now MSM8998 Yoshino reaches 100Mbps on LTE (needs userspace commits to
achieve the performance).

**Pull request merged**
